/* generated by Id 1.1 at èÚ² */
/* with the command: -I../../stage2/ -I../../st80 -g -m slotnames.st -o slotnames.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s_new_5f_= 0;
static oop s__2d= 0;
static oop s_new= 0;
static oop s_slotNameAt_= 0;
static oop s__5fslotNameAt_5f_= 0;
static oop s__5fintegerValue= 0;
static oop s_value_5f_= 0;
static oop s_slotOffsetAt_= 0;
static oop s__5fimport_= 0;
static oop s__5fslotOffsetAt_5f_= 0;
static oop s_slotSizeAt_= 0;
static oop s__5fslotSizeAt_5f_= 0;
static oop s__2d_3e= 0;
static oop s__2b= 0;
static oop s_printString= 0;
static oop s_function_5f_arity_5f_= 0;
static oop s_function_5f_arity_5f_outer_state_nlr_5f_= 0;
static oop s__5fslots= 0;
static oop s_ifTrue_= 0;
static oop s_slots= 0;
static oop s_whileTrue_= 0;
static oop s_putln= 0;
static oop s_at_put_= 0;
static oop s_println= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "new_:", &s_new_5f_ },
  { "-", &s__2d },
  { "new", &s_new },
  { "slotNameAt:", &s_slotNameAt_ },
  { "_slotNameAt_:", &s__5fslotNameAt_5f_ },
  { "_integerValue", &s__5fintegerValue },
  { "value_:", &s_value_5f_ },
  { "slotOffsetAt:", &s_slotOffsetAt_ },
  { "_import:", &s__5fimport_ },
  { "_slotOffsetAt_:", &s__5fslotOffsetAt_5f_ },
  { "slotSizeAt:", &s_slotSizeAt_ },
  { "_slotSizeAt_:", &s__5fslotSizeAt_5f_ },
  { "->", &s__2d_3e },
  { "+", &s__2b },
  { "printString", &s_printString },
  { "function_:arity_:", &s_function_5f_arity_5f_ },
  { "function_:arity_:outer:state:nlr_:", &s_function_5f_arity_5f_outer_state_nlr_5f_ },
  { "_slots", &s__5fslots },
  { "ifTrue:", &s_ifTrue_ },
  { "slots", &s_slots },
  { "whileTrue:", &s_whileTrue_ },
  { "putln", &s_putln },
  { "at:put:", &s_at_put_ },
  { "println", &s_println },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Character {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Fraction {
  struct _vtable *_vtable[0];
  oop v_numerator;
  oop v_denominator;
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargePositiveInteger {
  struct _vtable *_vtable[0];
  oop v_bytes;
};
struct t_LargeNegativeInteger {
  struct _vtable *_vtable[0];
  oop v_bytes;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_ImmutableArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_WordArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__words;
};
struct t_ImmutableWordArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__words;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_ImmutableByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_ImmutableString {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
struct t_CharacterTable {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_LookupKey {
  struct _vtable *_vtable[0];
  oop v_key;
};
struct t_Association {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t_AVLTreeNode {
  struct _vtable *_vtable[0];
  oop v_left;
  oop v_right;
  oop v_height;
  oop v_value;
};
struct t_AVLTree {
  struct _vtable *_vtable[0];
  oop v_rootNode;
  oop v_orderBlock;
};
struct t_Set {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
};
struct t_OrderedCollection {
  struct _vtable *_vtable[0];
  oop v_array;
  oop v_firstIndex;
  oop v_lastIndex;
};
struct t_Dictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
};
struct t_IdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
};
struct t_IdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
};
struct t_Stream {
  struct _vtable *_vtable[0];
};
struct t_PositionableStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_ReadStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_GetOpt {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
  oop v_defaultBlock;
};
struct t_Smalltalk {
  struct _vtable *_vtable[0];
  oop v_argumentCount;
  oop v_argumentVector;
};
struct t_SymbolTable {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
};
struct t_WriteStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_writeLimit;
};
struct t_SelectorTable {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
};
struct t_PerformWithArgumentsSelectors {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
static oop l_2= 0;
static oop l_5= 0;
static oop l_8= 0;
static oop l_11= 0;
static oop l_12= 0;
static oop v__object= 0;
static oop v__vector= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_StaticBlockClosure= 0;
static oop v_BlockClosure= 0;
static oop v_Magnitude= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_SmallInteger= 0;
static oop v_LargePositiveInteger= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_Array= 0;
static oop v_WordArray= 0;
static oop v_ByteArray= 0;
static oop v_String= 0;
static oop v_ImmutableString= 0;
static oop v_nil= 0;
static oop v_LookupKey= 0;
static oop v_Set= 0;
static oop v_Dictionary= 0;
static oop v_IdentityDictionary= 0;
static oop v_Stream= 0;
static oop v_PositionableStream= 0;
static struct __methodinfo __info1= { "slotNameAt:", "Object", "/Users/chazu/dev/c/idst-with-history/object/examples/slotnames/slotnames.st", 0, 3, 9, 0 };
static oop Object__slotNameAt_(oop v__closure, oop v_stateful_self, oop v_self, oop v_index)
 {
  _enter(&__info1);
  oop v__name= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  (void)v__name;
  _line(3);
  /* ifTrue: */
  _1= 0;
  _2= v_self;
  _3= v_index;
  _4= l_2;
  {
    int _l= (long)_3 >> 1;
    int _r= (long)_4 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_3) && ((_s ^ (_s << 1)) >= 0))  _3= (oop)(long)(_s << 1 | 1);  else _3= _sendv(s__2d, 2, _3, _4);
  }
  _line(6);
  _3=_sendv(s__5fintegerValue, 1, _3);
  _line(6);
  _2=_sendv(s__5fslotNameAt_5f_, 2, _2, _3);
  v__name= _2;
  if (!_2) goto _l1;
 {
  _1= v_String;
  _2= v__name;
  _line(6);
  _1=_sendv(s_value_5f_, 2, _1, _2);
 }
 _l1:;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info3= { "_slotNameAt_:", "Object", "/Users/chazu/dev/c/idst-with-history/object/examples/slotnames/slotnames.st", 0, 9, 20, &__info1 };
static oop Object___5fslotNameAt_5f_(oop v__closure, oop v_stateful_self, oop v_self, oop v__index)
 {
  _enter(&__info3);
  oop v__slots= 0;
  oop _1= 0;
  (void)v__slots;
  _line(9);
  _1= v_self;
  _line(12);
  _1=_sendv(s__5fslots, 1, _1);
  v__slots= _1;
 {
# define self ((struct t_Object *)v_self)

	long index= (long)v__index;
	struct __slotinfo *info= (struct __slotinfo *)v__slots;
	return (oop)(info[index].name);
    
# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info4= { "slotOffsetAt:", "Object", "/Users/chazu/dev/c/idst-with-history/object/examples/slotnames/slotnames.st", 0, 20, 25, &__info3 };
static oop Object__slotOffsetAt_(oop v__closure, oop v_stateful_self, oop v_self, oop v_index)
 {
  _enter(&__info4);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  _line(20);
  _1= v_SmallInteger;
  _2= v_self;
  _3= v_index;
  _4= l_5;
  {
    int _l= (long)_3 >> 1;
    int _r= (long)_4 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_3) && ((_s ^ (_s << 1)) >= 0))  _3= (oop)(long)(_s << 1 | 1);  else _3= _sendv(s__2d, 2, _3, _4);
  }
  _line(22);
  _3=_sendv(s__5fintegerValue, 1, _3);
  _line(22);
  _2=_sendv(s__5fslotOffsetAt_5f_, 2, _2, _3);
  _line(22);
  _1=_sendv(s_value_5f_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info6= { "_slotOffsetAt_:", "Object", "/Users/chazu/dev/c/idst-with-history/object/examples/slotnames/slotnames.st", 0, 25, 36, &__info4 };
static oop Object___5fslotOffsetAt_5f_(oop v__closure, oop v_stateful_self, oop v_self, oop v__index)
 {
  _enter(&__info6);
  oop v__slots= 0;
  oop _1= 0;
  (void)v__slots;
  _line(25);
  _1= v_self;
  _line(28);
  _1=_sendv(s__5fslots, 1, _1);
  v__slots= _1;
 {
# define self ((struct t_Object *)v_self)

	long index= (long)v__index;
	struct __slotinfo *info= (struct __slotinfo *)v__slots;
	return (oop)(info[index].offset);
    
# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info7= { "slotSizeAt:", "Object", "/Users/chazu/dev/c/idst-with-history/object/examples/slotnames/slotnames.st", 0, 36, 41, &__info6 };
static oop Object__slotSizeAt_(oop v__closure, oop v_stateful_self, oop v_self, oop v_index)
 {
  _enter(&__info7);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  _line(36);
  _1= v_SmallInteger;
  _2= v_self;
  _3= v_index;
  _4= l_8;
  {
    int _l= (long)_3 >> 1;
    int _r= (long)_4 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_3) && ((_s ^ (_s << 1)) >= 0))  _3= (oop)(long)(_s << 1 | 1);  else _3= _sendv(s__2d, 2, _3, _4);
  }
  _line(38);
  _3=_sendv(s__5fintegerValue, 1, _3);
  _line(38);
  _2=_sendv(s__5fslotSizeAt_5f_, 2, _2, _3);
  _line(38);
  _1=_sendv(s_value_5f_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info9= { "_slotSizeAt_:", "Object", "/Users/chazu/dev/c/idst-with-history/object/examples/slotnames/slotnames.st", 0, 41, 52, &__info7 };
static oop Object___5fslotSizeAt_5f_(oop v__closure, oop v_stateful_self, oop v_self, oop v__index)
 {
  _enter(&__info9);
  oop v__slots= 0;
  oop _1= 0;
  (void)v__slots;
  _line(41);
  _1= v_self;
  _line(44);
  _1=_sendv(s__5fslots, 1, _1);
  v__slots= _1;
 {
# define self ((struct t_Object *)v_self)

	long index= (long)v__index;
	struct __slotinfo *info= (struct __slotinfo *)v__slots;
	return (oop)(info[index].size);
    
# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info10= { "slots", "Object", "/Users/chazu/dev/c/idst-with-history/object/examples/slotnames/slotnames.st", 0, 52, 65, &__info9 };
static oop Object__slots(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info10);
  oop v_index= 0;
  oop v_slots= 0;
  oop v_name= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  oop _5= 0;
  (void)v_index;
  (void)v_slots;
  (void)v_name;
  _line(52);
  _1= l_11;
  v_index= _1;
  _1= v_IdentityDictionary;
  _line(56);
  _1=_sendv(s_new, 1, _1);
  v_slots= _1;
  /* whileTrue: */
  goto _l3;
 _l2:;
 {
  _1= v_slots;
  _2= v_name;
  _3= v_self;
  _4= v_index;
  _line(59);
  _3=_sendv(s_slotOffsetAt_, 2, _3, _4);
  _4= v_self;
  _5= v_index;
  _line(59);
  _4=_sendv(s_slotSizeAt_, 2, _4, _5);
  _line(59);
  _3=_sendv(s__2d_3e, 2, _3, _4);
  _line(59);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _1= v_index;
  _2= l_11;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  v_index= _1;
 }
 _l3:;
 {
  _1= v_self;
  _2= v_index;
  _line(57);
  _1=_sendv(s_slotNameAt_, 2, _1, _2);
  v_name= _1;
 }
  if (_1) goto _l2;
  _1= 0;
  _1= v_index;
  _line(61);
  _1=_sendv(s_println, 1, _1);
  _1= v_slots;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info12= { "[] ?", "?", "/Users/chazu/dev/c/idst-with-history/object/examples/slotnames/slotnames.st", 0, 0, 0, &__info10 };
static oop b_12(oop v__closure, oop v__self)
 {
  _enter(&__info12);
  oop _1= 0;
  _line(67);
  _1= v_nil;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info13= { "[] ?", "?", "/Users/chazu/dev/c/idst-with-history/object/examples/slotnames/slotnames.st", 0, 0, 0, &__info12 };
static oop b_13(oop v__closure, oop v__self)
 {
  _enter(&__info13);
  oop _1= 0;
  _line(68);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* x */
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "slotnames.st", 0, 0, 0, &__info13 };
void __id__init__(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info1);

  _sendv(s__5fimport_, 3, _libid->_object, "st80", "__id__init__st80");
  v__object= _libid->import("_object");
  v__vector= _libid->import("_vector");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_BlockClosure= _libid->import("BlockClosure");
  v_Magnitude= _libid->import("Magnitude");
  v_Number= _libid->import("Number");
  v_Integer= _libid->import("Integer");
  v_SmallInteger= _libid->import("SmallInteger");
  v_LargePositiveInteger= _libid->import("LargePositiveInteger");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_Array= _libid->import("Array");
  v_WordArray= _libid->import("WordArray");
  v_ByteArray= _libid->import("ByteArray");
  v_String= _libid->import("String");
  v_ImmutableString= _libid->import("ImmutableString");
  v_nil= _libid->import("nil");
  v_LookupKey= _libid->import("LookupKey");
  v_Set= _libid->import("Set");
  v_Dictionary= _libid->import("Dictionary");
  v_IdentityDictionary= _libid->import("IdentityDictionary");
  v_Stream= _libid->import("Stream");
  v_PositionableStream= _libid->import("PositionableStream");
  l_2= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_Object, s_slotNameAt_, (_imp_t)Object__slotNameAt_);
  _libid->method(v_Object, s__5fslotNameAt_5f_, (_imp_t)Object___5fslotNameAt_5f_);
  l_5= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_Object, s_slotOffsetAt_, (_imp_t)Object__slotOffsetAt_);
  _libid->method(v_Object, s__5fslotOffsetAt_5f_, (_imp_t)Object___5fslotOffsetAt_5f_);
  l_8= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_Object, s_slotSizeAt_, (_imp_t)Object__slotSizeAt_);
  _libid->method(v_Object, s__5fslotSizeAt_5f_, (_imp_t)Object___5fslotSizeAt_5f_);
  l_11= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_Object, s_slots, (_imp_t)Object__slots);
  l_12= _sendv(s_function_5f_arity_5f_, 3, v_StaticBlockClosure, b_12, 0);
 {
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 2);
  oop _1= 0;
  _1= l_12;
  _line(67);
  _1=_sendv(s_slots, 1, _1);
  _line(67);
  _1=_sendv(s_printString, 1, _1);
  _line(67);
  _1=_sendv(s_putln, 1, _1);
  /* Scope() */
  /* Scope('x'->TemporaryVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _1= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_13, 0, 0, ((oop *)_state1), 0);
  _line(68);
  _1=_sendv(s_slots, 1, _1);
  _line(68);
  _1=_sendv(s_printString, 1, _1);
  _line(68);
  _1=_sendv(s_putln, 1, _1);
 }
  _leave();
}

int main(int argc, char *argv[])
{
#if defined(WIN32)
  void *init= GetProcAddress(GetModuleHandle(0), "_libid_init");
#else
  void *init= dlsym(RTLD_DEFAULT, "_libid_init");
#endif
  struct __libid *libid;
  char **envp= { 0 };
  if (!init) { fprintf(stderr, "id runtime not found\n");  abort(); }
  libid= ((struct __libid *(*)(int *, char ***, char ***))init)(&argc, &argv, &envp);
  __id__init__(libid);
  return 0;
}

#if defined(EMBEDDED)
extern void _start(void);
void *StartTVector[2]= { (void *)_start, 0 };
#endif
