/* generated by Id 1.1 at шк */
/* with the command: -I../../stage2/ -I../../st80 -g -m main.st -o main.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s_at_= 0;
static oop s_new= 0;
static oop s_new_5f_= 0;
static oop s_garbageCollect= 0;
static oop s_nextPutAll_= 0;
static oop s__5fdebugName= 0;
static oop s_size_5f_value_5f_= 0;
static oop s_value_5f_= 0;
static oop s__5fimport_= 0;
static oop s_print_= 0;
static oop s_function_5f_arity_5f_outer_state_nlr_5f_= 0;
static oop s_printString= 0;
static oop s_new_= 0;
static oop s_printOn_= 0;
static oop s__5fslots= 0;
static oop s_value_= 0;
static oop s_to_do_= 0;
static oop s_putln= 0;
static oop s__5fsizeof= 0;
static oop s_nextPut_= 0;
static oop s_at_put_= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "at:", &s_at_ },
  { "new", &s_new },
  { "new_:", &s_new_5f_ },
  { "garbageCollect", &s_garbageCollect },
  { "nextPutAll:", &s_nextPutAll_ },
  { "_debugName", &s__5fdebugName },
  { "size_:value_:", &s_size_5f_value_5f_ },
  { "value_:", &s_value_5f_ },
  { "_import:", &s__5fimport_ },
  { "print:", &s_print_ },
  { "function_:arity_:outer:state:nlr_:", &s_function_5f_arity_5f_outer_state_nlr_5f_ },
  { "printString", &s_printString },
  { "new:", &s_new_ },
  { "printOn:", &s_printOn_ },
  { "_slots", &s__5fslots },
  { "value:", &s_value_ },
  { "to:do:", &s_to_do_ },
  { "putln", &s_putln },
  { "_sizeof", &s__5fsizeof },
  { "nextPut:", &s_nextPut_ },
  { "at:put:", &s_at_put_ },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Character {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Fraction {
  struct _vtable *_vtable[0];
  oop v_numerator;
  oop v_denominator;
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargePositiveInteger {
  struct _vtable *_vtable[0];
  oop v_bytes;
};
struct t_LargeNegativeInteger {
  struct _vtable *_vtable[0];
  oop v_bytes;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_ImmutableArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_WordArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__words;
};
struct t_ImmutableWordArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__words;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_ImmutableByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_ImmutableString {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
struct t_CharacterTable {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_LookupKey {
  struct _vtable *_vtable[0];
  oop v_key;
};
struct t_Association {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t_AVLTreeNode {
  struct _vtable *_vtable[0];
  oop v_left;
  oop v_right;
  oop v_height;
  oop v_value;
};
struct t_AVLTree {
  struct _vtable *_vtable[0];
  oop v_rootNode;
  oop v_orderBlock;
};
struct t_Set {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
};
struct t_OrderedCollection {
  struct _vtable *_vtable[0];
  oop v_array;
  oop v_firstIndex;
  oop v_lastIndex;
};
struct t_Dictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
};
struct t_IdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
};
struct t_IdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
};
struct t_Stream {
  struct _vtable *_vtable[0];
};
struct t_PositionableStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_ReadStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_GetOpt {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
  oop v_defaultBlock;
};
struct t_Smalltalk {
  struct _vtable *_vtable[0];
  oop v_argumentCount;
  oop v_argumentVector;
};
struct t_SymbolTable {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
};
struct t_WriteStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_writeLimit;
};
struct t_SelectorTable {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
};
struct t_PerformWithArgumentsSelectors {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_WeakArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_Foo {
  struct _vtable *_vtable[0];
  oop v_value;
};
static oop l_4= 0;
static oop l_5= 0;
static oop l_6= 0;
static oop l_7= 0;
static oop v__object= 0;
static oop v__vector= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_StaticBlockClosure= 0;
static oop v_BlockClosure= 0;
static oop v_Magnitude= 0;
static oop v_Character= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_SmallInteger= 0;
static oop v_LargePositiveInteger= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_Array= 0;
static oop v_WordArray= 0;
static oop v_ByteArray= 0;
static oop v_String= 0;
static oop v_ImmutableString= 0;
static oop v_LookupKey= 0;
static oop v_Set= 0;
static oop v_Dictionary= 0;
static oop v_IdentityDictionary= 0;
static oop v_Stream= 0;
static oop v_PositionableStream= 0;
static oop v_Smalltalk= 0;
static oop v_WeakArray= 0;
static oop v_Foo= 0;
static struct __methodinfo __info1= { "garbageCollect", "Smalltalk", "/Users/chazu/dev/c/idst-with-history/object/examples/weak/main.st", 0, 5, 11, 0 };
static oop Smalltalk__garbageCollect(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info1);
  oop _1= 0;
  _line(5);
 {
# define self ((struct t_Smalltalk *)v_self)

    GC_gcollect();

# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static size_t Foo___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_Foo); }
static char *Foo___5fdebugName(oop _closure, oop v_self) { return "Foo"; }
static struct __slotinfo *Foo___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "value", 0, 4 }, { 0, 0, 0 } };  return &info[0]; }
static struct __methodinfo __info2= { "value:", "Foo", "/Users/chazu/dev/c/idst-with-history/object/examples/weak/main.st", 0, 13, 19, &__info1 };
static oop Foo__value_(oop v__closure, oop v_stateful_self, oop v_self, oop v_v)
 {
  _enter(&__info2);
  oop _1= 0;
  _line(13);
  _1= v_self;
  _line(15);
  _1=_sendv(s_new, 1, _1);
  v_self= _1;
  v_stateful_self= _1;
  _1= v_v;
  ((struct t_Foo *)v_stateful_self)->v_value= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info3= { "printOn:", "Foo", "/Users/chazu/dev/c/idst-with-history/object/examples/weak/main.st", 0, 19, 25, &__info2 };
static oop Foo__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info3);
  oop _1= 0;
  oop _2= 0;
  _line(19);
  _1= v_aStream;
  _2= l_4;
  _line(21);
  _sendv(s_nextPutAll_, 2, _1, _2);
  _2= ((struct t_Foo *)v_stateful_self)->v_value;
  _sendv(s_print_, 2, _1, _2);
  _2= l_5;
  _1=_sendv(s_nextPut_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info8= { "[] ?", "?", "/Users/chazu/dev/c/idst-with-history/object/examples/weak/main.st", 0, 0, 0, &__info3 };
static oop b_8(oop v__closure, oop v__self, oop v_i)
 {
  _enter(&__info8);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  _line(29);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* weak */
  _2= v_i;
  _3= v_Foo;
  _4= v_i;
  _line(29);
  _3=_sendv(s_value_, 2, _3, _4);
  _line(29);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info9= { "[] ?", "?", "/Users/chazu/dev/c/idst-with-history/object/examples/weak/main.st", 0, 0, 0, &__info8 };
static oop b_9(oop v__closure, oop v__self, oop v_i)
 {
  _enter(&__info9);
  oop _1= 0;
  oop _2= 0;
  _line(30);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* weak */
  _2= v_i;
  _line(30);
  _1=_sendv(s_at_, 2, _1, _2);
  _line(30);
  _1=_sendv(s_printString, 1, _1);
  _line(30);
  _1=_sendv(s_putln, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info10= { "[] ?", "?", "/Users/chazu/dev/c/idst-with-history/object/examples/weak/main.st", 0, 0, 0, &__info9 };
static oop b_10(oop v__closure, oop v__self, oop v_i)
 {
  _enter(&__info10);
  oop _1= 0;
  oop _2= 0;
  _line(31);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* weak */
  _2= v_i;
  _line(31);
  _1=_sendv(s_at_, 2, _1, _2);
  _line(31);
  _1=_sendv(s_printString, 1, _1);
  _line(31);
  _1=_sendv(s_putln, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info11= { "[] ?", "?", "/Users/chazu/dev/c/idst-with-history/object/examples/weak/main.st", 0, 0, 0, &__info10 };
static oop b_11(oop v__closure, oop v__self, oop v_i)
 {
  _enter(&__info11);
  oop _1= 0;
  oop _2= 0;
  _line(32);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* weak */
  _2= v_i;
  _line(32);
  _1=_sendv(s_at_, 2, _1, _2);
  _line(32);
  _1=_sendv(s_printString, 1, _1);
  _line(32);
  _1=_sendv(s_putln, 1, _1);
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "main.st", 0, 0, 0, &__info11 };
void __id__init__(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info1);

  _sendv(s__5fimport_, 3, _libid->_object, "st80", "__id__init__st80");
  v__object= _libid->import("_object");
  v__vector= _libid->import("_vector");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_BlockClosure= _libid->import("BlockClosure");
  v_Magnitude= _libid->import("Magnitude");
  v_Character= _libid->import("Character");
  v_Number= _libid->import("Number");
  v_Integer= _libid->import("Integer");
  v_SmallInteger= _libid->import("SmallInteger");
  v_LargePositiveInteger= _libid->import("LargePositiveInteger");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_Array= _libid->import("Array");
  v_WordArray= _libid->import("WordArray");
  v_ByteArray= _libid->import("ByteArray");
  v_String= _libid->import("String");
  v_ImmutableString= _libid->import("ImmutableString");
  v_LookupKey= _libid->import("LookupKey");
  v_Set= _libid->import("Set");
  v_Dictionary= _libid->import("Dictionary");
  v_IdentityDictionary= _libid->import("IdentityDictionary");
  v_Stream= _libid->import("Stream");
  v_PositionableStream= _libid->import("PositionableStream");
  v_Smalltalk= _libid->import("Smalltalk");
  _sendv(s__5fimport_, 3, _libid->_object, "WeakArray", "__id__init__WeakArray");
  v_WeakArray= _libid->import("WeakArray");
  _libid->method(v_Smalltalk, s_garbageCollect, (_imp_t)Smalltalk__garbageCollect);
  v_Foo= _libid->proto2(v_Object, Foo___5fsizeof(0, 0));
  _libid->method(v_Foo, s__5fsizeof, (_imp_t)Foo___5fsizeof);
  _libid->method(v_Foo, s__5fdebugName, (_imp_t)Foo___5fdebugName);
  _libid->method(v_Foo, s__5fslots, (_imp_t)Foo___5fslots);
  _libid->export("Foo", v_Foo);
  _libid->method(v_Foo, s_value_, (_imp_t)Foo__value_);
  l_4= _sendv(s_size_5f_value_5f_, 3, v_ImmutableString, 4, "Foo(");
  l_5= _sendv(s_value_5f_, 2, v_Character, 41);
  _libid->method(v_Foo, s_printOn_, (_imp_t)Foo__printOn_);
  l_6= _sendv(s_value_5f_, 2, v_SmallInteger, 4);
  l_7= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
 {
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 2);
  oop v_size= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  (void)v_size;
  _1= l_6;
  v_size= _1;
  _1= v_WeakArray;
  _2= v_size;
  _line(28);
  _1=_sendv(s_new_, 2, _1, _2);
  ((oop *)_state1)[1]= _1;  /* weak */
  _1= l_7;
  _2= v_size;
  /* Scope('i'->ArgumentVariableNode) */
  /* Scope('weak'->TemporaryVariableNode 'size'->TemporaryVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_8, 1, 0, ((oop *)_state1), 0);
  _line(29);
  _1=_sendv(s_to_do_, 3, _1, _2, _3);
  _1= v_Smalltalk;
  _line(30);
  _1=_sendv(s_garbageCollect, 1, _1);
  _1= l_7;
  _2= v_size;
  /* Scope('i'->ArgumentVariableNode) */
  /* Scope('weak'->TemporaryVariableNode 'size'->TemporaryVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_9, 1, 0, ((oop *)_state1), 0);
  _line(30);
  _1=_sendv(s_to_do_, 3, _1, _2, _3);
  _1= v_Smalltalk;
  _line(31);
  _1=_sendv(s_garbageCollect, 1, _1);
  _1= l_7;
  _2= v_size;
  /* Scope('i'->ArgumentVariableNode) */
  /* Scope('weak'->TemporaryVariableNode 'size'->TemporaryVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_10, 1, 0, ((oop *)_state1), 0);
  _line(31);
  _1=_sendv(s_to_do_, 3, _1, _2, _3);
  _1= v_Smalltalk;
  _line(32);
  _1=_sendv(s_garbageCollect, 1, _1);
  _1= l_7;
  _2= v_size;
  /* Scope('i'->ArgumentVariableNode) */
  /* Scope('weak'->TemporaryVariableNode 'size'->TemporaryVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_11, 1, 0, ((oop *)_state1), 0);
  _line(32);
  _1=_sendv(s_to_do_, 3, _1, _2, _3);
 }
  _leave();
}

int main(int argc, char *argv[])
{
#if defined(WIN32)
  void *init= GetProcAddress(GetModuleHandle(0), "_libid_init");
#else
  void *init= dlsym(RTLD_DEFAULT, "_libid_init");
#endif
  struct __libid *libid;
  char **envp= { 0 };
  if (!init) { fprintf(stderr, "id runtime not found\n");  abort(); }
  libid= ((struct __libid *(*)(int *, char ***, char ***))init)(&argc, &argv, &envp);
  __id__init__(libid);
  return 0;
}

#if defined(EMBEDDED)
extern void _start(void);
void *StartTVector[2]= { (void *)_start, 0 };
#endif
