/* generated by Id 1.1 at ËZE */
/* with the command: -I../../object/stage2/ -I../objects -g -I../objects -c ParsingExpression-printing.st -o ParsingExpression-printing.o.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s_new_5f_= 0;
static oop s_size_5f_value_5f_= 0;
static oop s_nextPutAll_= 0;
static oop s_isUnresolved= 0;
static oop s_value_5f_= 0;
static oop s_do_separatedBy_= 0;
static oop s__5fimport_= 0;
static oop s_print_= 0;
static oop s_function_5f_arity_5f_outer_state_nlr_5f_= 0;
static oop s_space= 0;
static oop s_delimiter= 0;
static oop s_printOn_= 0;
static oop s_ifTrue_= 0;
static oop s_nextPut_= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "new_:", &s_new_5f_ },
  { "size_:value_:", &s_size_5f_value_5f_ },
  { "nextPutAll:", &s_nextPutAll_ },
  { "isUnresolved", &s_isUnresolved },
  { "value_:", &s_value_5f_ },
  { "do:separatedBy:", &s_do_separatedBy_ },
  { "_import:", &s__5fimport_ },
  { "print:", &s_print_ },
  { "function_:arity_:outer:state:nlr_:", &s_function_5f_arity_5f_outer_state_nlr_5f_ },
  { "space", &s_space },
  { "delimiter", &s_delimiter },
  { "printOn:", &s_printOn_ },
  { "ifTrue:", &s_ifTrue_ },
  { "nextPut:", &s_nextPut_ },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Date {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__microseconds;
};
struct t_Time {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__nanoseconds;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargeInteger {
  struct _vtable *_vtable[0];
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t_Association {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t_Link {
  struct _vtable *_vtable[0];
  oop v_prevLink;
  oop v_nextLink;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_LinkedList {
  struct _vtable *_vtable[0];
  oop v_firstLink;
  oop v_lastLink;
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__oops;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_OrderedCollection {
  struct _vtable *_vtable[0];
  oop v_firstIndex;
  oop v_lastIndex;
  oop v_array;
};
struct t_IdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Set {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_IdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Dictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_FastIdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_SlotDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_MemoDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_ProfiledMethod {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_count;
  oop v_next;
};
struct t_SinkStream {
  struct _vtable *_vtable[0];
};
struct t_ReadStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_WriteStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_writeLimit;
};
struct t_FileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
};
struct t_ConsoleFileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
  oop v__prompt;
};
struct t_File {
  struct _vtable *_vtable[0];
  oop v__fd;
  oop v_name;
};
struct t_Function {
  struct _vtable *_vtable[0];
};
struct t_Random {
  struct _vtable *_vtable[0];
  oop v_seed;
  oop v_a;
  oop v_m;
  oop v_q;
  oop v_r;
};
struct t_OS {
  struct _vtable *_vtable[0];
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
struct t_CharacterClass {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_FastIdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_SharedFile {
  struct _vtable *_vtable[0];
  oop v__fd;
  oop v_name;
  oop v_readStream;
};
struct t_Expression {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__oops;
  oop v_type;
};
struct t_Type {
  struct _vtable *_vtable[0];
};
struct t_VoidType {
  struct _vtable *_vtable[0];
};
struct t_NumericType {
  struct _vtable *_vtable[0];
};
struct t_IntegralType {
  struct _vtable *_vtable[0];
};
struct t_I1 {
  struct _vtable *_vtable[0];
};
struct t_U1 {
  struct _vtable *_vtable[0];
};
struct t_I2 {
  struct _vtable *_vtable[0];
};
struct t_U2 {
  struct _vtable *_vtable[0];
};
struct t_I4 {
  struct _vtable *_vtable[0];
};
struct t_U4 {
  struct _vtable *_vtable[0];
};
struct t_I8 {
  struct _vtable *_vtable[0];
};
struct t_U8 {
  struct _vtable *_vtable[0];
};
struct t_FloatingType {
  struct _vtable *_vtable[0];
};
struct t_F4 {
  struct _vtable *_vtable[0];
};
struct t_F8 {
  struct _vtable *_vtable[0];
};
struct t_PointerType {
  struct _vtable *_vtable[0];
  oop v_referentType;
};
struct t_P4 {
  struct _vtable *_vtable[0];
  oop v_referentType;
};
struct t_P8 {
  struct _vtable *_vtable[0];
  oop v_referentType;
};
struct t_StructureType {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v_alignment;
  oop v_members;
};
struct t_MemberType {
  struct _vtable *_vtable[0];
  oop v_offset;
  oop v_type;
};
struct t_ParsingExpression {
  struct _vtable *_vtable[0];
};
struct t_PeAny {
  struct _vtable *_vtable[0];
};
struct t_PeRest {
  struct _vtable *_vtable[0];
};
struct t_ParsingExpressionValue {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeIdentity {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeEquality {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeClass {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeSequence {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_ParsingExpressionSingle {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeNot {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeStructure {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_ParsingExpressionRepeat {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeZeroOne {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeZeroMore {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeOneMore {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeName {
  struct _vtable *_vtable[0];
  oop v_value;
  oop v_name;
  oop v_grammar;
};
struct t_PeRule {
  struct _vtable *_vtable[0];
  oop v_value;
  oop v_name;
  oop v_preAction;
  oop v_postAction;
  oop v_save;
};
struct t_ParsingExpressionMultiple {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeAnd {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeOr {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeUnresolved {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeTextResult {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeTextValue {
  struct _vtable *_vtable[0];
  oop v_value;
  oop v_limit;
};
struct t_PeTextValueAction {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeItemResult {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeAction {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeSave {
  struct _vtable *_vtable[0];
  oop v_value;
  oop v_size;
};
struct t_PePush {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PePop {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeStoreResult {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeSetResult {
  struct _vtable *_vtable[0];
  oop v_value;
  oop v_expression;
};
struct t_PeCollectResult {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeCollectResults {
  struct _vtable *_vtable[0];
  oop v_value;
  oop v_index;
};
static oop l_2= 0;
static oop l_4= 0;
static oop l_6= 0;
static oop l_8= 0;
static oop l_10= 0;
static oop l_12= 0;
static oop l_13= 0;
static oop l_15= 0;
static oop l_17= 0;
static oop l_19= 0;
static oop l_21= 0;
static oop l_25= 0;
static oop l_27= 0;
static oop l_29= 0;
static oop l_32= 0;
static oop l_34= 0;
static oop l_36= 0;
static oop l_38= 0;
static oop l_40= 0;
static oop l_41= 0;
static oop l_43= 0;
static oop l_45= 0;
static oop l_47= 0;
static oop l_49= 0;
static oop l_51= 0;
static oop l_53= 0;
static oop l_55= 0;
static oop l_57= 0;
static oop l_58= 0;
static oop v__object= 0;
static oop v__vector= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_Magnitude= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_SmallInteger= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_Array= 0;
static oop v_ByteArray= 0;
static oop v_String= 0;
static oop v_IdentitySet= 0;
static oop v_IdentityDictionary= 0;
static oop v_SlotDictionary= 0;
static oop v_StaticBlockClosure= 0;
static oop v_BlockClosure= 0;
static oop v_ReadStream= 0;
static oop v_FileStream= 0;
static oop v_File= 0;
static oop v_nil= 0;
static oop v_Type= 0;
static oop v_NumericType= 0;
static oop v_IntegralType= 0;
static oop v_I1= 0;
static oop v_I2= 0;
static oop v_I4= 0;
static oop v_I8= 0;
static oop v_FloatingType= 0;
static oop v_PointerType= 0;
static oop v_ParsingExpression= 0;
static oop v_PeAny= 0;
static oop v_ParsingExpressionValue= 0;
static oop v_PeIdentity= 0;
static oop v_PeEquality= 0;
static oop v_PeClass= 0;
static oop v_PeSequence= 0;
static oop v_ParsingExpressionSingle= 0;
static oop v_PeNot= 0;
static oop v_PeStructure= 0;
static oop v_ParsingExpressionRepeat= 0;
static oop v_PeZeroOne= 0;
static oop v_PeZeroMore= 0;
static oop v_PeOneMore= 0;
static oop v_PeName= 0;
static oop v_PeRule= 0;
static oop v_ParsingExpressionMultiple= 0;
static oop v_PeAnd= 0;
static oop v_PeOr= 0;
static oop v_PeUnresolved= 0;
static oop v_PeTextResult= 0;
static oop v_PeItemResult= 0;
static oop v_PeAction= 0;
static oop v_PeSave= 0;
static oop v_PePush= 0;
static oop v_PePop= 0;
static oop v_PeStoreResult= 0;
static oop v_PeSetResult= 0;
static oop v_PeCollectResult= 0;
static oop v_PeCollectResults= 0;
static struct __methodinfo __info1= { "printOn:", "PeAny", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 3, 5, 0 };
static oop PeAny__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info1);
  oop _1= 0;
  oop _2= 0;
  _line(3);
  _1= v_aStream;
  _2= l_2;
  _line(3);
  _1=_sendv(s_nextPutAll_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info3= { "printOn:", "PeIdentity", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 5, 6, &__info1 };
static oop PeIdentity__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info3);
  oop _1= 0;
  oop _2= 0;
  _line(5);
  _1= v_aStream;
  _2= l_4;
  _line(5);
  _sendv(s_nextPutAll_, 2, _1, _2);
  _2= ((struct t_PeIdentity *)v_stateful_self)->v_value;
  _1=_sendv(s_print_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info5= { "printOn:", "PeEquality", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 6, 7, &__info3 };
static oop PeEquality__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info5);
  oop _1= 0;
  oop _2= 0;
  _line(6);
  _1= v_aStream;
  _2= l_6;
  _line(6);
  _sendv(s_nextPutAll_, 2, _1, _2);
  _2= ((struct t_PeEquality *)v_stateful_self)->v_value;
  _1=_sendv(s_print_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info7= { "printOn:", "PeClass", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 7, 8, &__info5 };
static oop PeClass__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info7);
  oop _1= 0;
  oop _2= 0;
  _line(7);
  _1= v_aStream;
  _2= l_8;
  _line(7);
  _sendv(s_nextPutAll_, 2, _1, _2);
  _2= ((struct t_PeClass *)v_stateful_self)->v_value;
  _1=_sendv(s_print_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info9= { "printOn:", "PeSequence", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 8, 9, &__info7 };
static oop PeSequence__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info9);
  oop _1= 0;
  oop _2= 0;
  _line(8);
  _1= v_aStream;
  _2= l_10;
  _line(8);
  _sendv(s_nextPutAll_, 2, _1, _2);
  _2= ((struct t_PeSequence *)v_stateful_self)->v_value;
  _1=_sendv(s_print_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info11= { "printOn:", "PeStructure", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 9, 11, &__info9 };
static oop PeStructure__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info11);
  oop _1= 0;
  oop _2= 0;
  _line(9);
  _1= v_aStream;
  _2= l_12;
  _line(9);
  _sendv(s_nextPutAll_, 2, _1, _2);
  _2= ((struct t_PeStructure *)v_stateful_self)->v_value;
  _sendv(s_print_, 2, _1, _2);
  _2= l_13;
  _1=_sendv(s_nextPut_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info14= { "printOn:", "PeNot", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 11, 13, &__info11 };
static oop PeNot__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info14);
  oop _1= 0;
  oop _2= 0;
  _line(11);
  _1= v_aStream;
  _2= l_15;
  _line(11);
  _sendv(s_nextPutAll_, 2, _1, _2);
  _2= ((struct t_PeNot *)v_stateful_self)->v_value;
  _1=_sendv(s_print_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info16= { "printOn:", "PeZeroOne", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 13, 14, &__info14 };
static oop PeZeroOne__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info16);
  oop _1= 0;
  oop _2= 0;
  _line(13);
  _1= v_aStream;
  _2= ((struct t_PeZeroOne *)v_stateful_self)->v_value;
  _line(13);
  _sendv(s_print_, 2, _1, _2);
  _2= l_17;
  _1=_sendv(s_nextPut_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info18= { "printOn:", "PeZeroMore", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 14, 15, &__info16 };
static oop PeZeroMore__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info18);
  oop _1= 0;
  oop _2= 0;
  _line(14);
  _1= v_aStream;
  _2= ((struct t_PeZeroMore *)v_stateful_self)->v_value;
  _line(14);
  _sendv(s_print_, 2, _1, _2);
  _2= l_19;
  _1=_sendv(s_nextPut_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info20= { "printOn:", "PeOneMore", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 15, 17, &__info18 };
static oop PeOneMore__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info20);
  oop _1= 0;
  oop _2= 0;
  _line(15);
  _1= v_aStream;
  _2= ((struct t_PeOneMore *)v_stateful_self)->v_value;
  _line(15);
  _sendv(s_print_, 2, _1, _2);
  _2= l_21;
  _1=_sendv(s_nextPut_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info22= { "isUnresolved", "ParsingExpression", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 17, 18, &__info20 };
static oop ParsingExpression__isUnresolved(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info22);
  oop _1= 0;
  _line(17);
  _1= v_nil;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info23= { "isUnresolved", "PeUnresolved", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 18, 20, &__info22 };
static oop PeUnresolved__isUnresolved(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info23);
  oop _1= 0;
  _line(18);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info24= { "printOn:", "PeName", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 20, 26, &__info23 };
static oop PeName__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info24);
  oop _1= 0;
  oop _2= 0;
  _line(20);
  _1= v_aStream;
  _2= ((struct t_PeName *)v_stateful_self)->v_name;
  _line(22);
  _1=_sendv(s_print_, 2, _1, _2);
  /* ifTrue: */
  _1= 0;
  _2= ((struct t_PeName *)v_stateful_self)->v_value;
  _line(23);
  _2=_sendv(s_isUnresolved, 1, _2);
  if (!_2) goto _l1;
 {
  _1= v_aStream;
  _2= l_25;
  _line(23);
  _1=_sendv(s_nextPutAll_, 2, _1, _2);
 }
 _l1:;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info26= { "printOn:", "PeRule", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 26, 28, &__info24 };
static oop PeRule__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info26);
  oop _1= 0;
  oop _2= 0;
  _line(26);
  _1= v_aStream;
  _2= ((struct t_PeRule *)v_stateful_self)->v_name;
  _line(26);
  _sendv(s_print_, 2, _1, _2);
  _2= l_27;
  _sendv(s_nextPutAll_, 2, _1, _2);
  _2= ((struct t_PeRule *)v_stateful_self)->v_value;
  _1=_sendv(s_print_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info30= { "[] printOn:", "ParsingExpressionMultiple", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 28, 35, &__info26 };
static oop b_30(oop v__closure, oop v__self, oop v_pe)
 {
  _enter(&__info30);
  oop _1= 0;
  oop _2= 0;
  _line(31);
  _1= v_pe;
  _2= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* aStream */
  _line(31);
  _1=_sendv(s_printOn_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info31= { "[] printOn:", "ParsingExpressionMultiple", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 28, 35, &__info30 };
static oop b_31(oop v__closure, oop v__self)
 {
  _enter(&__info31);
  oop _1= 0;
  oop _2= 0;
  _line(31);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* aStream */
  _2= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[2];  /* self */
  _line(31);
  _2=_sendv(s_delimiter, 1, _2);
  _line(31);
  _1=_sendv(s_nextPutAll_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info28= { "printOn:", "ParsingExpressionMultiple", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 28, 35, &__info31 };
static oop ParsingExpressionMultiple__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info28);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 5);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  ((oop *)_state1)[3]= v_stateful_self;
  ((oop *)_state1)[2]= v_self;
  ((oop *)_state1)[1]= v_aStream;
  _line(28);
  _1= ((oop *)_state1)[1];  /* aStream */
  _2= l_29;
  _line(30);
  _1=_sendv(s_nextPut_, 2, _1, _2);
  _1= ((struct t_ParsingExpressionMultiple *)((oop *)_state1)[3])->v_value;  /* value */
  /* Scope('pe'->ArgumentVariableNode) */
  /* Scope('self'->ArgumentVariableNode 'value'->SlotVariableNode 'stateful_self'->ArgumentVariableNode 'aStream'->ArgumentVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _2= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_30, 1, 0, ((oop *)_state1), 0);
  /* Scope() */
  /* Scope('self'->ArgumentVariableNode 'value'->SlotVariableNode 'stateful_self'->ArgumentVariableNode 'aStream'->ArgumentVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_31, 0, 0, ((oop *)_state1), 0);
  _line(31);
  _1=_sendv(s_do_separatedBy_, 3, _1, _2, _3);
  _1= ((oop *)_state1)[1];  /* aStream */
  _2= l_32;
  _line(32);
  _1=_sendv(s_nextPut_, 2, _1, _2);
  _1= ((oop *)_state1)[2];  /* self */
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info33= { "delimiter", "PeAnd", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 35, 36, &__info28 };
static oop PeAnd__delimiter(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info33);
  oop _1= 0;
  _line(35);
  _1= l_34;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info35= { "delimiter", "PeOr", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 36, 38, &__info33 };
static oop PeOr__delimiter(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info35);
  oop _1= 0;
  _line(36);
  _1= l_36;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info37= { "printOn:", "PeTextResult", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 38, 44, &__info35 };
static oop PeTextResult__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info37);
  oop _1= 0;
  oop _2= 0;
  _line(38);
  _1= ((struct t_PeTextResult *)v_stateful_self)->v_value;
  _2= v_aStream;
  _line(40);
  _1=_sendv(s_printOn_, 2, _1, _2);
  _1= v_aStream;
  _2= l_38;
  _line(41);
  _1=_sendv(s_nextPut_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info39= { "printOn:", "PeAction", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 44, 45, &__info37 };
static oop PeAction__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info39);
  oop _1= 0;
  oop _2= 0;
  _line(44);
  _1= v_aStream;
  _2= l_40;
  _line(44);
  _sendv(s_nextPutAll_, 2, _1, _2);
  _2= ((struct t_PeAction *)v_stateful_self)->v_value;
  _sendv(s_print_, 2, _1, _2);
  _2= l_41;
  _1=_sendv(s_nextPutAll_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info42= { "printOn:", "PeStoreResult", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 45, 46, &__info39 };
static oop PeStoreResult__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info42);
  oop _1= 0;
  oop _2= 0;
  _line(45);
  _1= v_aStream;
  _2= l_43;
  _line(45);
  _sendv(s_nextPutAll_, 2, _1, _2);
  _2= ((struct t_PeStoreResult *)v_stateful_self)->v_value;
  _1=_sendv(s_print_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info44= { "printOn:", "PeSetResult", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 46, 48, &__info42 };
static oop PeSetResult__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info44);
  oop _1= 0;
  oop _2= 0;
  _line(46);
  _1= v_aStream;
  _2= l_45;
  _line(46);
  _1=_sendv(s_nextPutAll_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info46= { "printOn:", "PeSave", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 48, 49, &__info44 };
static oop PeSave__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info46);
  oop _1= 0;
  oop _2= 0;
  _line(48);
  _1= v_aStream;
  _2= l_47;
  _line(48);
  _sendv(s_nextPutAll_, 2, _1, _2);
  _2= ((struct t_PeSave *)v_stateful_self)->v_size;
  _sendv(s_print_, 2, _1, _2);
  _sendv(s_space, 1, _1);
  _2= ((struct t_PeSave *)v_stateful_self)->v_value;
  _1=_sendv(s_print_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info48= { "printOn:", "PePush", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 49, 50, &__info46 };
static oop PePush__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info48);
  oop _1= 0;
  oop _2= 0;
  _line(49);
  _1= v_aStream;
  _2= l_49;
  _line(49);
  _sendv(s_nextPutAll_, 2, _1, _2);
  _2= ((struct t_PePush *)v_stateful_self)->v_value;
  _1=_sendv(s_print_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info50= { "printOn:", "PePop", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 50, 52, &__info48 };
static oop PePop__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info50);
  oop _1= 0;
  oop _2= 0;
  _line(50);
  _1= v_aStream;
  _2= l_51;
  _line(50);
  _sendv(s_nextPutAll_, 2, _1, _2);
  _2= ((struct t_PePop *)v_stateful_self)->v_value;
  _1=_sendv(s_print_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info52= { "printOn:", "PeItemResult", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 52, 59, &__info50 };
static oop PeItemResult__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info52);
  oop _1= 0;
  oop _2= 0;
  _line(52);
  _1= ((struct t_PeItemResult *)v_stateful_self)->v_value;
  _2= v_aStream;
  _line(54);
  _1=_sendv(s_printOn_, 2, _1, _2);
  _1= v_aStream;
  _2= l_53;
  _line(55);
  _1=_sendv(s_nextPutAll_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info54= { "printOn:", "PeCollectResult", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 59, 65, &__info52 };
static oop PeCollectResult__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info54);
  oop _1= 0;
  oop _2= 0;
  _line(59);
  _1= v_aStream;
  _2= l_55;
  _line(61);
  _1=_sendv(s_nextPut_, 2, _1, _2);
  _1= v_self;
  _2= v_aStream;
  _line(62);
  _1=_superv(v_PeStoreResult, s_printOn_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info56= { "printOn:", "PeCollectResults", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-printing.st", 0, 65, 70, &__info54 };
static oop PeCollectResults__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info56);
  oop _1= 0;
  oop _2= 0;
  _line(65);
  _1= v_aStream;
  _2= l_57;
  _line(67);
  _sendv(s_nextPut_, 2, _1, _2);
  _2= ((struct t_PeCollectResults *)v_stateful_self)->v_index;
  _sendv(s_print_, 2, _1, _2);
  _2= l_58;
  _1=_sendv(s_nextPut_, 2, _1, _2);
  _1= ((struct t_PeCollectResults *)v_stateful_self)->v_value;
  _2= v_aStream;
  _line(68);
  _1=_sendv(s_printOn_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "ParsingExpression-printing.st", 0, 0, 0, &__info56 };
void __id__init__ParsingExpression_2dprinting(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
# define GC_add_roots _libid->gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info1);

  _sendv(s__5fimport_, 3, _libid->_object, "ParsingExpression", "__id__init__ParsingExpression");
  v__object= _libid->import("_object");
  v__vector= _libid->import("_vector");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_Magnitude= _libid->import("Magnitude");
  v_Number= _libid->import("Number");
  v_Integer= _libid->import("Integer");
  v_SmallInteger= _libid->import("SmallInteger");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_Array= _libid->import("Array");
  v_ByteArray= _libid->import("ByteArray");
  v_String= _libid->import("String");
  v_IdentitySet= _libid->import("IdentitySet");
  v_IdentityDictionary= _libid->import("IdentityDictionary");
  v_SlotDictionary= _libid->import("SlotDictionary");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_BlockClosure= _libid->import("BlockClosure");
  v_ReadStream= _libid->import("ReadStream");
  v_FileStream= _libid->import("FileStream");
  v_File= _libid->import("File");
  v_nil= _libid->import("nil");
  v_Type= _libid->import("Type");
  v_NumericType= _libid->import("NumericType");
  v_IntegralType= _libid->import("IntegralType");
  v_I1= _libid->import("I1");
  v_I2= _libid->import("I2");
  v_I4= _libid->import("I4");
  v_I8= _libid->import("I8");
  v_FloatingType= _libid->import("FloatingType");
  v_PointerType= _libid->import("PointerType");
  v_ParsingExpression= _libid->import("ParsingExpression");
  v_PeAny= _libid->import("PeAny");
  v_ParsingExpressionValue= _libid->import("ParsingExpressionValue");
  v_PeIdentity= _libid->import("PeIdentity");
  v_PeEquality= _libid->import("PeEquality");
  v_PeClass= _libid->import("PeClass");
  v_PeSequence= _libid->import("PeSequence");
  v_ParsingExpressionSingle= _libid->import("ParsingExpressionSingle");
  v_PeNot= _libid->import("PeNot");
  v_PeStructure= _libid->import("PeStructure");
  v_ParsingExpressionRepeat= _libid->import("ParsingExpressionRepeat");
  v_PeZeroOne= _libid->import("PeZeroOne");
  v_PeZeroMore= _libid->import("PeZeroMore");
  v_PeOneMore= _libid->import("PeOneMore");
  v_PeName= _libid->import("PeName");
  v_PeRule= _libid->import("PeRule");
  v_ParsingExpressionMultiple= _libid->import("ParsingExpressionMultiple");
  v_PeAnd= _libid->import("PeAnd");
  v_PeOr= _libid->import("PeOr");
  v_PeUnresolved= _libid->import("PeUnresolved");
  v_PeTextResult= _libid->import("PeTextResult");
  v_PeItemResult= _libid->import("PeItemResult");
  v_PeAction= _libid->import("PeAction");
  v_PeSave= _libid->import("PeSave");
  v_PePush= _libid->import("PePush");
  v_PePop= _libid->import("PePop");
  v_PeStoreResult= _libid->import("PeStoreResult");
  v_PeSetResult= _libid->import("PeSetResult");
  v_PeCollectResult= _libid->import("PeCollectResult");
  v_PeCollectResults= _libid->import("PeCollectResults");
  l_2= _sendv(s_size_5f_value_5f_, 3, v_String, 1, ".");
  _libid->method(v_PeAny, s_printOn_, (_imp_t)PeAny__printOn_);
  l_4= _sendv(s_size_5f_value_5f_, 3, v_String, 2, "==");
  _libid->method(v_PeIdentity, s_printOn_, (_imp_t)PeIdentity__printOn_);
  l_6= _sendv(s_size_5f_value_5f_, 3, v_String, 1, "=");
  _libid->method(v_PeEquality, s_printOn_, (_imp_t)PeEquality__printOn_);
  l_8= _sendv(s_size_5f_value_5f_, 3, v_String, 1, "=");
  _libid->method(v_PeClass, s_printOn_, (_imp_t)PeClass__printOn_);
  l_10= _sendv(s_size_5f_value_5f_, 3, v_String, 2, "=*");
  _libid->method(v_PeSequence, s_printOn_, (_imp_t)PeSequence__printOn_);
  l_12= _sendv(s_size_5f_value_5f_, 3, v_String, 3, "=#(");
  l_13= _sendv(s_value_5f_, 2, v_SmallInteger, 41);
  _libid->method(v_PeStructure, s_printOn_, (_imp_t)PeStructure__printOn_);
  l_15= _sendv(s_size_5f_value_5f_, 3, v_String, 1, "!");
  _libid->method(v_PeNot, s_printOn_, (_imp_t)PeNot__printOn_);
  l_17= _sendv(s_value_5f_, 2, v_SmallInteger, 63);
  _libid->method(v_PeZeroOne, s_printOn_, (_imp_t)PeZeroOne__printOn_);
  l_19= _sendv(s_value_5f_, 2, v_SmallInteger, 42);
  _libid->method(v_PeZeroMore, s_printOn_, (_imp_t)PeZeroMore__printOn_);
  l_21= _sendv(s_value_5f_, 2, v_SmallInteger, 43);
  _libid->method(v_PeOneMore, s_printOn_, (_imp_t)PeOneMore__printOn_);
  _libid->method(v_ParsingExpression, s_isUnresolved, (_imp_t)ParsingExpression__isUnresolved);
  _libid->method(v_PeUnresolved, s_isUnresolved, (_imp_t)PeUnresolved__isUnresolved);
  l_25= _sendv(s_size_5f_value_5f_, 3, v_String, 3, "!!!");
  _libid->method(v_PeName, s_printOn_, (_imp_t)PeName__printOn_);
  l_27= _sendv(s_size_5f_value_5f_, 3, v_String, 3, " = ");
  _libid->method(v_PeRule, s_printOn_, (_imp_t)PeRule__printOn_);
  l_29= _sendv(s_value_5f_, 2, v_SmallInteger, 40);
  l_32= _sendv(s_value_5f_, 2, v_SmallInteger, 41);
  _libid->method(v_ParsingExpressionMultiple, s_printOn_, (_imp_t)ParsingExpressionMultiple__printOn_);
  l_34= _sendv(s_size_5f_value_5f_, 3, v_String, 1, " ");
  _libid->method(v_PeAnd, s_delimiter, (_imp_t)PeAnd__delimiter);
  l_36= _sendv(s_size_5f_value_5f_, 3, v_String, 3, " | ");
  _libid->method(v_PeOr, s_delimiter, (_imp_t)PeOr__delimiter);
  l_38= _sendv(s_value_5f_, 2, v_SmallInteger, 36);
  _libid->method(v_PeTextResult, s_printOn_, (_imp_t)PeTextResult__printOn_);
  l_40= _sendv(s_size_5f_value_5f_, 3, v_String, 1, "{");
  l_41= _sendv(s_size_5f_value_5f_, 3, v_String, 1, "}");
  _libid->method(v_PeAction, s_printOn_, (_imp_t)PeAction__printOn_);
  l_43= _sendv(s_size_5f_value_5f_, 3, v_String, 2, "->");
  _libid->method(v_PeStoreResult, s_printOn_, (_imp_t)PeStoreResult__printOn_);
  l_45= _sendv(s_size_5f_value_5f_, 3, v_String, 3, "<-#");
  _libid->method(v_PeSetResult, s_printOn_, (_imp_t)PeSetResult__printOn_);
  l_47= _sendv(s_size_5f_value_5f_, 3, v_String, 2, "@=");
  _libid->method(v_PeSave, s_printOn_, (_imp_t)PeSave__printOn_);
  l_49= _sendv(s_size_5f_value_5f_, 3, v_String, 2, "@+");
  _libid->method(v_PePush, s_printOn_, (_imp_t)PePush__printOn_);
  l_51= _sendv(s_size_5f_value_5f_, 3, v_String, 2, "@-");
  _libid->method(v_PePop, s_printOn_, (_imp_t)PePop__printOn_);
  l_53= _sendv(s_size_5f_value_5f_, 3, v_String, 7, " <item>");
  _libid->method(v_PeItemResult, s_printOn_, (_imp_t)PeItemResult__printOn_);
  l_55= _sendv(s_value_5f_, 2, v_SmallInteger, 43);
  _libid->method(v_PeCollectResult, s_printOn_, (_imp_t)PeCollectResult__printOn_);
  l_57= _sendv(s_value_5f_, 2, v_SmallInteger, 123);
  l_58= _sendv(s_value_5f_, 2, v_SmallInteger, 125);
  _libid->method(v_PeCollectResults, s_printOn_, (_imp_t)PeCollectResults__printOn_);
  _leave();
}
