/* generated by Id 1.1 at è */
/* with the command: -I../../object/stage2/ -I../objects -g -I../objects -c ParsingExpression-bootstrap.st -o ParsingExpression-bootstrap.o.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s_action= 0;
static oop s_value_5f_= 0;
static oop s_zeroOne= 0;
static oop s__5fimport_= 0;
static oop s__2d_3e= 0;
static oop s_withName_= 0;
static oop s_zeroMore= 0;
static oop s_add_= 0;
static oop s__7c= 0;
static oop s_parseClass= 0;
static oop s__3c_3d= 0;
static oop s_new= 0;
static oop s__2c= 0;
static oop s_asCharacterClass= 0;
static oop s_size_5f_value_5f_= 0;
static oop s_debugName= 0;
static oop s_ifTrue_ifFalse_= 0;
static oop s__3d_3d= 0;
static oop s_parseLiteral= 0;
static oop s_parseStructure= 0;
static oop s_storeResult= 0;
static oop s__3d_3e= 0;
static oop s_addLast_= 0;
static oop s_parse= 0;
static oop s_textResult= 0;
static oop s_oneMore= 0;
static oop s_setResult= 0;
static oop s_itemResult= 0;
static oop s_withValue_= 0;
static oop s__3c_2d= 0;
static oop s_withValue_index_= 0;
static oop s_error_= 0;
static oop s_first= 0;
static oop s_not= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "action", &s_action },
  { "value_:", &s_value_5f_ },
  { "zeroOne", &s_zeroOne },
  { "_import:", &s__5fimport_ },
  { "->", &s__2d_3e },
  { "withName:", &s_withName_ },
  { "zeroMore", &s_zeroMore },
  { "add:", &s_add_ },
  { "|", &s__7c },
  { "parseClass", &s_parseClass },
  { "<=", &s__3c_3d },
  { "new", &s_new },
  { ",", &s__2c },
  { "asCharacterClass", &s_asCharacterClass },
  { "size_:value_:", &s_size_5f_value_5f_ },
  { "debugName", &s_debugName },
  { "ifTrue:ifFalse:", &s_ifTrue_ifFalse_ },
  { "==", &s__3d_3d },
  { "parseLiteral", &s_parseLiteral },
  { "parseStructure", &s_parseStructure },
  { "storeResult", &s_storeResult },
  { "=>", &s__3d_3e },
  { "addLast:", &s_addLast_ },
  { "parse", &s_parse },
  { "textResult", &s_textResult },
  { "oneMore", &s_oneMore },
  { "setResult", &s_setResult },
  { "itemResult", &s_itemResult },
  { "withValue:", &s_withValue_ },
  { "<-", &s__3c_2d },
  { "withValue:index:", &s_withValue_index_ },
  { "error:", &s_error_ },
  { "first", &s_first },
  { "not", &s_not },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Date {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__microseconds;
};
struct t_Time {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__nanoseconds;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargeInteger {
  struct _vtable *_vtable[0];
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t_Association {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t_Link {
  struct _vtable *_vtable[0];
  oop v_prevLink;
  oop v_nextLink;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_LinkedList {
  struct _vtable *_vtable[0];
  oop v_firstLink;
  oop v_lastLink;
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__oops;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_OrderedCollection {
  struct _vtable *_vtable[0];
  oop v_firstIndex;
  oop v_lastIndex;
  oop v_array;
};
struct t_IdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Set {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_IdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Dictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_FastIdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_SlotDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_MemoDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_ProfiledMethod {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_count;
  oop v_next;
};
struct t_SinkStream {
  struct _vtable *_vtable[0];
};
struct t_ReadStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_WriteStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_writeLimit;
};
struct t_FileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
};
struct t_ConsoleFileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
  oop v__prompt;
};
struct t_File {
  struct _vtable *_vtable[0];
  oop v__fd;
  oop v_name;
};
struct t_Function {
  struct _vtable *_vtable[0];
};
struct t_Random {
  struct _vtable *_vtable[0];
  oop v_seed;
  oop v_a;
  oop v_m;
  oop v_q;
  oop v_r;
};
struct t_OS {
  struct _vtable *_vtable[0];
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
struct t_CharacterClass {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_FastIdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_SharedFile {
  struct _vtable *_vtable[0];
  oop v__fd;
  oop v_name;
  oop v_readStream;
};
struct t_Expression {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__oops;
  oop v_type;
};
struct t_Type {
  struct _vtable *_vtable[0];
};
struct t_VoidType {
  struct _vtable *_vtable[0];
};
struct t_NumericType {
  struct _vtable *_vtable[0];
};
struct t_IntegralType {
  struct _vtable *_vtable[0];
};
struct t_I1 {
  struct _vtable *_vtable[0];
};
struct t_U1 {
  struct _vtable *_vtable[0];
};
struct t_I2 {
  struct _vtable *_vtable[0];
};
struct t_U2 {
  struct _vtable *_vtable[0];
};
struct t_I4 {
  struct _vtable *_vtable[0];
};
struct t_U4 {
  struct _vtable *_vtable[0];
};
struct t_I8 {
  struct _vtable *_vtable[0];
};
struct t_U8 {
  struct _vtable *_vtable[0];
};
struct t_FloatingType {
  struct _vtable *_vtable[0];
};
struct t_F4 {
  struct _vtable *_vtable[0];
};
struct t_F8 {
  struct _vtable *_vtable[0];
};
struct t_PointerType {
  struct _vtable *_vtable[0];
  oop v_referentType;
};
struct t_P4 {
  struct _vtable *_vtable[0];
  oop v_referentType;
};
struct t_P8 {
  struct _vtable *_vtable[0];
  oop v_referentType;
};
struct t_StructureType {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v_alignment;
  oop v_members;
};
struct t_MemberType {
  struct _vtable *_vtable[0];
  oop v_offset;
  oop v_type;
};
struct t_ParsingExpression {
  struct _vtable *_vtable[0];
};
struct t_PeAny {
  struct _vtable *_vtable[0];
};
struct t_PeRest {
  struct _vtable *_vtable[0];
};
struct t_ParsingExpressionValue {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeIdentity {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeEquality {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeClass {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeSequence {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_ParsingExpressionSingle {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeNot {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeStructure {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_ParsingExpressionRepeat {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeZeroOne {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeZeroMore {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeOneMore {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeName {
  struct _vtable *_vtable[0];
  oop v_value;
  oop v_name;
  oop v_grammar;
};
struct t_PeRule {
  struct _vtable *_vtable[0];
  oop v_value;
  oop v_name;
  oop v_preAction;
  oop v_postAction;
  oop v_save;
};
struct t_ParsingExpressionMultiple {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeAnd {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeOr {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeUnresolved {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeTextResult {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeTextValue {
  struct _vtable *_vtable[0];
  oop v_value;
  oop v_limit;
};
struct t_PeTextValueAction {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeItemResult {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeAction {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeSave {
  struct _vtable *_vtable[0];
  oop v_value;
  oop v_size;
};
struct t_PePush {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PePop {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeStoreResult {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeSetResult {
  struct _vtable *_vtable[0];
  oop v_value;
  oop v_expression;
};
struct t_PeCollectResult {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_PeCollectResults {
  struct _vtable *_vtable[0];
  oop v_value;
  oop v_index;
};
static oop l_2= 0;
static oop l_5= 0;
static oop l_12= 0;
static oop l_15= 0;
static oop l_18= 0;
static oop l_31= 0;
static oop v__object= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_Magnitude= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_SmallInteger= 0;
static oop v_Symbol= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_Array= 0;
static oop v_ByteArray= 0;
static oop v_String= 0;
static oop v_IdentitySet= 0;
static oop v_IdentityDictionary= 0;
static oop v_SlotDictionary= 0;
static oop v_StaticBlockClosure= 0;
static oop v_BlockClosure= 0;
static oop v_ReadStream= 0;
static oop v_FileStream= 0;
static oop v_File= 0;
static oop v_true= 0;
static oop v_false= 0;
static oop v_Type= 0;
static oop v_NumericType= 0;
static oop v_IntegralType= 0;
static oop v_I1= 0;
static oop v_I2= 0;
static oop v_I4= 0;
static oop v_I8= 0;
static oop v_FloatingType= 0;
static oop v_PointerType= 0;
static oop v_ParsingExpression= 0;
static oop v_PeAny= 0;
static oop v_PeRest= 0;
static oop v_ParsingExpressionValue= 0;
static oop v_PeIdentity= 0;
static oop v_PeClass= 0;
static oop v_PeSequence= 0;
static oop v_ParsingExpressionSingle= 0;
static oop v_PeNot= 0;
static oop v_PeStructure= 0;
static oop v_ParsingExpressionRepeat= 0;
static oop v_PeZeroOne= 0;
static oop v_PeZeroMore= 0;
static oop v_PeOneMore= 0;
static oop v_PeName= 0;
static oop v_ParsingExpressionMultiple= 0;
static oop v_PeAnd= 0;
static oop v_PeOr= 0;
static oop v_PeTextResult= 0;
static oop v_PeTextValueAction= 0;
static oop v_PeItemResult= 0;
static oop v_PeAction= 0;
static oop v_PeStoreResult= 0;
static oop v_PeSetResult= 0;
static oop v_PeCollectResult= 0;
static oop v_PeCollectResults= 0;
static struct __methodinfo __info1= { "parse", "Object", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 3, 5, 0 };
static oop Object__parse(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info1);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(3);
  _1= v_self;
  _2= l_2;
  _3= v_self;
  _line(3);
  _3=_sendv(s_debugName, 1, _3);
  _line(3);
  _2=_sendv(s__2c, 2, _2, _3);
  _line(3);
  _1=_sendv(s_error_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info3= { "parse", "SmallInteger", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 5, 6, &__info1 };
static oop SmallInteger__parse(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info3);
  oop _1= 0;
  oop _2= 0;
  _line(5);
  _1= v_PeIdentity;
  _2= v_self;
  _line(5);
  _1=_sendv(s_withValue_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info4= { "parse", "String", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 6, 7, &__info3 };
static oop String__parse(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info4);
  oop _1= 0;
  oop _2= 0;
  _line(6);
  /* ifTrue:ifFalse: */
  _1= ((struct t_String *)v_stateful_self)->v_size;
  _2= l_5;
  _1= (_1 == _2) ? v_true : v_false;
  if (!_1) goto _l1;
 {
  _1= v_PeIdentity;
  _2= v_self;
  _line(6);
  _2=_sendv(s_first, 1, _2);
  _line(6);
  _1=_sendv(s_withValue_, 2, _1, _2);
 }
  goto _l2;
 _l1:;
 {
  _1= v_PeSequence;
  _2= v_self;
  _line(6);
  _1=_sendv(s_withValue_, 2, _1, _2);
 }
 _l2:;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info6= { "parseClass", "SequenceableCollection", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 7, 8, &__info4 };
static oop SequenceableCollection__parseClass(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info6);
  oop _1= 0;
  oop _2= 0;
  _line(7);
  _1= v_PeClass;
  _2= v_self;
  _line(7);
  _2=_sendv(s_asCharacterClass, 1, _2);
  _line(7);
  _1=_sendv(s_withValue_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info7= { "parse", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 8, 9, &__info6 };
static oop Symbol__parse(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info7);
  oop _1= 0;
  oop _2= 0;
  _line(8);
  _1= v_PeName;
  _2= v_self;
  _line(8);
  _1=_sendv(s_withName_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info8= { "parseLiteral", "Object", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 9, 11, &__info7 };
static oop Object__parseLiteral(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info8);
  oop _1= 0;
  oop _2= 0;
  _line(9);
  _1= v_PeIdentity;
  _2= v_self;
  _line(9);
  _1=_sendv(s_withValue_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info9= { "parseStructure", "ParsingExpression", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 11, 13, &__info8 };
static oop ParsingExpression__parseStructure(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info9);
  oop _1= 0;
  oop _2= 0;
  _line(11);
  _1= v_PeStructure;
  _2= v_self;
  _line(11);
  _1=_sendv(s_withValue_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info10= { "zeroOne", "ParsingExpression", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 13, 13, &__info9 };
static oop ParsingExpression__zeroOne(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info10);
  oop _1= 0;
  oop _2= 0;
  _line(13);
  _1= v_PeZeroOne;
  _2= v_self;
  _line(13);
  _1=_sendv(s_withValue_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info11= { "zeroOne", "ParsingExpressionRepeat", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 13, 14, &__info10 };
static oop ParsingExpressionRepeat__zeroOne(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info11);
  oop _1= 0;
  oop _2= 0;
  _line(13);
  _1= v_self;
  _2= l_12;
  _line(13);
  _1=_sendv(s_error_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info13= { "zeroMore", "ParsingExpression", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 14, 14, &__info11 };
static oop ParsingExpression__zeroMore(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info13);
  oop _1= 0;
  oop _2= 0;
  _line(14);
  _1= v_PeZeroMore;
  _2= v_self;
  _line(14);
  _1=_sendv(s_withValue_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info14= { "zeroMore", "ParsingExpressionRepeat", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 14, 15, &__info13 };
static oop ParsingExpressionRepeat__zeroMore(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info14);
  oop _1= 0;
  oop _2= 0;
  _line(14);
  _1= v_self;
  _2= l_15;
  _line(14);
  _1=_sendv(s_error_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info16= { "oneMore", "ParsingExpression", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 15, 15, &__info14 };
static oop ParsingExpression__oneMore(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info16);
  oop _1= 0;
  oop _2= 0;
  _line(15);
  _1= v_PeOneMore;
  _2= v_self;
  _line(15);
  _1=_sendv(s_withValue_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info17= { "oneMore", "ParsingExpressionRepeat", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 15, 17, &__info16 };
static oop ParsingExpressionRepeat__oneMore(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info17);
  oop _1= 0;
  oop _2= 0;
  _line(15);
  _1= v_self;
  _2= l_18;
  _line(15);
  _1=_sendv(s_error_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info19= { "zeroMore", "PeAny", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 17, 19, &__info17 };
static oop PeAny__zeroMore(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info19);
  oop _1= 0;
  _line(17);
  _1= v_PeRest;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info20= { "not", "ParsingExpression", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 19, 21, &__info19 };
static oop ParsingExpression__not(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info20);
  oop _1= 0;
  oop _2= 0;
  _line(19);
  _1= v_PeNot;
  _2= v_self;
  _line(19);
  _1=_sendv(s_withValue_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info21= { ",", "ParsingExpression", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 21, 22, &__info20 };
static oop ParsingExpression___2c(oop v__closure, oop v_stateful_self, oop v_self, oop v_pe)
 {
  _enter(&__info21);
  oop _1= 0;
  oop _2= 0;
  _line(21);
  _1= v_PeAnd;
  _line(21);
  _1=_sendv(s_new, 1, _1);
  _2= v_self;
  _line(21);
  _sendv(s_add_, 2, _1, _2);
  _2= v_pe;
  _1=_sendv(s_add_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info22= { ",", "PeAnd", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 22, 24, &__info21 };
static oop PeAnd___2c(oop v__closure, oop v_stateful_self, oop v_self, oop v_pe)
 {
  _enter(&__info22);
  oop _1= 0;
  oop _2= 0;
  _line(22);
  _1= ((struct t_PeAnd *)v_stateful_self)->v_value;
  _2= v_pe;
  _line(22);
  _1=_sendv(s_addLast_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info23= { "|", "ParsingExpression", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 24, 25, &__info22 };
static oop ParsingExpression___7c(oop v__closure, oop v_stateful_self, oop v_self, oop v_pe)
 {
  _enter(&__info23);
  oop _1= 0;
  oop _2= 0;
  _line(24);
  _1= v_PeOr;
  _line(24);
  _1=_sendv(s_new, 1, _1);
  _2= v_self;
  _line(24);
  _sendv(s_add_, 2, _1, _2);
  _2= v_pe;
  _1=_sendv(s_add_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info24= { "|", "PeOr", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 25, 27, &__info23 };
static oop PeOr___7c(oop v__closure, oop v_stateful_self, oop v_self, oop v_pe)
 {
  _enter(&__info24);
  oop _1= 0;
  oop _2= 0;
  _line(25);
  _1= ((struct t_PeOr *)v_stateful_self)->v_value;
  _2= v_pe;
  _line(25);
  _1=_sendv(s_addLast_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info25= { "textResult", "ParsingExpression", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 27, 28, &__info24 };
static oop ParsingExpression__textResult(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info25);
  oop _1= 0;
  oop _2= 0;
  _line(27);
  _1= v_PeTextResult;
  _2= v_self;
  _line(27);
  _1=_sendv(s_withValue_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info26= { "textResult", "PeTextResult", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 28, 30, &__info25 };
static oop PeTextResult__textResult(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info26);
  oop _1= 0;
  _line(28);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info27= { "action", "ParsingExpression", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 30, 31, &__info26 };
static oop ParsingExpression__action(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info27);
  oop _1= 0;
  oop _2= 0;
  _line(30);
  _1= v_PeAction;
  _2= v_self;
  _line(30);
  _1=_sendv(s_withValue_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info28= { "action", "PeTextResult", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 31, 32, &__info27 };
static oop PeTextResult__action(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info28);
  oop _1= 0;
  oop _2= 0;
  _line(31);
  _1= v_PeTextValueAction;
  _2= ((struct t_PeTextResult *)v_stateful_self)->v_value;
  _line(31);
  _1=_sendv(s_withValue_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info29= { "storeResult", "SmallInteger", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 32, 34, &__info28 };
static oop SmallInteger__storeResult(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info29);
  oop _1= 0;
  oop _2= 0;
  _line(32);
  _1= v_PeStoreResult;
  _2= v_self;
  _line(32);
  _1=_sendv(s_withValue_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info30= { "setResult", "BlockClosure", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 34, 35, &__info29 };
static oop BlockClosure__setResult(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info30);
  oop _1= 0;
  oop _2= 0;
  _line(34);
  _1= v_self;
  _2= l_31;
  _line(34);
  _1=_sendv(s_error_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info32= { "setResult", "StaticBlockClosure", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 35, 39, &__info30 };
static oop StaticBlockClosure__setResult(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info32);
  oop _1= 0;
  oop _2= 0;
  _line(35);
  _1= v_PeSetResult;
  _2= ((struct t_StaticBlockClosure *)v_stateful_self)->v__function;
  _line(35);
  _1=_sendv(s_withValue_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info33= { "->", "ParsingExpression", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 39, 40, &__info32 };
static oop ParsingExpression___2d_3e(oop v__closure, oop v_stateful_self, oop v_self, oop v_anInteger)
 {
  _enter(&__info33);
  oop _1= 0;
  oop _2= 0;
  _line(39);
  _1= v_self;
  _line(39);
  _1=_sendv(s_itemResult, 1, _1);
  _2= v_anInteger;
  _line(39);
  _2=_sendv(s_storeResult, 1, _2);
  _line(39);
  _1=_sendv(s__2c, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info34= { "=>", "ParsingExpression", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 40, 41, &__info33 };
static oop ParsingExpression___3d_3e(oop v__closure, oop v_stateful_self, oop v_self, oop v_anInteger)
 {
  _enter(&__info34);
  oop _1= 0;
  oop _2= 0;
  _line(40);
  _1= v_self;
  _2= v_anInteger;
  _line(40);
  _2=_sendv(s_storeResult, 1, _2);
  _line(40);
  _2=_sendv(s_action, 1, _2);
  _line(40);
  _1=_sendv(s__2c, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info35= { "<-", "ParsingExpression", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 41, 42, &__info34 };
static oop ParsingExpression___3c_2d(oop v__closure, oop v_stateful_self, oop v_self, oop v_aBlock)
 {
  _enter(&__info35);
  oop _1= 0;
  oop _2= 0;
  _line(41);
  _1= v_self;
  _2= v_aBlock;
  _line(41);
  _2=_sendv(s_setResult, 1, _2);
  _line(41);
  _1=_sendv(s__2c, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info36= { "<=", "ParsingExpression", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 42, 44, &__info35 };
static oop ParsingExpression___3c_3d(oop v__closure, oop v_stateful_self, oop v_self, oop v_aBlock)
 {
  _enter(&__info36);
  oop _1= 0;
  oop _2= 0;
  _line(42);
  _1= v_self;
  _2= v_aBlock;
  _line(42);
  _2=_sendv(s_setResult, 1, _2);
  _line(42);
  _2=_sendv(s_action, 1, _2);
  _line(42);
  _1=_sendv(s__2c, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info37= { "itemResult", "ParsingExpression", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 44, 45, &__info36 };
static oop ParsingExpression__itemResult(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info37);
  oop _1= 0;
  _line(44);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info38= { "itemResult", "PeAny", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 45, 47, &__info37 };
static oop PeAny__itemResult(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info38);
  oop _1= 0;
  oop _2= 0;
  _line(45);
  _1= v_PeItemResult;
  _2= v_self;
  _line(45);
  _1=_sendv(s_withValue_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info39= { "->", "ParsingExpressionRepeat", "/Users/chazu/dev/c/idst-with-history/function/jolt2/ParsingExpression-bootstrap.st", 0, 47, 52, &__info38 };
static oop ParsingExpressionRepeat___2d_3e(oop v__closure, oop v_stateful_self, oop v_self, oop v_anInteger)
 {
  _enter(&__info39);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(47);
  _1= ((struct t_ParsingExpressionRepeat *)v_stateful_self)->v_value;
  _2= v_PeCollectResult;
  _3= v_anInteger;
  _line(49);
  _2=_sendv(s_withValue_, 2, _2, _3);
  _line(49);
  _1=_sendv(s__2c, 2, _1, _2);
  ((struct t_ParsingExpressionRepeat *)v_stateful_self)->v_value= _1;
  _1= v_PeCollectResults;
  _2= v_self;
  _3= v_anInteger;
  _line(50);
  _1=_sendv(s_withValue_index_, 3, _1, _2, _3);
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "ParsingExpression-bootstrap.st", 0, 0, 0, &__info39 };
void __id__init__ParsingExpression_2dbootstrap(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
# define GC_add_roots _libid->gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info1);

  _sendv(s__5fimport_, 3, _libid->_object, "ParsingExpression", "__id__init__ParsingExpression");
  v__object= _libid->import("_object");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_Magnitude= _libid->import("Magnitude");
  v_Number= _libid->import("Number");
  v_Integer= _libid->import("Integer");
  v_SmallInteger= _libid->import("SmallInteger");
  v_Symbol= _libid->import("Symbol");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_Array= _libid->import("Array");
  v_ByteArray= _libid->import("ByteArray");
  v_String= _libid->import("String");
  v_IdentitySet= _libid->import("IdentitySet");
  v_IdentityDictionary= _libid->import("IdentityDictionary");
  v_SlotDictionary= _libid->import("SlotDictionary");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_BlockClosure= _libid->import("BlockClosure");
  v_ReadStream= _libid->import("ReadStream");
  v_FileStream= _libid->import("FileStream");
  v_File= _libid->import("File");
  v_true= _libid->import("true");
  v_false= _libid->import("false");
  v_Type= _libid->import("Type");
  v_NumericType= _libid->import("NumericType");
  v_IntegralType= _libid->import("IntegralType");
  v_I1= _libid->import("I1");
  v_I2= _libid->import("I2");
  v_I4= _libid->import("I4");
  v_I8= _libid->import("I8");
  v_FloatingType= _libid->import("FloatingType");
  v_PointerType= _libid->import("PointerType");
  v_ParsingExpression= _libid->import("ParsingExpression");
  v_PeAny= _libid->import("PeAny");
  v_PeRest= _libid->import("PeRest");
  v_ParsingExpressionValue= _libid->import("ParsingExpressionValue");
  v_PeIdentity= _libid->import("PeIdentity");
  v_PeClass= _libid->import("PeClass");
  v_PeSequence= _libid->import("PeSequence");
  v_ParsingExpressionSingle= _libid->import("ParsingExpressionSingle");
  v_PeNot= _libid->import("PeNot");
  v_PeStructure= _libid->import("PeStructure");
  v_ParsingExpressionRepeat= _libid->import("ParsingExpressionRepeat");
  v_PeZeroOne= _libid->import("PeZeroOne");
  v_PeZeroMore= _libid->import("PeZeroMore");
  v_PeOneMore= _libid->import("PeOneMore");
  v_PeName= _libid->import("PeName");
  v_ParsingExpressionMultiple= _libid->import("ParsingExpressionMultiple");
  v_PeAnd= _libid->import("PeAnd");
  v_PeOr= _libid->import("PeOr");
  v_PeTextResult= _libid->import("PeTextResult");
  v_PeTextValueAction= _libid->import("PeTextValueAction");
  v_PeItemResult= _libid->import("PeItemResult");
  v_PeAction= _libid->import("PeAction");
  v_PeStoreResult= _libid->import("PeStoreResult");
  v_PeSetResult= _libid->import("PeSetResult");
  v_PeCollectResult= _libid->import("PeCollectResult");
  v_PeCollectResults= _libid->import("PeCollectResults");
  l_2= _sendv(s_size_5f_value_5f_, 3, v_String, 35, "cannot make ParsingExpression from ");
  _libid->method(v_Object, s_parse, (_imp_t)Object__parse);
  _libid->method(v_SmallInteger, s_parse, (_imp_t)SmallInteger__parse);
  l_5= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_String, s_parse, (_imp_t)String__parse);
  _libid->method(v_SequenceableCollection, s_parseClass, (_imp_t)SequenceableCollection__parseClass);
  _libid->method(v_Symbol, s_parse, (_imp_t)Symbol__parse);
  _libid->method(v_Object, s_parseLiteral, (_imp_t)Object__parseLiteral);
  _libid->method(v_ParsingExpression, s_parseStructure, (_imp_t)ParsingExpression__parseStructure);
  _libid->method(v_ParsingExpression, s_zeroOne, (_imp_t)ParsingExpression__zeroOne);
  l_12= _sendv(s_size_5f_value_5f_, 3, v_String, 24, "cannot repeat repetition");
  _libid->method(v_ParsingExpressionRepeat, s_zeroOne, (_imp_t)ParsingExpressionRepeat__zeroOne);
  _libid->method(v_ParsingExpression, s_zeroMore, (_imp_t)ParsingExpression__zeroMore);
  l_15= _sendv(s_size_5f_value_5f_, 3, v_String, 24, "cannot repeat repetition");
  _libid->method(v_ParsingExpressionRepeat, s_zeroMore, (_imp_t)ParsingExpressionRepeat__zeroMore);
  _libid->method(v_ParsingExpression, s_oneMore, (_imp_t)ParsingExpression__oneMore);
  l_18= _sendv(s_size_5f_value_5f_, 3, v_String, 24, "cannot repeat repetition");
  _libid->method(v_ParsingExpressionRepeat, s_oneMore, (_imp_t)ParsingExpressionRepeat__oneMore);
  _libid->method(v_PeAny, s_zeroMore, (_imp_t)PeAny__zeroMore);
  _libid->method(v_ParsingExpression, s_not, (_imp_t)ParsingExpression__not);
  _libid->method(v_ParsingExpression, s__2c, (_imp_t)ParsingExpression___2c);
  _libid->method(v_PeAnd, s__2c, (_imp_t)PeAnd___2c);
  _libid->method(v_ParsingExpression, s__7c, (_imp_t)ParsingExpression___7c);
  _libid->method(v_PeOr, s__7c, (_imp_t)PeOr___7c);
  _libid->method(v_ParsingExpression, s_textResult, (_imp_t)ParsingExpression__textResult);
  _libid->method(v_PeTextResult, s_textResult, (_imp_t)PeTextResult__textResult);
  _libid->method(v_ParsingExpression, s_action, (_imp_t)ParsingExpression__action);
  _libid->method(v_PeTextResult, s_action, (_imp_t)PeTextResult__action);
  _libid->method(v_SmallInteger, s_storeResult, (_imp_t)SmallInteger__storeResult);
  l_31= _sendv(s_size_5f_value_5f_, 3, v_String, 66, "action block must not contain free references or non-local returns");
  _libid->method(v_BlockClosure, s_setResult, (_imp_t)BlockClosure__setResult);
  _libid->method(v_StaticBlockClosure, s_setResult, (_imp_t)StaticBlockClosure__setResult);
  _libid->method(v_ParsingExpression, s__2d_3e, (_imp_t)ParsingExpression___2d_3e);
  _libid->method(v_ParsingExpression, s__3d_3e, (_imp_t)ParsingExpression___3d_3e);
  _libid->method(v_ParsingExpression, s__3c_2d, (_imp_t)ParsingExpression___3c_2d);
  _libid->method(v_ParsingExpression, s__3c_3d, (_imp_t)ParsingExpression___3c_3d);
  _libid->method(v_ParsingExpression, s_itemResult, (_imp_t)ParsingExpression__itemResult);
  _libid->method(v_PeAny, s_itemResult, (_imp_t)PeAny__itemResult);
  _libid->method(v_ParsingExpressionRepeat, s__2d_3e, (_imp_t)ParsingExpressionRepeat___2d_3e);
  _leave();
}
