/* generated by Id 1.1 at шк	 */
/* with the command: -I../../object/stage2/ -I../objects -g -I../objects -c readline.st -o readline.o.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s__2d= 0;
static oop s__5fintegerValue= 0;
static oop s__2b= 0;
static oop s_value_5f_= 0;
static oop s_size= 0;
static oop s__5fimport_= 0;
static oop s_grow= 0;
static oop s__5fbytes= 0;
static oop s_refill= 0;
static oop s_whileTrue_= 0;
static oop s__5fatexit= 0;
static oop s__3c_3d= 0;
static oop s_at_put_= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "-", &s__2d },
  { "_integerValue", &s__5fintegerValue },
  { "+", &s__2b },
  { "value_:", &s_value_5f_ },
  { "size", &s_size },
  { "_import:", &s__5fimport_ },
  { "grow", &s_grow },
  { "_bytes", &s__5fbytes },
  { "refill", &s_refill },
  { "whileTrue:", &s_whileTrue_ },
  { "_atexit", &s__5fatexit },
  { "<=", &s__3c_3d },
  { "at:put:", &s_at_put_ },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Date {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__microseconds;
};
struct t_Time {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__nanoseconds;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargeInteger {
  struct _vtable *_vtable[0];
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t_Association {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t_Link {
  struct _vtable *_vtable[0];
  oop v_prevLink;
  oop v_nextLink;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_LinkedList {
  struct _vtable *_vtable[0];
  oop v_firstLink;
  oop v_lastLink;
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__oops;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_OrderedCollection {
  struct _vtable *_vtable[0];
  oop v_firstIndex;
  oop v_lastIndex;
  oop v_array;
};
struct t_IdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Set {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_IdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Dictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_FastIdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_SlotDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_MemoDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_ProfiledMethod {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_count;
  oop v_next;
};
struct t_SinkStream {
  struct _vtable *_vtable[0];
};
struct t_ReadStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_WriteStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_writeLimit;
};
struct t_FileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
};
struct t_ConsoleFileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
  oop v__prompt;
};
struct t_File {
  struct _vtable *_vtable[0];
  oop v__fd;
  oop v_name;
};
struct t_Function {
  struct _vtable *_vtable[0];
};
struct t_Random {
  struct _vtable *_vtable[0];
  oop v_seed;
  oop v_a;
  oop v_m;
  oop v_q;
  oop v_r;
};
struct t_OS {
  struct _vtable *_vtable[0];
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
static oop l_3= 0;
static oop l_4= 0;
static oop v__object= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_Magnitude= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_SmallInteger= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_ByteArray= 0;
static oop v_IdentitySet= 0;
static oop v_IdentityDictionary= 0;
static oop v_SlotDictionary= 0;
static oop v_StaticBlockClosure= 0;
static oop v_ReadStream= 0;
static oop v_FileStream= 0;
static oop v_ConsoleFileStream= 0;
static oop v_true= 0;
static oop v_false= 0;
#include "readline.h"
static struct __methodinfo __info1= { "_atexit", "ConsoleFileStream", "/Users/chazu/dev/c/idst-with-history/function/jolt2/readline.st", 0, 5, 10, 0 };
static oop ConsoleFileStream___5fatexit(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info1);
  oop _1= 0;
  _line(5);
 {
# define self ((struct t_ConsoleFileStream *)v_self)

    write_history(".jolt-history");

# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info2= { "refill", "ConsoleFileStream", "/Users/chazu/dev/c/idst-with-history/function/jolt2/readline.st", 0, 10, 45, &__info1 };
static oop ConsoleFileStream__refill(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info2);
  oop v_length= 0;
  oop v__buffer= 0;
  oop v__bytes= 0;
  oop v__position= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  (void)v_length;
  (void)v__buffer;
  (void)v__bytes;
  (void)v__position;
  _line(10);
 {
# define self ((struct t_ConsoleFileStream *)v_self)

	static char *buffer= 0;
        static int   live= 1;
        if (!live)
	    { _return 0; }
	if (buffer)
	{
	    free(buffer);
	    buffer= 0;
	}
	else
	{
	    using_history();
	    stifle_history(1000);
	    read_history(".jolt-history");
	    atexit((void (*)(void))ConsoleFileStream___5fatexit);
	}
	buffer= readline((char *)self->v__prompt);
	if (!buffer) { _return (oop)(live= 0); }
	if (*buffer) add_history(buffer);
	v_length= (oop)((strlen(buffer) + 1) << 1 | 1);
	v__buffer= (oop)buffer;
    
# undef self
 }
  _1= 0;
  /* whileTrue: */
  goto _l2;
 _l1:;
 {
  _1= v_self;
  _line(36);
  _1=_sendv(s_grow, 1, _1);
 }
 _l2:;
 {
  _1= ((struct t_ConsoleFileStream *)v_stateful_self)->v_collection;
  _line(36);
  _1=_sendv(s_size, 1, _1);
  _2= ((struct t_ConsoleFileStream *)v_stateful_self)->v_position;
  _3= v_length;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_2 & (long)_3) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2b, 2, _2, _3);
  }
  if (1 & (long)_1 & (long)_2) {
    _1= (((long)_1 <= (long)_2) ? v_true : v_false);
  } else _1= _sendv(s__3c_3d, 2, _1, _2);
 }
  if (_1) goto _l1;
  _1= 0;
  _1= ((struct t_ConsoleFileStream *)v_stateful_self)->v_collection;
  _line(37);
  _1=_sendv(s__5fbytes, 1, _1);
  v__bytes= _1;
  _1= ((struct t_ConsoleFileStream *)v_stateful_self)->v_position;
  _line(38);
  _1=_sendv(s__5fintegerValue, 1, _1);
  v__position= _1;
 {
# define self ((struct t_ConsoleFileStream *)v_self)

	strcpy((char *)v__bytes + (long)v__position, (char *)v__buffer);
    
# undef self
 }
  _1= 0;
  _1= ((struct t_ConsoleFileStream *)v_stateful_self)->v_collection;
  _2= ((struct t_ConsoleFileStream *)v_stateful_self)->v_position;
  _3= v_length;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_2 & (long)_3) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2b, 2, _2, _3);
  }
  _3= l_3;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2d, 2, _2, _3);
  }
  _3= l_4;
  _line(42);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _1= ((struct t_ConsoleFileStream *)v_stateful_self)->v_position;
  _2= v_length;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  ((struct t_ConsoleFileStream *)v_stateful_self)->v_readLimit= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "readline.st", 0, 0, 0, &__info2 };
void __id__init__readline(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
# define GC_add_roots _libid->gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info1);

  _sendv(s__5fimport_, 3, _libid->_object, "Stream", "__id__init__Stream");
  v__object= _libid->import("_object");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_Magnitude= _libid->import("Magnitude");
  v_Number= _libid->import("Number");
  v_Integer= _libid->import("Integer");
  v_SmallInteger= _libid->import("SmallInteger");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_ByteArray= _libid->import("ByteArray");
  v_IdentitySet= _libid->import("IdentitySet");
  v_IdentityDictionary= _libid->import("IdentityDictionary");
  v_SlotDictionary= _libid->import("SlotDictionary");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_ReadStream= _libid->import("ReadStream");
  v_FileStream= _libid->import("FileStream");
  v_ConsoleFileStream= _libid->import("ConsoleFileStream");
  v_true= _libid->import("true");
  v_false= _libid->import("false");
  _libid->method(v_ConsoleFileStream, s__5fatexit, (_imp_t)ConsoleFileStream___5fatexit);
  l_3= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  l_4= _sendv(s_value_5f_, 2, v_SmallInteger, 10);
  _libid->method(v_ConsoleFileStream, s_refill, (_imp_t)ConsoleFileStream__refill);
  _leave();
}
