/* generated by Id 1.1 at ËZ¨ */
/* with the command: -I../../object/stage2/ -I. -g -g -c Array.st -o Array.o.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s__5fpalloc_= 0;
static oop s_do_= 0;
static oop s_value_5f_= 0;
static oop s__5fimport_= 0;
static oop s_at_5f_= 0;
static oop s__5felements= 0;
static oop s_new_= 0;
static oop s__3c= 0;
static oop s_to_do_= 0;
static oop s_isArray= 0;
static oop s_and_= 0;
static oop s__3c_3d= 0;
static oop s_at_5f_put_= 0;
static oop s_nextPut_= 0;
static oop s_new_5f_= 0;
static oop s_new= 0;
static oop s__2d= 0;
static oop s_size_5f_value_5f_= 0;
static oop s_ifTrue_ifFalse_= 0;
static oop s__5fintegerValue= 0;
static oop s_errorOutOfBounds_= 0;
static oop s_argumentVectorSize= 0;
static oop s__5fargumentVectorSize= 0;
static oop s_argumentVectorAt_= 0;
static oop s__5fargumentVectorAt_5f_= 0;
static oop s_argumentVector= 0;
static oop s_function_5f_arity_5f_outer_state_nlr_5f_= 0;
static oop s_printContentsOn_= 0;
static oop s_import= 0;
static oop s_function_5f_arity_5f_= 0;
static oop s_printOn_= 0;
static oop s_at_= 0;
static oop s_at_put_= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "_palloc:", &s__5fpalloc_ },
  { "do:", &s_do_ },
  { "value_:", &s_value_5f_ },
  { "_import:", &s__5fimport_ },
  { "at_:", &s_at_5f_ },
  { "_elements", &s__5felements },
  { "new:", &s_new_ },
  { "<", &s__3c },
  { "to:do:", &s_to_do_ },
  { "isArray", &s_isArray },
  { "and:", &s_and_ },
  { "<=", &s__3c_3d },
  { "at_:put:", &s_at_5f_put_ },
  { "nextPut:", &s_nextPut_ },
  { "new_:", &s_new_5f_ },
  { "new", &s_new },
  { "-", &s__2d },
  { "size_:value_:", &s_size_5f_value_5f_ },
  { "ifTrue:ifFalse:", &s_ifTrue_ifFalse_ },
  { "_integerValue", &s__5fintegerValue },
  { "errorOutOfBounds:", &s_errorOutOfBounds_ },
  { "argumentVectorSize", &s_argumentVectorSize },
  { "_argumentVectorSize", &s__5fargumentVectorSize },
  { "argumentVectorAt:", &s_argumentVectorAt_ },
  { "_argumentVectorAt_:", &s__5fargumentVectorAt_5f_ },
  { "argumentVector", &s_argumentVector },
  { "function_:arity_:outer:state:nlr_:", &s_function_5f_arity_5f_outer_state_nlr_5f_ },
  { "printContentsOn:", &s_printContentsOn_ },
  { "import", &s_import },
  { "function_:arity_:", &s_function_5f_arity_5f_ },
  { "printOn:", &s_printOn_ },
  { "at:", &s_at_ },
  { "at:put:", &s_at_put_ },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Date {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__microseconds;
};
struct t_Time {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__nanoseconds;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargeInteger {
  struct _vtable *_vtable[0];
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t_Association {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t_Link {
  struct _vtable *_vtable[0];
  oop v_prevLink;
  oop v_nextLink;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_LinkedList {
  struct _vtable *_vtable[0];
  oop v_firstLink;
  oop v_lastLink;
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__oops;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_OrderedCollection {
  struct _vtable *_vtable[0];
  oop v_firstIndex;
  oop v_lastIndex;
  oop v_array;
};
struct t_IdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Set {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_IdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Dictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_FastIdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_SlotDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_MemoDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_ProfiledMethod {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_count;
  oop v_next;
};
struct t_SinkStream {
  struct _vtable *_vtable[0];
};
struct t_ReadStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_WriteStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_writeLimit;
};
struct t_FileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
};
struct t_ConsoleFileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
  oop v__prompt;
};
struct t_File {
  struct _vtable *_vtable[0];
  oop v__fd;
  oop v_name;
};
struct t_Function {
  struct _vtable *_vtable[0];
};
struct t_Random {
  struct _vtable *_vtable[0];
  oop v_seed;
  oop v_a;
  oop v_m;
  oop v_q;
  oop v_r;
};
struct t_OS {
  struct _vtable *_vtable[0];
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
static oop l_7= 0;
static oop l_10= 0;
static oop l_17= 0;
static oop l_18= 0;
static oop l_21= 0;
static oop l_23= 0;
static oop v__object= 0;
static oop v__vector= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_Magnitude= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_SmallInteger= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_Array= 0;
static oop v_ByteArray= 0;
static oop v_String= 0;
static oop v_IdentitySet= 0;
static oop v_IdentityDictionary= 0;
static oop v_SlotDictionary= 0;
static oop v_StaticBlockClosure= 0;
static oop v_BlockClosure= 0;
static oop v_ReadStream= 0;
static oop v_FileStream= 0;
static oop v_true= 0;
static oop v_false= 0;
static struct __methodinfo __info1= { "isArray", "_object", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 23, 24, 0 };
static oop _object__isArray(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info1);
  oop _1= 0;
  _line(23);
  _1= v_false;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info2= { "isArray", "Array", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 24, 26, &__info1 };
static oop Array__isArray(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info2);
  oop _1= 0;
  _line(24);
  _1= v_true;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info3= { "size_:value_:", "Array", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 26, 36, &__info2 };
static oop Array__size_5f_value_5f_(oop v__closure, oop v_stateful_self, oop v_self, oop v__size, oop v__value)
 {
  _enter(&__info3);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(26);
  _1= v_self;
  _2= v_SmallInteger;
  _3= v__size;
  _line(28);
  _2=_sendv(s_value_5f_, 2, _2, _3);
  _line(28);
  _1=_sendv(s_new_, 2, _1, _2);
  v_self= _1;
  v_stateful_self= _1;
 {
# define self ((struct t_Array *)v_self)

      int i;
      for (i= 0;  i < (long)v__size;  ++i)
        ((oop *)self->v__oops)[i]= *((oop **)v__value)[i];
    
# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info4= { "new:", "Array", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 36, 43, &__info3 };
static oop Array__new_(oop v__closure, oop v_stateful_self, oop v_self, oop v_capacity)
 {
  _enter(&__info4);
  oop _1= 0;
  oop _2= 0;
  _line(36);
  _1= v_self;
  _line(38);
  _1=_superv(v_ArrayedCollection, s_new, 1, _1);
  v_self= _1;
  v_stateful_self= _1;
  _1= v_capacity;
  ((struct t_Array *)v_stateful_self)->v_size= _1;
  _1= v_self;
  _2= ((struct t_Array *)v_stateful_self)->v_size;
  _line(40);
  _1=_sendv(s__5fpalloc_, 2, _1, _2);
  ((struct t_Array *)v_stateful_self)->v__oops= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info5= { "_elements", "Array", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 43, 45, &__info4 };
static oop Array___5felements(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info5);
  oop _1= 0;
  _line(43);
  _1= ((struct t_Array *)v_stateful_self)->v__oops;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info6= { "at:", "Array", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 45, 52, &__info5 };
static oop Array__at_(oop v__closure, oop v_stateful_self, oop v_self, oop v_offset)
 {
  _enter(&__info6);
  oop _1= 0;
  oop _2= 0;
  _line(45);
  /* ifTrue:ifFalse: */
  /* and: */
  _1= l_7;
  _2= v_offset;
  if (1 & (long)_2) {
    _1= (((long)_1 <= (long)_2) ? v_true : v_false);
  } else _1= _sendv(s__3c_3d, 2, _1, _2);
  if (!_1) goto _l3;
 {
  _1= v_offset;
  _2= ((struct t_Array *)v_stateful_self)->v_size;
  if (1 & (long)_1 & (long)_2) {
    _1= (((long)_1 < (long)_2) ? v_true : v_false);
  } else _1= _sendv(s__3c, 2, _1, _2);
 }
 _l3:;
  if (!_1) goto _l1;
 {
  _1= v_self;
  _2= v_offset;
  _line(48);
  _2=_sendv(s__5fintegerValue, 1, _2);
  _line(48);
  _1=_sendv(s_at_5f_, 2, _1, _2);
 }
  goto _l2;
 _l1:;
 {
  _1= v_self;
  _2= v_offset;
  _line(49);
  _1=_sendv(s_errorOutOfBounds_, 2, _1, _2);
 }
 _l2:;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info8= { "at_:", "Array", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 52, 57, &__info6 };
static oop Array__at_5f_(oop v__closure, oop v_stateful_self, oop v_self, oop v__offset)
 {
  _enter(&__info8);
  oop _1= 0;
  _line(52);
 {
# define self ((struct t_Array *)v_self)

    _return ((oop *)self->v__oops)[(long)v__offset];

# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info9= { "at:put:", "Array", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 57, 64, &__info8 };
static oop Array__at_put_(oop v__closure, oop v_stateful_self, oop v_self, oop v_offset, oop v_anObject)
 {
  _enter(&__info9);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(57);
  /* ifTrue:ifFalse: */
  /* and: */
  _1= l_10;
  _2= v_offset;
  if (1 & (long)_2) {
    _1= (((long)_1 <= (long)_2) ? v_true : v_false);
  } else _1= _sendv(s__3c_3d, 2, _1, _2);
  if (!_1) goto _l6;
 {
  _1= v_offset;
  _2= ((struct t_Array *)v_stateful_self)->v_size;
  if (1 & (long)_1 & (long)_2) {
    _1= (((long)_1 < (long)_2) ? v_true : v_false);
  } else _1= _sendv(s__3c, 2, _1, _2);
 }
 _l6:;
  if (!_1) goto _l4;
 {
  _1= v_self;
  _2= v_offset;
  _line(60);
  _2=_sendv(s__5fintegerValue, 1, _2);
  _3= v_anObject;
  _line(60);
  _1=_sendv(s_at_5f_put_, 3, _1, _2, _3);
 }
  goto _l5;
 _l4:;
 {
  _1= v_self;
  _2= v_offset;
  _line(61);
  _1=_sendv(s_errorOutOfBounds_, 2, _1, _2);
 }
 _l5:;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info11= { "at_:put:", "Array", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 64, 69, &__info9 };
static oop Array__at_5f_put_(oop v__closure, oop v_stateful_self, oop v_self, oop v__offset, oop v_anObject)
 {
  _enter(&__info11);
  oop _1= 0;
  _line(64);
 {
# define self ((struct t_Array *)v_self)

    _return ((oop *)self->v__oops)[(long)v__offset]= v_anObject;

# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info12= { "argumentVectorSize", "Array", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 69, 70, &__info11 };
static oop Array__argumentVectorSize(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info12);
  oop _1= 0;
  oop _2= 0;
  _line(69);
  _1= v_SmallInteger;
  _2= v_self;
  _line(69);
  _2=_sendv(s__5fargumentVectorSize, 1, _2);
  _line(69);
  _1=_sendv(s_value_5f_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info13= { "_argumentVectorSize", "Array", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 70, 71, &__info12 };
static oop Array___5fargumentVectorSize(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info13);
  oop _1= 0;
  _line(70);
 {
# define self ((struct t_Array *)v_self)
 _return (oop)_libid->param(0); 
# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info14= { "argumentVectorAt:", "Array", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 71, 72, &__info13 };
static oop Array__argumentVectorAt_(oop v__closure, oop v_stateful_self, oop v_self, oop v_offset)
 {
  _enter(&__info14);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(71);
  _1= v_String;
  _2= v_self;
  _3= v_offset;
  _line(71);
  _3=_sendv(s__5fintegerValue, 1, _3);
  _line(71);
  _2=_sendv(s__5fargumentVectorAt_5f_, 2, _2, _3);
  _line(71);
  _1=_sendv(s_value_5f_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info15= { "_argumentVectorAt_:", "Array", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 72, 74, &__info14 };
static oop Array___5fargumentVectorAt_5f_(oop v__closure, oop v_stateful_self, oop v_self, oop v__off)
 {
  _enter(&__info15);
  oop _1= 0;
  _line(72);
 {
# define self ((struct t_Array *)v_self)
 _return (oop)(((char **)_libid->param(1))[(long)v__off]); 
# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info19= { "[] argumentVector", "Array", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 74, 80, &__info15 };
static oop b_19(oop v__closure, oop v__self, oop v_offset)
 {
  _enter(&__info19);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  _line(77);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* self */
  _2= v_offset;
  _3= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* self */
  _4= v_offset;
  _line(77);
  _3=_sendv(s_argumentVectorAt_, 2, _3, _4);
  _line(77);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info16= { "argumentVector", "Array", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 74, 80, &__info19 };
static oop Array__argumentVector(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info16);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 5);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  ((oop *)_state1)[2]= v_stateful_self;
  ((oop *)_state1)[1]= v_self;
  _line(74);
  _1= ((oop *)_state1)[1];  /* self */
  _2= ((oop *)_state1)[1];  /* self */
  _line(76);
  _2=_sendv(s_argumentVectorSize, 1, _2);
  _line(76);
  _1=_sendv(s_new_, 2, _1, _2);
  ((oop *)_state1)[1]= _1;  /* self */
  ((oop *)_state1)[2]= _1;  /* stateful_self */
  _1= l_17;
  _2= ((struct t_Array *)((oop *)_state1)[2])->v_size;  /* size */
  _3= l_18;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2d, 2, _2, _3);
  }
  /* Scope('offset'->ArgumentVariableNode) */
  /* Scope('size'->SlotVariableNode 'self'->ArgumentVariableNode '_oops'->SlotVariableNode 'stateful_self'->ArgumentVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_19, 1, 0, ((oop *)_state1), 0);
  _line(77);
  _1=_sendv(s_to_do_, 3, _1, _2, _3);
  _1= ((oop *)_state1)[1];  /* self */
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info20= { "printOn:", "Array", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 80, 86, &__info16 };
static oop Array__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info20);
  oop _1= 0;
  oop _2= 0;
  _line(80);
  _1= v_aStream;
  _2= l_21;
  _line(82);
  _1=_sendv(s_nextPut_, 2, _1, _2);
  _1= v_self;
  _2= v_aStream;
  _line(83);
  _1=_sendv(s_printContentsOn_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info23= { "[] import", "Array", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 86, 87, &__info20 };
static oop b_23(oop v__closure, oop v__self, oop v_s)
 {
  _enter(&__info23);
  oop _1= 0;
  _line(86);
  _1= v_s;
  _line(86);
  _1=_sendv(s_import, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info22= { "import", "Array", "/Users/chazu/dev/c/idst-with-history/function/objects/Array.st", 0, 86, 87, &__info23 };
static oop Array__import(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info22);
  oop _1= 0;
  oop _2= 0;
  _line(86);
  _1= v_self;
  _2= l_23;
  _line(86);
  _1=_sendv(s_do_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "Array.st", 0, 0, 0, &__info22 };
void __id__init__Array(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
# define GC_add_roots _libid->gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info1);

  _sendv(s__5fimport_, 3, _libid->_object, "Objects", "__id__init__Objects");
  v__object= _libid->import("_object");
  v__vector= _libid->import("_vector");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_Magnitude= _libid->import("Magnitude");
  v_Number= _libid->import("Number");
  v_Integer= _libid->import("Integer");
  v_SmallInteger= _libid->import("SmallInteger");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_Array= _libid->import("Array");
  v_ByteArray= _libid->import("ByteArray");
  v_String= _libid->import("String");
  v_IdentitySet= _libid->import("IdentitySet");
  v_IdentityDictionary= _libid->import("IdentityDictionary");
  v_SlotDictionary= _libid->import("SlotDictionary");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_BlockClosure= _libid->import("BlockClosure");
  v_ReadStream= _libid->import("ReadStream");
  v_FileStream= _libid->import("FileStream");
  v_true= _libid->import("true");
  v_false= _libid->import("false");
  _libid->method(v__object, s_isArray, (_imp_t)_object__isArray);
  _libid->method(v_Array, s_isArray, (_imp_t)Array__isArray);
  _libid->method(v_Array, s_size_5f_value_5f_, (_imp_t)Array__size_5f_value_5f_);
  _libid->method(v_Array, s_new_, (_imp_t)Array__new_);
  _libid->method(v_Array, s__5felements, (_imp_t)Array___5felements);
  l_7= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  _libid->method(v_Array, s_at_, (_imp_t)Array__at_);
  _libid->method(v_Array, s_at_5f_, (_imp_t)Array__at_5f_);
  l_10= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  _libid->method(v_Array, s_at_put_, (_imp_t)Array__at_put_);
  _libid->method(v_Array, s_at_5f_put_, (_imp_t)Array__at_5f_put_);
  _libid->method(v_Array, s_argumentVectorSize, (_imp_t)Array__argumentVectorSize);
  _libid->method(v_Array, s__5fargumentVectorSize, (_imp_t)Array___5fargumentVectorSize);
  _libid->method(v_Array, s_argumentVectorAt_, (_imp_t)Array__argumentVectorAt_);
  _libid->method(v_Array, s__5fargumentVectorAt_5f_, (_imp_t)Array___5fargumentVectorAt_5f_);
  l_17= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  l_18= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_Array, s_argumentVector, (_imp_t)Array__argumentVector);
  l_21= _sendv(s_value_5f_, 2, v_SmallInteger, 35);
  _libid->method(v_Array, s_printOn_, (_imp_t)Array__printOn_);
  l_23= _sendv(s_function_5f_arity_5f_, 3, v_StaticBlockClosure, b_23, 1);
  _libid->method(v_Array, s_import, (_imp_t)Array__import);
  _leave();
}
