/* generated by Id 1.1 at èÚp */
/* with the command: -I../../object/stage2/ -I. -g -g -c Association.st -o Association.o.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s_new= 0;
static oop s_withKey_value_= 0;
static oop s_identityHash= 0;
static oop s_nextPutAll_= 0;
static oop s__2d_3e= 0;
static oop s_value_5f_= 0;
static oop s__5fimport_= 0;
static oop s_key= 0;
static oop s_print_= 0;
static oop s_size_5f_value_5f_= 0;
static oop s_hash= 0;
static oop s_printOn_= 0;
static oop s_setValue_= 0;
static oop s_value= 0;
static oop s_nextPut_= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "new", &s_new },
  { "withKey:value:", &s_withKey_value_ },
  { "identityHash", &s_identityHash },
  { "nextPutAll:", &s_nextPutAll_ },
  { "->", &s__2d_3e },
  { "value_:", &s_value_5f_ },
  { "_import:", &s__5fimport_ },
  { "key", &s_key },
  { "print:", &s_print_ },
  { "size_:value_:", &s_size_5f_value_5f_ },
  { "hash", &s_hash },
  { "printOn:", &s_printOn_ },
  { "setValue:", &s_setValue_ },
  { "value", &s_value },
  { "nextPut:", &s_nextPut_ },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Date {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__microseconds;
};
struct t_Time {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__nanoseconds;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargeInteger {
  struct _vtable *_vtable[0];
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t_Association {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t_Link {
  struct _vtable *_vtable[0];
  oop v_prevLink;
  oop v_nextLink;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_LinkedList {
  struct _vtable *_vtable[0];
  oop v_firstLink;
  oop v_lastLink;
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__oops;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_OrderedCollection {
  struct _vtable *_vtable[0];
  oop v_firstIndex;
  oop v_lastIndex;
  oop v_array;
};
struct t_IdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Set {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_IdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Dictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_FastIdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_SlotDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_MemoDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_ProfiledMethod {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_count;
  oop v_next;
};
struct t_SinkStream {
  struct _vtable *_vtable[0];
};
struct t_ReadStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_WriteStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_writeLimit;
};
struct t_FileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
};
struct t_ConsoleFileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
  oop v__prompt;
};
struct t_File {
  struct _vtable *_vtable[0];
  oop v__fd;
  oop v_name;
};
struct t_Function {
  struct _vtable *_vtable[0];
};
struct t_Random {
  struct _vtable *_vtable[0];
  oop v_seed;
  oop v_a;
  oop v_m;
  oop v_q;
  oop v_r;
};
struct t_OS {
  struct _vtable *_vtable[0];
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
static oop l_9= 0;
static oop l_10= 0;
static oop l_11= 0;
static oop v__object= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_Magnitude= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_SmallInteger= 0;
static oop v_Association= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_ByteArray= 0;
static oop v_String= 0;
static oop v_IdentitySet= 0;
static oop v_IdentityDictionary= 0;
static oop v_SlotDictionary= 0;
static oop v_StaticBlockClosure= 0;
static oop v_ReadStream= 0;
static oop v_FileStream= 0;
static struct __methodinfo __info1= { "key", "Association", "/Users/chazu/dev/c/idst-with-history/function/objects/Association.st", 0, 25, 26, 0 };
static oop Association__key(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info1);
  oop _1= 0;
  _line(25);
  _1= ((struct t_Association *)v_stateful_self)->v_key;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info2= { "value", "Association", "/Users/chazu/dev/c/idst-with-history/function/objects/Association.st", 0, 26, 28, &__info1 };
static oop Association__value(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info2);
  oop _1= 0;
  _line(26);
  _1= ((struct t_Association *)v_stateful_self)->v_value;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info3= { "->", "Object", "/Users/chazu/dev/c/idst-with-history/function/objects/Association.st", 0, 28, 33, &__info2 };
static oop Object___2d_3e(oop v__closure, oop v_stateful_self, oop v_self, oop v_anObject)
 {
  _enter(&__info3);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(28);
  _1= v_Association;
  _2= v_self;
  _3= v_anObject;
  _line(30);
  _1=_sendv(s_withKey_value_, 3, _1, _2, _3);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info4= { "withKey:value:", "Association", "/Users/chazu/dev/c/idst-with-history/function/objects/Association.st", 0, 33, 40, &__info3 };
static oop Association__withKey_value_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aKey, oop v_aValue)
 {
  _enter(&__info4);
  oop _1= 0;
  _line(33);
  _1= v_self;
  _line(35);
  _1=_sendv(s_new, 1, _1);
  v_self= _1;
  v_stateful_self= _1;
  _1= v_aKey;
  ((struct t_Association *)v_stateful_self)->v_key= _1;
  _1= v_aValue;
  ((struct t_Association *)v_stateful_self)->v_value= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info5= { "setValue:", "Association", "/Users/chazu/dev/c/idst-with-history/function/objects/Association.st", 0, 40, 45, &__info4 };
static oop Association__setValue_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aValue)
 {
  _enter(&__info5);
  oop _1= 0;
  _line(40);
  _1= v_aValue;
  ((struct t_Association *)v_stateful_self)->v_value= _1;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info6= { "identityHash", "Association", "/Users/chazu/dev/c/idst-with-history/function/objects/Association.st", 0, 45, 50, &__info5 };
static oop Association__identityHash(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info6);
  oop _1= 0;
  _line(45);
  _1= ((struct t_Association *)v_stateful_self)->v_key;
  _line(47);
  _1=_sendv(s_identityHash, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info7= { "hash", "Association", "/Users/chazu/dev/c/idst-with-history/function/objects/Association.st", 0, 50, 55, &__info6 };
static oop Association__hash(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info7);
  oop _1= 0;
  _line(50);
  _1= ((struct t_Association *)v_stateful_self)->v_key;
  _line(52);
  _1=_sendv(s_hash, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info8= { "printOn:", "Association", "/Users/chazu/dev/c/idst-with-history/function/objects/Association.st", 0, 55, 59, &__info7 };
static oop Association__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info8);
  oop _1= 0;
  oop _2= 0;
  _line(55);
  _1= v_aStream;
  _2= l_9;
  _line(57);
  _sendv(s_nextPut_, 2, _1, _2);
  _2= ((struct t_Association *)v_stateful_self)->v_key;
  _sendv(s_print_, 2, _1, _2);
  _2= l_10;
  _sendv(s_nextPutAll_, 2, _1, _2);
  _2= ((struct t_Association *)v_stateful_self)->v_value;
  _sendv(s_print_, 2, _1, _2);
  _2= l_11;
  _1=_sendv(s_nextPut_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "Association.st", 0, 0, 0, &__info8 };
void __id__init__Association(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
# define GC_add_roots _libid->gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info1);

  _sendv(s__5fimport_, 3, _libid->_object, "Objects", "__id__init__Objects");
  v__object= _libid->import("_object");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_Magnitude= _libid->import("Magnitude");
  v_Number= _libid->import("Number");
  v_Integer= _libid->import("Integer");
  v_SmallInteger= _libid->import("SmallInteger");
  v_Association= _libid->import("Association");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_ByteArray= _libid->import("ByteArray");
  v_String= _libid->import("String");
  v_IdentitySet= _libid->import("IdentitySet");
  v_IdentityDictionary= _libid->import("IdentityDictionary");
  v_SlotDictionary= _libid->import("SlotDictionary");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_ReadStream= _libid->import("ReadStream");
  v_FileStream= _libid->import("FileStream");
  _libid->method(v_Association, s_key, (_imp_t)Association__key);
  _libid->method(v_Association, s_value, (_imp_t)Association__value);
  _libid->method(v_Object, s__2d_3e, (_imp_t)Object___2d_3e);
  _libid->method(v_Association, s_withKey_value_, (_imp_t)Association__withKey_value_);
  _libid->method(v_Association, s_setValue_, (_imp_t)Association__setValue_);
  _libid->method(v_Association, s_identityHash, (_imp_t)Association__identityHash);
  _libid->method(v_Association, s_hash, (_imp_t)Association__hash);
  l_9= _sendv(s_value_5f_, 2, v_SmallInteger, 40);
  l_10= _sendv(s_size_5f_value_5f_, 3, v_String, 4, " -> ");
  l_11= _sendv(s_value_5f_, 2, v_SmallInteger, 41);
  _libid->method(v_Association, s_printOn_, (_imp_t)Association__printOn_);
  _leave();
}
