/* generated by Id 1.1 at èÚ˜ */
/* with the command: -I../../object/stage2/ -I. -g -g -c BlockClosure.st -o BlockClosure.o.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s__2c= 0;
static oop s_value_value_value_= 0;
static oop s_function_5f_arity_5f_= 0;
static oop s_errorArgumentCount_= 0;
static oop s_size_5f_value_5f_= 0;
static oop s_value_5f_= 0;
static oop s_arity= 0;
static oop s__5fimport_= 0;
static oop s_printString= 0;
static oop s_value_value_= 0;
static oop s_value_value_value_value_= 0;
static oop s_value_value_value_value_value_= 0;
static oop s_whileFalse_= 0;
static oop s_ifFalse_= 0;
static oop s_function_5f_arity_5f_outer_state_nlr_5f_= 0;
static oop s_printExecutionProfile= 0;
static oop s_value_= 0;
static oop s_whileTrue_= 0;
static oop s_ifTrue_= 0;
static oop s_whileFalse= 0;
static oop s_error_= 0;
static oop s_value= 0;
static oop s_whileTrue= 0;
static oop s_repeat= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { ",", &s__2c },
  { "value:value:value:", &s_value_value_value_ },
  { "function_:arity_:", &s_function_5f_arity_5f_ },
  { "errorArgumentCount:", &s_errorArgumentCount_ },
  { "size_:value_:", &s_size_5f_value_5f_ },
  { "value_:", &s_value_5f_ },
  { "arity", &s_arity },
  { "_import:", &s__5fimport_ },
  { "printString", &s_printString },
  { "value:value:", &s_value_value_ },
  { "value:value:value:value:", &s_value_value_value_value_ },
  { "value:value:value:value:value:", &s_value_value_value_value_value_ },
  { "whileFalse:", &s_whileFalse_ },
  { "ifFalse:", &s_ifFalse_ },
  { "function_:arity_:outer:state:nlr_:", &s_function_5f_arity_5f_outer_state_nlr_5f_ },
  { "printExecutionProfile", &s_printExecutionProfile },
  { "value:", &s_value_ },
  { "whileTrue:", &s_whileTrue_ },
  { "ifTrue:", &s_ifTrue_ },
  { "whileFalse", &s_whileFalse },
  { "error:", &s_error_ },
  { "value", &s_value },
  { "whileTrue", &s_whileTrue },
  { "repeat", &s_repeat },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Date {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__microseconds;
};
struct t_Time {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__nanoseconds;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargeInteger {
  struct _vtable *_vtable[0];
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t_Association {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t_Link {
  struct _vtable *_vtable[0];
  oop v_prevLink;
  oop v_nextLink;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_LinkedList {
  struct _vtable *_vtable[0];
  oop v_firstLink;
  oop v_lastLink;
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__oops;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_OrderedCollection {
  struct _vtable *_vtable[0];
  oop v_firstIndex;
  oop v_lastIndex;
  oop v_array;
};
struct t_IdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Set {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_IdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Dictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_FastIdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_SlotDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_MemoDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_ProfiledMethod {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_count;
  oop v_next;
};
struct t_SinkStream {
  struct _vtable *_vtable[0];
};
struct t_ReadStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_WriteStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_writeLimit;
};
struct t_FileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
};
struct t_ConsoleFileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
  oop v__prompt;
};
struct t_File {
  struct _vtable *_vtable[0];
  oop v__fd;
  oop v_name;
};
struct t_Function {
  struct _vtable *_vtable[0];
};
struct t_Random {
  struct _vtable *_vtable[0];
  oop v_seed;
  oop v_a;
  oop v_m;
  oop v_q;
  oop v_r;
};
struct t_OS {
  struct _vtable *_vtable[0];
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
static oop l_4= 0;
static oop l_5= 0;
static oop l_7= 0;
static oop l_9= 0;
static oop l_11= 0;
static oop l_13= 0;
static oop l_15= 0;
static oop l_17= 0;
static oop v__object= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_Magnitude= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_SmallInteger= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_ByteArray= 0;
static oop v_String= 0;
static oop v_IdentitySet= 0;
static oop v_IdentityDictionary= 0;
static oop v_SlotDictionary= 0;
static oop v_StaticBlockClosure= 0;
static oop v_BlockClosure= 0;
static oop v_ReadStream= 0;
static oop v_FileStream= 0;
static oop v_nil= 0;
static oop v_true= 0;
static struct __methodinfo __info1= { "function_:arity_:", "StaticBlockClosure", "/Users/chazu/dev/c/idst-with-history/function/objects/BlockClosure.st", 0, 23, 30, 0 };
static oop StaticBlockClosure__function_5f_arity_5f_(oop v__closure, oop v_stateful_self, oop v_self, oop v__implementationAddress, oop v__argumentCount)
 {
  _enter(&__info1);
  oop _1= 0;
  _line(23);
 {
# define self ((struct t_StaticBlockClosure *)v_self)
 v_self= v_stateful_self= _libid->alloc(v_self, sizeof(*self)); 
# undef self
 }
  _1= 0;
  _1= v__argumentCount;
  ((struct t_StaticBlockClosure *)v_stateful_self)->v__arity= _1;
  _1= v__implementationAddress;
  ((struct t_StaticBlockClosure *)v_stateful_self)->v__function= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info2= { "arity", "StaticBlockClosure", "/Users/chazu/dev/c/idst-with-history/function/objects/BlockClosure.st", 0, 30, 32, &__info1 };
static oop StaticBlockClosure__arity(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info2);
  oop _1= 0;
  oop _2= 0;
  _line(30);
  _1= v_SmallInteger;
  _2= ((struct t_StaticBlockClosure *)v_stateful_self)->v__arity;
  _line(30);
  _1=_sendv(s_value_5f_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info3= { "errorArgumentCount:", "StaticBlockClosure", "/Users/chazu/dev/c/idst-with-history/function/objects/BlockClosure.st", 0, 32, 39, &__info2 };
static oop StaticBlockClosure__errorArgumentCount_(oop v__closure, oop v_stateful_self, oop v_self, oop v_given)
 {
  _enter(&__info3);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(32);
  _1= v_self;
  _2= l_4;
  _3= v_self;
  _line(34);
  _3=_sendv(s_arity, 1, _3);
  _line(34);
  _3=_sendv(s_printString, 1, _3);
  _line(34);
  _2=_sendv(s__2c, 2, _2, _3);
  _3= l_5;
  _line(34);
  _2=_sendv(s__2c, 2, _2, _3);
  _3= v_given;
  _line(34);
  _3=_sendv(s_printString, 1, _3);
  _line(34);
  _2=_sendv(s__2c, 2, _2, _3);
  _line(34);
  _1=_sendv(s_error_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info6= { "value", "StaticBlockClosure", "/Users/chazu/dev/c/idst-with-history/function/objects/BlockClosure.st", 0, 39, 45, &__info3 };
static oop StaticBlockClosure__value(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info6);
  oop _1= 0;
  oop _2= 0;
  _line(39);
 {
# define self ((struct t_StaticBlockClosure *)v_self)
 if ((long)self->v__arity == 0) { _return ((oop(*)())(self->v__function))(v__closure, v_self); } 
# undef self
 }
  _1= 0;
  _1= v_self;
  _2= l_7;
  _line(42);
  _1=_sendv(s_errorArgumentCount_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info8= { "value:", "StaticBlockClosure", "/Users/chazu/dev/c/idst-with-history/function/objects/BlockClosure.st", 0, 45, 51, &__info6 };
static oop StaticBlockClosure__value_(oop v__closure, oop v_stateful_self, oop v_self, oop v_a)
 {
  _enter(&__info8);
  oop _1= 0;
  oop _2= 0;
  _line(45);
 {
# define self ((struct t_StaticBlockClosure *)v_self)
 if ((long)self->v__arity == 1) { _return ((oop(*)())(self->v__function))(v__closure, v_self, v_a); } 
# undef self
 }
  _1= 0;
  _1= v_self;
  _2= l_9;
  _line(48);
  _1=_sendv(s_errorArgumentCount_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info10= { "value:value:", "StaticBlockClosure", "/Users/chazu/dev/c/idst-with-history/function/objects/BlockClosure.st", 0, 51, 57, &__info8 };
static oop StaticBlockClosure__value_value_(oop v__closure, oop v_stateful_self, oop v_self, oop v_a, oop v_b)
 {
  _enter(&__info10);
  oop _1= 0;
  oop _2= 0;
  _line(51);
 {
# define self ((struct t_StaticBlockClosure *)v_self)
 if ((long)self->v__arity == 2) { _return ((oop(*)())(self->v__function))(v__closure, v_self, v_a, v_b); } 
# undef self
 }
  _1= 0;
  _1= v_self;
  _2= l_11;
  _line(54);
  _1=_sendv(s_errorArgumentCount_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info12= { "value:value:value:", "StaticBlockClosure", "/Users/chazu/dev/c/idst-with-history/function/objects/BlockClosure.st", 0, 57, 63, &__info10 };
static oop StaticBlockClosure__value_value_value_(oop v__closure, oop v_stateful_self, oop v_self, oop v_a, oop v_b, oop v_c)
 {
  _enter(&__info12);
  oop _1= 0;
  oop _2= 0;
  _line(57);
 {
# define self ((struct t_StaticBlockClosure *)v_self)
 if ((long)self->v__arity == 3) { _return ((oop(*)())(self->v__function))(v__closure, v_self, v_a, v_b, v_c); } 
# undef self
 }
  _1= 0;
  _1= v_self;
  _2= l_13;
  _line(60);
  _1=_sendv(s_errorArgumentCount_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info14= { "value:value:value:value:", "StaticBlockClosure", "/Users/chazu/dev/c/idst-with-history/function/objects/BlockClosure.st", 0, 63, 69, &__info12 };
static oop StaticBlockClosure__value_value_value_value_(oop v__closure, oop v_stateful_self, oop v_self, oop v_a, oop v_b, oop v_c, oop v_d)
 {
  _enter(&__info14);
  oop _1= 0;
  oop _2= 0;
  _line(63);
 {
# define self ((struct t_StaticBlockClosure *)v_self)
 if ((long)self->v__arity == 4) { _return ((oop(*)())(self->v__function))(v__closure, v_self, v_a, v_b, v_c, v_d); } 
# undef self
 }
  _1= 0;
  _1= v_self;
  _2= l_15;
  _line(66);
  _1=_sendv(s_errorArgumentCount_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info16= { "value:value:value:value:value:", "StaticBlockClosure", "/Users/chazu/dev/c/idst-with-history/function/objects/BlockClosure.st", 0, 69, 77, &__info14 };
static oop StaticBlockClosure__value_value_value_value_value_(oop v__closure, oop v_stateful_self, oop v_self, oop v_a, oop v_b, oop v_c, oop v_d, oop v_e)
 {
  _enter(&__info16);
  oop _1= 0;
  oop _2= 0;
  _line(69);
 {
# define self ((struct t_StaticBlockClosure *)v_self)
 if ((long)self->v__arity == 5) { _return ((oop(*)())(self->v__function))(v__closure, v_self, v_a, v_b, v_c, v_d, v_e); } 
# undef self
 }
  _1= 0;
  _1= v_self;
  _2= l_17;
  _line(72);
  _1=_sendv(s_errorArgumentCount_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info18= { "whileTrue", "StaticBlockClosure", "/Users/chazu/dev/c/idst-with-history/function/objects/BlockClosure.st", 0, 77, 82, &__info16 };
static oop StaticBlockClosure__whileTrue(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info18);
  oop _1= 0;
  _line(77);
  /* whileTrue: */
  goto _l2;
 _l1:;
 {
  _1= v_nil;
 }
 _l2:;
 {
  _1= v_self;
  _line(79);
  _1=_sendv(s_value, 1, _1);
 }
  if (_1) goto _l1;
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info19= { "whileTrue:", "StaticBlockClosure", "/Users/chazu/dev/c/idst-with-history/function/objects/BlockClosure.st", 0, 82, 90, &__info18 };
static oop StaticBlockClosure__whileTrue_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aBlock)
 {
  _enter(&__info19);
  oop _1= 0;
  oop _2= 0;
  _line(82);
  /* ifTrue: */
  _1= 0;
  _2= v_self;
  _line(84);
  _2=_sendv(s_value, 1, _2);
  if (!_2) goto _l3;
 {
  _1= v_aBlock;
  _line(86);
  _1=_sendv(s_value, 1, _1);
  _1= v_self;
  _2= v_aBlock;
  _line(87);
  _1=_sendv(s_whileTrue_, 2, _1, _2);
 }
 _l3:;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info20= { "whileFalse", "StaticBlockClosure", "/Users/chazu/dev/c/idst-with-history/function/objects/BlockClosure.st", 0, 90, 95, &__info19 };
static oop StaticBlockClosure__whileFalse(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info20);
  oop _1= 0;
  _line(90);
  /* whileFalse: */
  goto _l5;
 _l4:;
 {
  _1= v_nil;
 }
 _l5:;
 {
  _1= v_self;
  _line(92);
  _1=_sendv(s_value, 1, _1);
 }
  if (!_1) goto _l4;
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info21= { "whileFalse:", "StaticBlockClosure", "/Users/chazu/dev/c/idst-with-history/function/objects/BlockClosure.st", 0, 95, 103, &__info20 };
static oop StaticBlockClosure__whileFalse_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aBlock)
 {
  _enter(&__info21);
  oop _1= 0;
  oop _2= 0;
  _line(95);
  /* ifFalse: */
  _1= 0;
  _2= v_self;
  _line(97);
  _2=_sendv(s_value, 1, _2);
  if (_2) goto _l6;
 {
  _1= v_aBlock;
  _line(99);
  _1=_sendv(s_value, 1, _1);
  _1= v_self;
  _2= v_aBlock;
  _line(100);
  _1=_sendv(s_whileFalse_, 2, _1, _2);
 }
 _l6:;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info22= { "repeat", "StaticBlockClosure", "/Users/chazu/dev/c/idst-with-history/function/objects/BlockClosure.st", 0, 103, 109, &__info21 };
static oop StaticBlockClosure__repeat(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info22);
  oop _1= 0;
  _line(103);
  /* whileTrue: */
  goto _l8;
 _l7:;
 {
  _1= v_self;
  _line(105);
  _1=_sendv(s_value, 1, _1);
 }
 _l8:;
 {
  _1= v_true;
 }
  if (_1) goto _l7;
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info23= { "function_:arity_:outer:state:nlr_:", "BlockClosure", "/Users/chazu/dev/c/idst-with-history/function/objects/BlockClosure.st", 0, 109, 122, &__info22 };
static oop BlockClosure__function_5f_arity_5f_outer_state_nlr_5f_(oop v__closure, oop v_stateful_self, oop v_self, oop v__implementationAddress, oop v__argumentCount, oop v_outerBlock, oop v_variableArray, oop v__dynamicEnvironment)
 {
  _enter(&__info23);
  oop _1= 0;
  _line(109);
 {
# define self ((struct t_BlockClosure *)v_self)
 v_self= v_stateful_self= _libid->alloc(v_self, sizeof(*self)); 
# undef self
 }
  _1= 0;
  _1= v__implementationAddress;
  ((struct t_BlockClosure *)v_stateful_self)->v__function= _1;
  _1= v__argumentCount;
  ((struct t_BlockClosure *)v_stateful_self)->v__arity= _1;
  _1= v_outerBlock;
  ((struct t_BlockClosure *)v_stateful_self)->v_outer= _1;
  _1= v_variableArray;
  ((struct t_BlockClosure *)v_stateful_self)->v_state= _1;
  _1= v__dynamicEnvironment;
  ((struct t_BlockClosure *)v_stateful_self)->v__nlr= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
#include "_profile.c"
static struct __methodinfo __info24= { "printExecutionProfile", "StaticBlockClosure", "/Users/chazu/dev/c/idst-with-history/function/objects/BlockClosure.st", 0, 124, 137, &__info23 };
static oop StaticBlockClosure__printExecutionProfile(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info24);
  oop v_result= 0;
  oop _1= 0;
  (void)v_result;
  _line(124);
 {
# define self ((struct t_StaticBlockClosure *)v_self)
 enableExecutionProfile(); 
# undef self
 }
  _1= 0;
  _1= v_self;
  _line(128);
  _1=_sendv(s_value, 1, _1);
  v_result= _1;
 {
# define self ((struct t_StaticBlockClosure *)v_self)

	disableExecutionProfile();
	printExecutionProfile();
	clearExecutionProfile();
	(void)setExecutionProfilePeriod;
    
# undef self
 }
  _1= 0;
  _1= v_result;
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "BlockClosure.st", 0, 0, 0, &__info24 };
void __id__init__BlockClosure(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
# define GC_add_roots _libid->gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info1);

  _sendv(s__5fimport_, 3, _libid->_object, "Objects", "__id__init__Objects");
  v__object= _libid->import("_object");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_Magnitude= _libid->import("Magnitude");
  v_Number= _libid->import("Number");
  v_Integer= _libid->import("Integer");
  v_SmallInteger= _libid->import("SmallInteger");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_ByteArray= _libid->import("ByteArray");
  v_String= _libid->import("String");
  v_IdentitySet= _libid->import("IdentitySet");
  v_IdentityDictionary= _libid->import("IdentityDictionary");
  v_SlotDictionary= _libid->import("SlotDictionary");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_BlockClosure= _libid->import("BlockClosure");
  v_ReadStream= _libid->import("ReadStream");
  v_FileStream= _libid->import("FileStream");
  v_nil= _libid->import("nil");
  v_true= _libid->import("true");
  _libid->method(v_StaticBlockClosure, s_function_5f_arity_5f_, (_imp_t)StaticBlockClosure__function_5f_arity_5f_);
  _libid->method(v_StaticBlockClosure, s_arity, (_imp_t)StaticBlockClosure__arity);
  l_4= _sendv(s_size_5f_value_5f_, 3, v_String, 22, "BlockClosure expected ");
  l_5= _sendv(s_size_5f_value_5f_, 3, v_String, 25, " arguments but was given ");
  _libid->method(v_StaticBlockClosure, s_errorArgumentCount_, (_imp_t)StaticBlockClosure__errorArgumentCount_);
  l_7= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  _libid->method(v_StaticBlockClosure, s_value, (_imp_t)StaticBlockClosure__value);
  l_9= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_StaticBlockClosure, s_value_, (_imp_t)StaticBlockClosure__value_);
  l_11= _sendv(s_value_5f_, 2, v_SmallInteger, 2);
  _libid->method(v_StaticBlockClosure, s_value_value_, (_imp_t)StaticBlockClosure__value_value_);
  l_13= _sendv(s_value_5f_, 2, v_SmallInteger, 3);
  _libid->method(v_StaticBlockClosure, s_value_value_value_, (_imp_t)StaticBlockClosure__value_value_value_);
  l_15= _sendv(s_value_5f_, 2, v_SmallInteger, 4);
  _libid->method(v_StaticBlockClosure, s_value_value_value_value_, (_imp_t)StaticBlockClosure__value_value_value_value_);
  l_17= _sendv(s_value_5f_, 2, v_SmallInteger, 5);
  _libid->method(v_StaticBlockClosure, s_value_value_value_value_value_, (_imp_t)StaticBlockClosure__value_value_value_value_value_);
  _libid->method(v_StaticBlockClosure, s_whileTrue, (_imp_t)StaticBlockClosure__whileTrue);
  _libid->method(v_StaticBlockClosure, s_whileTrue_, (_imp_t)StaticBlockClosure__whileTrue_);
  _libid->method(v_StaticBlockClosure, s_whileFalse, (_imp_t)StaticBlockClosure__whileFalse);
  _libid->method(v_StaticBlockClosure, s_whileFalse_, (_imp_t)StaticBlockClosure__whileFalse_);
  _libid->method(v_StaticBlockClosure, s_repeat, (_imp_t)StaticBlockClosure__repeat);
  _libid->method(v_BlockClosure, s_function_5f_arity_5f_outer_state_nlr_5f_, (_imp_t)BlockClosure__function_5f_arity_5f_outer_state_nlr_5f_);
  _libid->method(v_StaticBlockClosure, s_printExecutionProfile, (_imp_t)StaticBlockClosure__printExecutionProfile);
  _leave();
}
