/* generated by Id 1.1 at шкц */
/* with the command: -I../../object/stage2/ -I. -g -g -c IdentitySet.st -o IdentitySet.o.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s_at_put_= 0;
static oop s_deepen_at_= 0;
static oop s_do_= 0;
static oop s_value_5f_= 0;
static oop s__5fimport_= 0;
static oop s_widen= 0;
static oop s_new_= 0;
static oop s_remove_= 0;
static oop s_add_= 0;
static oop s__5fslots= 0;
static oop s_ifTrue_= 0;
static oop s_to_do_= 0;
static oop s__2a= 0;
static oop s_lists= 0;
static oop s_value= 0;
static oop s_new_5f_= 0;
static oop s_new= 0;
static oop s__2d= 0;
static oop s_compare_with_= 0;
static oop s_function_5f_arity_5f_outer_state_nlr_5f_= 0;
static oop s__2b= 0;
static oop s__3d_3d= 0;
static oop s_size= 0;
static oop s_remove_ifAbsent_= 0;
static oop s_errorNotFound_= 0;
static oop s_findElement_= 0;
static oop s_identityHash= 0;
static oop s_grow_at_= 0;
static oop s_replaceFrom_to_with_startingAt_= 0;
static oop s_notNil= 0;
static oop s_reverseDo_= 0;
static oop s_hashOf_= 0;
static oop s_addAll_= 0;
static oop s_value_= 0;
static oop s__5fdebugName= 0;
static oop s_isNil= 0;
static oop s__5c_5c= 0;
static oop s_includes_= 0;
static oop s__5fsizeof= 0;
static oop s_newList= 0;
static oop s_at_= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "at:put:", &s_at_put_ },
  { "deepen:at:", &s_deepen_at_ },
  { "do:", &s_do_ },
  { "value_:", &s_value_5f_ },
  { "_import:", &s__5fimport_ },
  { "widen", &s_widen },
  { "new:", &s_new_ },
  { "remove:", &s_remove_ },
  { "add:", &s_add_ },
  { "_slots", &s__5fslots },
  { "ifTrue:", &s_ifTrue_ },
  { "to:do:", &s_to_do_ },
  { "*", &s__2a },
  { "lists", &s_lists },
  { "value", &s_value },
  { "new_:", &s_new_5f_ },
  { "new", &s_new },
  { "-", &s__2d },
  { "compare:with:", &s_compare_with_ },
  { "function_:arity_:outer:state:nlr_:", &s_function_5f_arity_5f_outer_state_nlr_5f_ },
  { "+", &s__2b },
  { "==", &s__3d_3d },
  { "size", &s_size },
  { "remove:ifAbsent:", &s_remove_ifAbsent_ },
  { "errorNotFound:", &s_errorNotFound_ },
  { "findElement:", &s_findElement_ },
  { "identityHash", &s_identityHash },
  { "grow:at:", &s_grow_at_ },
  { "replaceFrom:to:with:startingAt:", &s_replaceFrom_to_with_startingAt_ },
  { "notNil", &s_notNil },
  { "reverseDo:", &s_reverseDo_ },
  { "hashOf:", &s_hashOf_ },
  { "addAll:", &s_addAll_ },
  { "value:", &s_value_ },
  { "_debugName", &s__5fdebugName },
  { "isNil", &s_isNil },
  { "\\\\", &s__5c_5c },
  { "includes:", &s_includes_ },
  { "_sizeof", &s__5fsizeof },
  { "newList", &s_newList },
  { "at:", &s_at_ },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Date {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__microseconds;
};
struct t_Time {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__nanoseconds;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargeInteger {
  struct _vtable *_vtable[0];
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t_Association {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t_Link {
  struct _vtable *_vtable[0];
  oop v_prevLink;
  oop v_nextLink;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_LinkedList {
  struct _vtable *_vtable[0];
  oop v_firstLink;
  oop v_lastLink;
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__oops;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_OrderedCollection {
  struct _vtable *_vtable[0];
  oop v_firstIndex;
  oop v_lastIndex;
  oop v_array;
};
struct t_IdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Set {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_IdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Dictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_FastIdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_SlotDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_MemoDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_ProfiledMethod {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_count;
  oop v_next;
};
struct t_SinkStream {
  struct _vtable *_vtable[0];
};
struct t_ReadStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_WriteStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_writeLimit;
};
struct t_FileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
};
struct t_ConsoleFileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
  oop v__prompt;
};
struct t_File {
  struct _vtable *_vtable[0];
  oop v__fd;
  oop v_name;
};
struct t_Function {
  struct _vtable *_vtable[0];
};
struct t_Random {
  struct _vtable *_vtable[0];
  oop v_seed;
  oop v_a;
  oop v_m;
  oop v_q;
  oop v_r;
};
struct t_OS {
  struct _vtable *_vtable[0];
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
static oop l_3= 0;
static oop l_5= 0;
static oop l_8= 0;
static oop l_9= 0;
static oop l_14= 0;
static oop l_15= 0;
static oop l_19= 0;
static oop l_22= 0;
static oop l_23= 0;
static oop l_28= 0;
static oop l_29= 0;
static oop l_31= 0;
static oop l_32= 0;
static oop l_33= 0;
struct t_FastIdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
static oop l_42= 0;
static oop v__object= 0;
static oop v__vector= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_Magnitude= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_SmallInteger= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_Array= 0;
static oop v_ByteArray= 0;
static oop v_IdentitySet= 0;
static oop v_IdentityDictionary= 0;
static oop v_SlotDictionary= 0;
static oop v_StaticBlockClosure= 0;
static oop v_BlockClosure= 0;
static oop v_ReadStream= 0;
static oop v_FileStream= 0;
static oop v_nil= 0;
static oop v_true= 0;
static oop v_false= 0;
static oop v_FastIdentitySet= 0;
static struct __methodinfo __info1= { "lists", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 25, 30, 0 };
static oop IdentitySet__lists(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info1);
  oop _1= 0;
  _line(25);
  _1= ((struct t_IdentitySet *)v_stateful_self)->v_lists;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info2= { "new", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 30, 35, &__info1 };
static oop IdentitySet__new(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info2);
  oop _1= 0;
  oop _2= 0;
  _line(30);
  _1= v_self;
  _2= l_3;
  _line(32);
  _1=_sendv(s_new_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info4= { "new:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 35, 42, &__info2 };
static oop IdentitySet__new_(oop v__closure, oop v_stateful_self, oop v_self, oop v_width)
 {
  _enter(&__info4);
  oop _1= 0;
  oop _2= 0;
  _line(35);
  _1= v_self;
  _line(37);
  _1=_superv(v_Collection, s_new, 1, _1);
  v_self= _1;
  v_stateful_self= _1;
  _1= l_5;
  ((struct t_IdentitySet *)v_stateful_self)->v_tally= _1;
  _1= v_Array;
  _2= v_width;
  _line(39);
  _1=_sendv(s_new_, 2, _1, _2);
  ((struct t_IdentitySet *)v_stateful_self)->v_lists= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info6= { "size", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 42, 44, &__info4 };
static oop IdentitySet__size(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info6);
  oop _1= 0;
  _line(42);
  _1= ((struct t_IdentitySet *)v_stateful_self)->v_tally;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info10= { "[] add:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 44, 69, &__info6 };
static oop b_10(oop v__closure, oop v__self, oop v_offset)
 {
  _enter(&__info10);
  oop v_elt= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  (void)v_elt;
  _line(54);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* list */
  _2= v_offset;
  _line(56);
  _1=_sendv(s_at_, 2, _1, _2);
  v_elt= _1;
  /* ifTrue: */
  _1= 0;
  _2= v_elt;
  _3= v_nil;
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l1;
 {
  _1= ((struct t_IdentitySet *)((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[3])->v_tally;  /* tally */
  _2= l_8;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  ((struct t_IdentitySet *)((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[3])->v_tally= _1;  /* tally */
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* list */
  _2= v_offset;
  _3= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[4];  /* anObject */
  _line(60);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _leave();
  return _libid->nlreturn(((struct t_BlockClosure *)v__self)->v__nlr, _1);
 }
 _l1:;
  /* ifTrue: */
  _1= 0;
  _2= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[2];  /* self */
  _3= v_elt;
  _4= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[4];  /* anObject */
  _line(61);
  _2=_sendv(s_compare_with_, 3, _2, _3, _4);
  if (!_2) goto _l2;
 {
  _1= v_elt;
  _leave();
  return _libid->nlreturn(((struct t_BlockClosure *)v__self)->v__nlr, _1);
 }
 _l2:;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info7= { "add:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 44, 69, &__info10 };
static oop IdentitySet__add_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anObject)
 {
  _enter(&__info7);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 7);
  oop v_listOffset= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  jmp_buf __nlr;
  oop _nlr;
  (void)v_listOffset;
  ((oop *)_state1)[3]= v_stateful_self;
  ((oop *)_state1)[2]= v_self;
  ((oop *)_state1)[4]= v_anObject;
  _nlr= (oop)&__nlr;
  if (setjmp(__nlr)) { return _libid->nlresult(); }
  _line(44);
  _1= ((oop *)_state1)[2];  /* self */
  _2= ((oop *)_state1)[4];  /* anObject */
  _line(47);
  _1=_sendv(s_hashOf_, 2, _1, _2);
  _2= ((struct t_IdentitySet *)((oop *)_state1)[3])->v_lists;  /* lists */
  _line(47);
  _2=_sendv(s_size, 1, _2);
  _1= _sendv(s__5c_5c, 2, _1, _2);
  v_listOffset= _1;
  _1= ((struct t_IdentitySet *)((oop *)_state1)[3])->v_lists;  /* lists */
  _2= v_listOffset;
  _line(48);
  _1=_sendv(s_at_, 2, _1, _2);
  ((oop *)_state1)[1]= _1;  /* list */
  /* ifTrue: */
  _1= 0;
  _2= ((oop *)_state1)[1];  /* list */
  _line(49);
  _2=_sendv(s_isNil, 1, _2);
  if (!_2) goto _l3;
 {
  _1= ((struct t_IdentitySet *)((oop *)_state1)[3])->v_lists;  /* lists */
  _2= v_listOffset;
  _3= ((oop *)_state1)[2];  /* self */
  _line(51);
  _3=_sendv(s_newList, 1, _3);
  _line(51);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  ((oop *)_state1)[1]= _1;  /* list */
  _1= ((struct t_IdentitySet *)((oop *)_state1)[3])->v_tally;  /* tally */
  _2= l_8;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  ((struct t_IdentitySet *)((oop *)_state1)[3])->v_tally= _1;  /* tally */
  _1= ((oop *)_state1)[1];  /* list */
  _2= l_9;
  _3= ((oop *)_state1)[4];  /* anObject */
  _line(53);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _leave();
  return _1;
 }
 _l3:;
  _1= l_9;
  _2= ((oop *)_state1)[1];  /* list */
  _line(54);
  _2=_sendv(s_size, 1, _2);
  _3= l_8;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2d, 2, _2, _3);
  }
  /* Scope('elt'->TemporaryVariableNode 'offset'->ArgumentVariableNode) */
  /* Scope('tally'->SlotVariableNode 'stateful_self'->ArgumentVariableNode 'listOffset'->TemporaryVariableNode 'self'->ArgumentVariableNode 'lists'->SlotVariableNode 'anObject'->ArgumentVariableNode 'list'->TemporaryVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_10, 1, 0, ((oop *)_state1), _nlr);
  _line(54);
  _1=_sendv(s_to_do_, 3, _1, _2, _3);
  _1= ((oop *)_state1)[2];  /* self */
  _2= ((oop *)_state1)[1];  /* list */
  _3= v_listOffset;
  _line(64);
  _sendv(s_grow_at_, 3, _1, _2, _3);
  _2= ((oop *)_state1)[4];  /* anObject */
  _1=_sendv(s_add_, 2, _1, _2);
  _1= ((oop *)_state1)[4];  /* anObject */
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info12= { "[] remove:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 69, 71, &__info7 };
static oop b_12(oop v__closure, oop v__self)
 {
  _enter(&__info12);
  oop _1= 0;
  oop _2= 0;
  _line(69);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* self */
  _2= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[3];  /* anObject */
  _line(69);
  _1=_sendv(s_errorNotFound_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info11= { "remove:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 69, 71, &__info12 };
static oop IdentitySet__remove_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anObject)
 {
  _enter(&__info11);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 6);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  ((oop *)_state1)[2]= v_stateful_self;
  ((oop *)_state1)[1]= v_self;
  ((oop *)_state1)[3]= v_anObject;
  _line(69);
  _1= ((oop *)_state1)[1];  /* self */
  _2= ((oop *)_state1)[3];  /* anObject */
  /* Scope() */
  /* Scope('self'->ArgumentVariableNode 'lists'->SlotVariableNode 'tally'->SlotVariableNode 'stateful_self'->ArgumentVariableNode 'anObject'->ArgumentVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_12, 0, 0, ((oop *)_state1), 0);
  _line(69);
  _1=_sendv(s_remove_ifAbsent_, 3, _1, _2, _3);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info17= { "[] remove:ifAbsent:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 71, 90, &__info11 };
static oop b_17(oop v__closure, oop v__self, oop v_index)
 {
  _enter(&__info17);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  oop _5= 0;
  _line(83);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_outer)->v_state))[1];  /* list */
  _2= v_index;
  _3= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_outer)->v_state))[1];  /* list */
  _4= v_index;
  _5= l_15;
  {
    int _l= (long)_4 >> 1;
    int _r= (long)_5 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_4) && ((_s ^ (_s << 1)) >= 0))  _4= (oop)(long)(_s << 1 | 1);  else _4= _sendv(s__2b, 2, _4, _5);
  }
  _line(83);
  _3=_sendv(s_at_, 2, _3, _4);
  _line(83);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info16= { "[] remove:ifAbsent:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 71, 90, &__info17 };
static oop b_16(oop v__closure, oop v__self, oop v_offset)
 {
  _enter(&__info16);
  oop v_elt= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  (void)v_elt;
  _line(77);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* list */
  _2= v_offset;
  _line(79);
  _1=_sendv(s_at_, 2, _1, _2);
  v_elt= _1;
  /* ifTrue: */
  _1= 0;
  _2= v_elt;
  _3= v_nil;
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l4;
 {
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[2];  /* errorBlock */
  _line(80);
  _1=_sendv(s_value, 1, _1);
  _leave();
  return _libid->nlreturn(((struct t_BlockClosure *)v__self)->v__nlr, _1);
 }
 _l4:;
  /* ifTrue: */
  _1= 0;
  _2= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[3];  /* self */
  _3= v_elt;
  _4= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[5];  /* anObject */
  _line(81);
  _2=_sendv(s_compare_with_, 3, _2, _3, _4);
  if (!_2) goto _l5;
 {
  _1= v_offset;
  _2= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[6];  /* listOffset */
  _3= l_15;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2d, 2, _2, _3);
  }
  /* Scope('index'->ArgumentVariableNode) */
  /* Scope('elt'->TemporaryVariableNode 'offset'->ArgumentVariableNode) */
  /* Object */
  /* 3 */
  /* 2 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_17, 1, v__self, 0, 0);
  _line(83);
  _1=_sendv(s_to_do_, 3, _1, _2, _3);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* list */
  _2= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[6];  /* listOffset */
  _3= v_nil;
  _line(84);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _1= ((struct t_IdentitySet *)((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[4])->v_tally;  /* tally */
  _2= l_15;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2d, 2, _1, _2);
  }
  ((struct t_IdentitySet *)((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[4])->v_tally= _1;  /* tally */
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[5];  /* anObject */
  _leave();
  return _libid->nlreturn(((struct t_BlockClosure *)v__self)->v__nlr, _1);
 }
 _l5:;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info13= { "remove:ifAbsent:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 71, 90, &__info16 };
static oop IdentitySet__remove_ifAbsent_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anObject, oop v_errorBlock)
 {
  _enter(&__info13);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 9);
  oop v_size= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  jmp_buf __nlr;
  oop _nlr;
  (void)v_size;
  ((oop *)_state1)[4]= v_stateful_self;
  ((oop *)_state1)[3]= v_self;
  ((oop *)_state1)[5]= v_anObject;
  ((oop *)_state1)[2]= v_errorBlock;
  _nlr= (oop)&__nlr;
  if (setjmp(__nlr)) { return _libid->nlresult(); }
  _line(71);
  _1= ((oop *)_state1)[3];  /* self */
  _2= ((oop *)_state1)[5];  /* anObject */
  _line(74);
  _1=_sendv(s_hashOf_, 2, _1, _2);
  _2= ((struct t_IdentitySet *)((oop *)_state1)[4])->v_lists;  /* lists */
  _line(74);
  _2=_sendv(s_size, 1, _2);
  _1= _sendv(s__5c_5c, 2, _1, _2);
  ((oop *)_state1)[6]= _1;  /* listOffset */
  _1= ((struct t_IdentitySet *)((oop *)_state1)[4])->v_lists;  /* lists */
  _2= ((oop *)_state1)[6];  /* listOffset */
  _line(75);
  _1=_sendv(s_at_, 2, _1, _2);
  ((oop *)_state1)[1]= _1;  /* list */
  /* ifTrue: */
  _1= 0;
  _2= ((oop *)_state1)[1];  /* list */
  _line(76);
  _2=_sendv(s_isNil, 1, _2);
  if (!_2) goto _l6;
 {
  _1= ((oop *)_state1)[2];  /* errorBlock */
  _line(76);
  _1=_sendv(s_value, 1, _1);
  _leave();
  return _1;
 }
 _l6:;
  _1= l_14;
  _2= ((oop *)_state1)[1];  /* list */
  _line(77);
  _2=_sendv(s_size, 1, _2);
  _3= l_15;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2d, 2, _2, _3);
  }
  ((oop *)_state1)[6]= _2;  /* listOffset */
  /* Scope('elt'->TemporaryVariableNode 'offset'->ArgumentVariableNode) */
  /* Scope('stateful_self'->ArgumentVariableNode 'tally'->SlotVariableNode 'size'->TemporaryVariableNode 'self'->ArgumentVariableNode 'listOffset'->TemporaryVariableNode 'lists'->SlotVariableNode 'errorBlock'->ArgumentVariableNode 'list'->TemporaryVariableNode 'anObject'->ArgumentVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_16, 1, 0, ((oop *)_state1), _nlr);
  _line(77);
  _1=_sendv(s_to_do_, 3, _1, _2, _3);
  _1= ((oop *)_state1)[2];  /* errorBlock */
  _line(87);
  _1=_sendv(s_value, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info18= { "newList", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 90, 92, &__info13 };
static oop IdentitySet__newList(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info18);
  oop _1= 0;
  oop _2= 0;
  _line(90);
  _1= v_Array;
  _2= l_19;
  _line(90);
  _1=_sendv(s_new_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info20= { "grow:at:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 92, 102, &__info18 };
static oop IdentitySet__grow_at_(oop v__closure, oop v_stateful_self, oop v_self, oop v_list, oop v_listOffset)
 {
  _enter(&__info20);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(92);
  _1= v_self;
  _2= v_list;
  _3= v_listOffset;
  _line(99);
  _1=_sendv(s_deepen_at_, 3, _1, _2, _3);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info24= { "[] findElement:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 102, 116, &__info20 };
static oop b_24(oop v__closure, oop v__self, oop v_offset)
 {
  _enter(&__info24);
  oop v_elt= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  (void)v_elt;
  _line(108);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* list */
  _2= v_offset;
  _line(110);
  _1=_sendv(s_at_, 2, _1, _2);
  v_elt= _1;
  /* ifTrue: */
  _1= 0;
  _2= v_elt;
  _3= v_nil;
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l7;
 {
  _1= v_nil;
  _leave();
  return _libid->nlreturn(((struct t_BlockClosure *)v__self)->v__nlr, _1);
 }
 _l7:;
  /* ifTrue: */
  _1= 0;
  _2= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[2];  /* self */
  _3= v_elt;
  _4= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[4];  /* anObject */
  _line(112);
  _2=_sendv(s_compare_with_, 3, _2, _3, _4);
  if (!_2) goto _l8;
 {
  _1= v_elt;
  _leave();
  return _libid->nlreturn(((struct t_BlockClosure *)v__self)->v__nlr, _1);
 }
 _l8:;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info21= { "findElement:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 102, 116, &__info24 };
static oop IdentitySet__findElement_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anObject)
 {
  _enter(&__info21);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 7);
  oop v_listOffset= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  jmp_buf __nlr;
  oop _nlr;
  (void)v_listOffset;
  ((oop *)_state1)[3]= v_stateful_self;
  ((oop *)_state1)[2]= v_self;
  ((oop *)_state1)[4]= v_anObject;
  _nlr= (oop)&__nlr;
  if (setjmp(__nlr)) { return _libid->nlresult(); }
  _line(102);
  _1= ((oop *)_state1)[2];  /* self */
  _2= ((oop *)_state1)[4];  /* anObject */
  _line(105);
  _1=_sendv(s_hashOf_, 2, _1, _2);
  _2= ((struct t_IdentitySet *)((oop *)_state1)[3])->v_lists;  /* lists */
  _line(105);
  _2=_sendv(s_size, 1, _2);
  _1= _sendv(s__5c_5c, 2, _1, _2);
  v_listOffset= _1;
  _1= ((struct t_IdentitySet *)((oop *)_state1)[3])->v_lists;  /* lists */
  _2= v_listOffset;
  _line(106);
  _1=_sendv(s_at_, 2, _1, _2);
  ((oop *)_state1)[1]= _1;  /* list */
  /* ifTrue: */
  _1= 0;
  _2= ((oop *)_state1)[1];  /* list */
  _line(107);
  _2=_sendv(s_isNil, 1, _2);
  if (!_2) goto _l9;
 {
  _1= v_nil;
  _leave();
  return _1;
 }
 _l9:;
  _1= l_22;
  _2= ((oop *)_state1)[1];  /* list */
  _line(108);
  _2=_sendv(s_size, 1, _2);
  _3= l_23;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2d, 2, _2, _3);
  }
  /* Scope('elt'->TemporaryVariableNode 'offset'->ArgumentVariableNode) */
  /* Scope('tally'->SlotVariableNode 'stateful_self'->ArgumentVariableNode 'listOffset'->TemporaryVariableNode 'self'->ArgumentVariableNode 'lists'->SlotVariableNode 'anObject'->ArgumentVariableNode 'list'->TemporaryVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_24, 1, 0, ((oop *)_state1), _nlr);
  _line(108);
  _1=_sendv(s_to_do_, 3, _1, _2, _3);
  _1= v_nil;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info25= { "hashOf:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 116, 117, &__info21 };
static oop IdentitySet__hashOf_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anObject)
 {
  _enter(&__info25);
  oop _1= 0;
  _line(116);
  _1= v_anObject;
  _line(116);
  _1=_sendv(s_identityHash, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info26= { "compare:with:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 117, 119, &__info25 };
static oop IdentitySet__compare_with_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anEntry, oop v_anObject)
 {
  _enter(&__info26);
  oop _1= 0;
  oop _2= 0;
  _line(117);
  _1= v_anEntry;
  _2= v_anObject;
  _1= (_1 == _2) ? v_true : v_false;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info27= { "widen", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 119, 125, &__info26 };
static oop IdentitySet__widen(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info27);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(119);
  _1= v_self;
  _2= ((struct t_IdentitySet *)v_stateful_self)->v_lists;
  _line(122);
  _2=_sendv(s_size, 1, _2);
  _3= l_28;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2b, 2, _2, _3);
  }
  _3= l_29;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= (_l * _r);
    if ((1 & (long)_2) && ((_r == 0) || (_s / _r == _l)) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2a, 2, _2, _3);
  }
  _3= l_28;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2d, 2, _2, _3);
  }
  _line(122);
  _1=_sendv(s_new_, 2, _1, _2);
  _2= v_self;
  _line(122);
  _sendv(s_addAll_, 2, _1, _2);
  _1=_sendv(s_lists, 1, _1);
  ((struct t_IdentitySet *)v_stateful_self)->v_lists= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info30= { "deepen:at:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 125, 134, &__info27 };
static oop IdentitySet__deepen_at_(oop v__closure, oop v_stateful_self, oop v_self, oop v_list, oop v_listOffset)
 {
  _enter(&__info30);
  oop v_newList= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  oop _5= 0;
  (void)v_newList;
  _line(125);
  _1= v_list;
  _2= v_list;
  _line(129);
  _2=_sendv(s_size, 1, _2);
  _3= l_31;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= (_l * _r);
    if ((1 & (long)_2) && ((_r == 0) || (_s / _r == _l)) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2a, 2, _2, _3);
  }
  _line(129);
  _1=_sendv(s_new_, 2, _1, _2);
  v_newList= _1;
  _1= v_newList;
  _2= l_32;
  _3= v_list;
  _line(130);
  _3=_sendv(s_size, 1, _3);
  _4= l_33;
  {
    int _l= (long)_3 >> 1;
    int _r= (long)_4 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_3) && ((_s ^ (_s << 1)) >= 0))  _3= (oop)(long)(_s << 1 | 1);  else _3= _sendv(s__2d, 2, _3, _4);
  }
  _4= v_list;
  _5= l_32;
  _line(130);
  _1=_sendv(s_replaceFrom_to_with_startingAt_, 5, _1, _2, _3, _4, _5);
  _1= ((struct t_IdentitySet *)v_stateful_self)->v_lists;
  _2= v_listOffset;
  _3= v_newList;
  _line(131);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info36= { "[] do:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 134, 139, &__info30 };
static oop b_36(oop v__closure, oop v__self, oop v_elt)
 {
  _enter(&__info36);
  oop _1= 0;
  oop _2= 0;
  _line(136);
  /* ifTrue: */
  _1= 0;
  _2= v_elt;
  _line(136);
  _2=_sendv(s_notNil, 1, _2);
  if (!_2) goto _l10;
 {
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_outer)->v_state))[1];  /* unaryBlock */
  _2= v_elt;
  _line(136);
  _1=_sendv(s_value_, 2, _1, _2);
 }
 _l10:;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info35= { "[] do:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 134, 139, &__info36 };
static oop b_35(oop v__closure, oop v__self, oop v_list)
 {
  _enter(&__info35);
  oop _1= 0;
  oop _2= 0;
  _line(136);
  /* ifTrue: */
  _1= 0;
  _2= v_list;
  _line(136);
  _2=_sendv(s_notNil, 1, _2);
  if (!_2) goto _l11;
 {
  _1= v_list;
  /* Scope('elt'->ArgumentVariableNode) */
  /* Scope('list'->ArgumentVariableNode) */
  /* Object */
  /* 3 */
  /* 2 */
  _2= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_36, 1, v__self, 0, 0);
  _line(136);
  _1=_sendv(s_do_, 2, _1, _2);
 }
 _l11:;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info34= { "do:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 134, 139, &__info35 };
static oop IdentitySet__do_(oop v__closure, oop v_stateful_self, oop v_self, oop v_unaryBlock)
 {
  _enter(&__info34);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 2);
  oop _1= 0;
  oop _2= 0;
  ((oop *)_state1)[1]= v_unaryBlock;
  _line(134);
  _1= ((struct t_IdentitySet *)v_stateful_self)->v_lists;
  /* Scope('list'->ArgumentVariableNode) */
  /* Scope('self'->ArgumentVariableNode 'lists'->SlotVariableNode 'tally'->SlotVariableNode 'stateful_self'->ArgumentVariableNode 'unaryBlock'->ArgumentVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _2= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_35, 1, 0, ((oop *)_state1), 0);
  _line(136);
  _1=_sendv(s_do_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info39= { "[] reverseDo:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 139, 144, &__info34 };
static oop b_39(oop v__closure, oop v__self, oop v_elt)
 {
  _enter(&__info39);
  oop _1= 0;
  oop _2= 0;
  _line(141);
  /* ifTrue: */
  _1= 0;
  _2= v_elt;
  _line(141);
  _2=_sendv(s_notNil, 1, _2);
  if (!_2) goto _l12;
 {
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_outer)->v_state))[1];  /* unaryBlock */
  _2= v_elt;
  _line(141);
  _1=_sendv(s_value_, 2, _1, _2);
 }
 _l12:;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info38= { "[] reverseDo:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 139, 144, &__info39 };
static oop b_38(oop v__closure, oop v__self, oop v_list)
 {
  _enter(&__info38);
  oop _1= 0;
  oop _2= 0;
  _line(141);
  /* ifTrue: */
  _1= 0;
  _2= v_list;
  _line(141);
  _2=_sendv(s_notNil, 1, _2);
  if (!_2) goto _l13;
 {
  _1= v_list;
  /* Scope('elt'->ArgumentVariableNode) */
  /* Scope('list'->ArgumentVariableNode) */
  /* Object */
  /* 3 */
  /* 2 */
  _2= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_39, 1, v__self, 0, 0);
  _line(141);
  _1=_sendv(s_reverseDo_, 2, _1, _2);
 }
 _l13:;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info37= { "reverseDo:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 139, 144, &__info38 };
static oop IdentitySet__reverseDo_(oop v__closure, oop v_stateful_self, oop v_self, oop v_unaryBlock)
 {
  _enter(&__info37);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 2);
  oop _1= 0;
  oop _2= 0;
  ((oop *)_state1)[1]= v_unaryBlock;
  _line(139);
  _1= ((struct t_IdentitySet *)v_stateful_self)->v_lists;
  /* Scope('list'->ArgumentVariableNode) */
  /* Scope('self'->ArgumentVariableNode 'lists'->SlotVariableNode 'tally'->SlotVariableNode 'stateful_self'->ArgumentVariableNode 'unaryBlock'->ArgumentVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _2= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_38, 1, 0, ((oop *)_state1), 0);
  _line(141);
  _1=_sendv(s_reverseDo_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info40= { "includes:", "IdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 144, 150, &__info37 };
static oop IdentitySet__includes_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anObject)
 {
  _enter(&__info40);
  oop _1= 0;
  oop _2= 0;
  _line(144);
  _1= v_self;
  _2= v_anObject;
  _line(146);
  _1=_sendv(s_findElement_, 2, _1, _2);
  _line(146);
  _1=_sendv(s_notNil, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static size_t FastIdentitySet___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_FastIdentitySet); }
static char *FastIdentitySet___5fdebugName(oop _closure, oop v_self) { return "FastIdentitySet"; }
static struct __slotinfo *FastIdentitySet___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "tally", 0, 4 }, { "lists", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static struct __methodinfo __info41= { "newList", "FastIdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 152, 154, &__info40 };
static oop FastIdentitySet__newList(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info41);
  oop _1= 0;
  oop _2= 0;
  _line(152);
  _1= v_Array;
  _2= l_42;
  _line(152);
  _1=_sendv(s_new_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info43= { "grow:at:", "FastIdentitySet", "/Users/chazu/dev/c/idst-with-history/function/objects/IdentitySet.st", 0, 154, 163, &__info41 };
static oop FastIdentitySet__grow_at_(oop v__closure, oop v_stateful_self, oop v_self, oop v_list, oop v_listOffset)
 {
  _enter(&__info43);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(154);
  _1= v_self;
  _2= v_list;
  _3= v_listOffset;
  _line(161);
  _1=_sendv(s_deepen_at_, 3, _1, _2, _3);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "IdentitySet.st", 0, 0, 0, &__info43 };
void __id__init__IdentitySet(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
# define GC_add_roots _libid->gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info1);

  _sendv(s__5fimport_, 3, _libid->_object, "Objects", "__id__init__Objects");
  v__object= _libid->import("_object");
  v__vector= _libid->import("_vector");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_Magnitude= _libid->import("Magnitude");
  v_Number= _libid->import("Number");
  v_Integer= _libid->import("Integer");
  v_SmallInteger= _libid->import("SmallInteger");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_Array= _libid->import("Array");
  v_ByteArray= _libid->import("ByteArray");
  v_IdentitySet= _libid->import("IdentitySet");
  v_IdentityDictionary= _libid->import("IdentityDictionary");
  v_SlotDictionary= _libid->import("SlotDictionary");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_BlockClosure= _libid->import("BlockClosure");
  v_ReadStream= _libid->import("ReadStream");
  v_FileStream= _libid->import("FileStream");
  v_nil= _libid->import("nil");
  v_true= _libid->import("true");
  v_false= _libid->import("false");
  _libid->method(v_IdentitySet, s_lists, (_imp_t)IdentitySet__lists);
  l_3= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_IdentitySet, s_new, (_imp_t)IdentitySet__new);
  l_5= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  _libid->method(v_IdentitySet, s_new_, (_imp_t)IdentitySet__new_);
  _libid->method(v_IdentitySet, s_size, (_imp_t)IdentitySet__size);
  l_8= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  l_9= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  _libid->method(v_IdentitySet, s_add_, (_imp_t)IdentitySet__add_);
  _libid->method(v_IdentitySet, s_remove_, (_imp_t)IdentitySet__remove_);
  l_14= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  l_15= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_IdentitySet, s_remove_ifAbsent_, (_imp_t)IdentitySet__remove_ifAbsent_);
  l_19= _sendv(s_value_5f_, 2, v_SmallInteger, 4);
  _libid->method(v_IdentitySet, s_newList, (_imp_t)IdentitySet__newList);
  _libid->method(v_IdentitySet, s_grow_at_, (_imp_t)IdentitySet__grow_at_);
  l_22= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  l_23= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_IdentitySet, s_findElement_, (_imp_t)IdentitySet__findElement_);
  _libid->method(v_IdentitySet, s_hashOf_, (_imp_t)IdentitySet__hashOf_);
  _libid->method(v_IdentitySet, s_compare_with_, (_imp_t)IdentitySet__compare_with_);
  l_28= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  l_29= _sendv(s_value_5f_, 2, v_SmallInteger, 2);
  _libid->method(v_IdentitySet, s_widen, (_imp_t)IdentitySet__widen);
  l_31= _sendv(s_value_5f_, 2, v_SmallInteger, 2);
  l_32= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  l_33= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_IdentitySet, s_deepen_at_, (_imp_t)IdentitySet__deepen_at_);
  _libid->method(v_IdentitySet, s_do_, (_imp_t)IdentitySet__do_);
  _libid->method(v_IdentitySet, s_reverseDo_, (_imp_t)IdentitySet__reverseDo_);
  _libid->method(v_IdentitySet, s_includes_, (_imp_t)IdentitySet__includes_);
  v_FastIdentitySet= _libid->proto2(v_IdentitySet, FastIdentitySet___5fsizeof(0, 0));
  _libid->method(v_FastIdentitySet, s__5fsizeof, (_imp_t)FastIdentitySet___5fsizeof);
  _libid->method(v_FastIdentitySet, s__5fdebugName, (_imp_t)FastIdentitySet___5fdebugName);
  _libid->method(v_FastIdentitySet, s__5fslots, (_imp_t)FastIdentitySet___5fslots);
  _libid->export("FastIdentitySet", v_FastIdentitySet);
  l_42= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_FastIdentitySet, s_newList, (_imp_t)FastIdentitySet__newList);
  _libid->method(v_FastIdentitySet, s_grow_at_, (_imp_t)FastIdentitySet__grow_at_);
  _leave();
}
