/* generated by Id 1.1 at èÚa */
/* with the command: -I../../object/stage2/ -I. -g -g -c Link.st -o Link.o.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s_reset= 0;
static oop s_prevLink= 0;
static oop s_unlink= 0;
static oop s_nextLink= 0;
static oop s__5fimport_= 0;
static oop s_unlinked= 0;
static oop s_prevLink_= 0;
static oop s_nextLink_= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "reset", &s_reset },
  { "prevLink", &s_prevLink },
  { "unlink", &s_unlink },
  { "nextLink", &s_nextLink },
  { "_import:", &s__5fimport_ },
  { "unlinked", &s_unlinked },
  { "prevLink:", &s_prevLink_ },
  { "nextLink:", &s_nextLink_ },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Date {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__microseconds;
};
struct t_Time {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__nanoseconds;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargeInteger {
  struct _vtable *_vtable[0];
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t_Association {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t_Link {
  struct _vtable *_vtable[0];
  oop v_prevLink;
  oop v_nextLink;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_LinkedList {
  struct _vtable *_vtable[0];
  oop v_firstLink;
  oop v_lastLink;
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__oops;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_OrderedCollection {
  struct _vtable *_vtable[0];
  oop v_firstIndex;
  oop v_lastIndex;
  oop v_array;
};
struct t_IdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Set {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_IdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Dictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_FastIdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_SlotDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_MemoDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_ProfiledMethod {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_count;
  oop v_next;
};
struct t_SinkStream {
  struct _vtable *_vtable[0];
};
struct t_ReadStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_WriteStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_writeLimit;
};
struct t_FileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
};
struct t_ConsoleFileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
  oop v__prompt;
};
struct t_File {
  struct _vtable *_vtable[0];
  oop v__fd;
  oop v_name;
};
struct t_Function {
  struct _vtable *_vtable[0];
};
struct t_Random {
  struct _vtable *_vtable[0];
  oop v_seed;
  oop v_a;
  oop v_m;
  oop v_q;
  oop v_r;
};
struct t_OS {
  struct _vtable *_vtable[0];
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
static oop v__object= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_Magnitude= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_Link= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_ByteArray= 0;
static oop v_IdentitySet= 0;
static oop v_IdentityDictionary= 0;
static oop v_SlotDictionary= 0;
static oop v_StaticBlockClosure= 0;
static oop v_ReadStream= 0;
static oop v_FileStream= 0;
static oop v_nil= 0;
static struct __methodinfo __info1= { "prevLink", "Link", "/Users/chazu/dev/c/idst-with-history/function/objects/Link.st", 0, 25, 26, 0 };
static oop Link__prevLink(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info1);
  oop _1= 0;
  _line(25);
  _1= ((struct t_Link *)v_stateful_self)->v_prevLink;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info2= { "prevLink:", "Link", "/Users/chazu/dev/c/idst-with-history/function/objects/Link.st", 0, 26, 27, &__info1 };
static oop Link__prevLink_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aLink)
 {
  _enter(&__info2);
  oop _1= 0;
  _line(26);
  _1= v_aLink;
  ((struct t_Link *)v_stateful_self)->v_prevLink= _1;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info3= { "nextLink", "Link", "/Users/chazu/dev/c/idst-with-history/function/objects/Link.st", 0, 27, 28, &__info2 };
static oop Link__nextLink(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info3);
  oop _1= 0;
  _line(27);
  _1= ((struct t_Link *)v_stateful_self)->v_nextLink;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info4= { "nextLink:", "Link", "/Users/chazu/dev/c/idst-with-history/function/objects/Link.st", 0, 28, 30, &__info3 };
static oop Link__nextLink_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aLink)
 {
  _enter(&__info4);
  oop _1= 0;
  _line(28);
  _1= v_aLink;
  ((struct t_Link *)v_stateful_self)->v_nextLink= _1;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info5= { "unlink", "Link", "/Users/chazu/dev/c/idst-with-history/function/objects/Link.st", 0, 30, 37, &__info4 };
static oop Link__unlink(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info5);
  oop _1= 0;
  oop _2= 0;
  _line(30);
  _1= ((struct t_Link *)v_stateful_self)->v_prevLink;
  _2= ((struct t_Link *)v_stateful_self)->v_nextLink;
  _line(32);
  _1=_sendv(s_nextLink_, 2, _1, _2);
  _1= ((struct t_Link *)v_stateful_self)->v_nextLink;
  _2= ((struct t_Link *)v_stateful_self)->v_prevLink;
  _line(33);
  _1=_sendv(s_prevLink_, 2, _1, _2);
  _1= v_nil;
  ((struct t_Link *)v_stateful_self)->v_nextLink= _1;
  ((struct t_Link *)v_stateful_self)->v_prevLink= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info6= { "unlinked", "Link", "/Users/chazu/dev/c/idst-with-history/function/objects/Link.st", 0, 37, 42, &__info5 };
static oop Link__unlinked(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info6);
  oop _1= 0;
  _line(37);
  _1= v_nil;
  ((struct t_Link *)v_stateful_self)->v_nextLink= _1;
  ((struct t_Link *)v_stateful_self)->v_prevLink= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info7= { "reset", "Link", "/Users/chazu/dev/c/idst-with-history/function/objects/Link.st", 0, 42, 46, &__info6 };
static oop Link__reset(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info7);
  oop _1= 0;
  _line(42);
  _1= v_nil;
  ((struct t_Link *)v_stateful_self)->v_nextLink= _1;
  ((struct t_Link *)v_stateful_self)->v_prevLink= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "Link.st", 0, 0, 0, &__info7 };
void __id__init__Link(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
# define GC_add_roots _libid->gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info1);

  _sendv(s__5fimport_, 3, _libid->_object, "Objects", "__id__init__Objects");
  v__object= _libid->import("_object");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_Magnitude= _libid->import("Magnitude");
  v_Number= _libid->import("Number");
  v_Integer= _libid->import("Integer");
  v_Link= _libid->import("Link");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_ByteArray= _libid->import("ByteArray");
  v_IdentitySet= _libid->import("IdentitySet");
  v_IdentityDictionary= _libid->import("IdentityDictionary");
  v_SlotDictionary= _libid->import("SlotDictionary");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_ReadStream= _libid->import("ReadStream");
  v_FileStream= _libid->import("FileStream");
  v_nil= _libid->import("nil");
  _libid->method(v_Link, s_prevLink, (_imp_t)Link__prevLink);
  _libid->method(v_Link, s_prevLink_, (_imp_t)Link__prevLink_);
  _libid->method(v_Link, s_nextLink, (_imp_t)Link__nextLink);
  _libid->method(v_Link, s_nextLink_, (_imp_t)Link__nextLink_);
  _libid->method(v_Link, s_unlink, (_imp_t)Link__unlink);
  _libid->method(v_Link, s_unlinked, (_imp_t)Link__unlinked);
  _libid->method(v_Link, s_reset, (_imp_t)Link__reset);
  _leave();
}
