/* generated by Id 1.1 at èšÜ */
/* with the command: -I../../object/stage2/ -I. -g -g -c LinkedList.st -o LinkedList.o.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s_reset= 0;
static oop s_do_= 0;
static oop s_notEmpty= 0;
static oop s_nextLink= 0;
static oop s_unlink= 0;
static oop s_collect_= 0;
static oop s_from_do_= 0;
static oop s__3e= 0;
static oop s_new_5f_= 0;
static oop s__2d= 0;
static oop s__7e_7e= 0;
static oop s__3d_3d= 0;
static oop s__2b= 0;
static oop s_reverseDo_= 0;
static oop s_select_= 0;
static oop s_whileTrue_= 0;
static oop s_value_= 0;
static oop s_isNil= 0;
static oop s_first= 0;
static oop s_at_= 0;
static oop s_add_after_= 0;
static oop s_addFirst_= 0;
static oop s_prevLink= 0;
static oop s_value_5f_= 0;
static oop s__5fimport_= 0;
static oop s_ifFalse_= 0;
static oop s_remove_= 0;
static oop s_add_= 0;
static oop s_ifTrue_= 0;
static oop s_and_= 0;
static oop s_unlinked= 0;
static oop s_last= 0;
static oop s_removeLast= 0;
static oop s_new= 0;
static oop s_add_before_= 0;
static oop s_size_5f_value_5f_= 0;
static oop s_removeFirst= 0;
static oop s_ifTrue_ifFalse_= 0;
static oop s_size= 0;
static oop s__3e_3d= 0;
static oop s_function_5f_arity_5f_outer_state_nlr_5f_= 0;
static oop s_prevLink_= 0;
static oop s_nextLink_= 0;
static oop s_addLast_= 0;
static oop s_notNil= 0;
static oop s_detect_= 0;
static oop s_inject_into_= 0;
static oop s_value_value_= 0;
static oop s_to_inject_into_= 0;
static oop s_upTo_inject_into_= 0;
static oop s_isEmpty= 0;
static oop s_error_= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "reset", &s_reset },
  { "do:", &s_do_ },
  { "notEmpty", &s_notEmpty },
  { "nextLink", &s_nextLink },
  { "unlink", &s_unlink },
  { "collect:", &s_collect_ },
  { "from:do:", &s_from_do_ },
  { ">", &s__3e },
  { "new_:", &s_new_5f_ },
  { "-", &s__2d },
  { "~~", &s__7e_7e },
  { "==", &s__3d_3d },
  { "+", &s__2b },
  { "reverseDo:", &s_reverseDo_ },
  { "select:", &s_select_ },
  { "whileTrue:", &s_whileTrue_ },
  { "value:", &s_value_ },
  { "isNil", &s_isNil },
  { "first", &s_first },
  { "at:", &s_at_ },
  { "add:after:", &s_add_after_ },
  { "addFirst:", &s_addFirst_ },
  { "prevLink", &s_prevLink },
  { "value_:", &s_value_5f_ },
  { "_import:", &s__5fimport_ },
  { "ifFalse:", &s_ifFalse_ },
  { "remove:", &s_remove_ },
  { "add:", &s_add_ },
  { "ifTrue:", &s_ifTrue_ },
  { "and:", &s_and_ },
  { "unlinked", &s_unlinked },
  { "last", &s_last },
  { "removeLast", &s_removeLast },
  { "new", &s_new },
  { "add:before:", &s_add_before_ },
  { "size_:value_:", &s_size_5f_value_5f_ },
  { "removeFirst", &s_removeFirst },
  { "ifTrue:ifFalse:", &s_ifTrue_ifFalse_ },
  { "size", &s_size },
  { ">=", &s__3e_3d },
  { "function_:arity_:outer:state:nlr_:", &s_function_5f_arity_5f_outer_state_nlr_5f_ },
  { "prevLink:", &s_prevLink_ },
  { "nextLink:", &s_nextLink_ },
  { "addLast:", &s_addLast_ },
  { "notNil", &s_notNil },
  { "detect:", &s_detect_ },
  { "inject:into:", &s_inject_into_ },
  { "value:value:", &s_value_value_ },
  { "to:inject:into:", &s_to_inject_into_ },
  { "upTo:inject:into:", &s_upTo_inject_into_ },
  { "isEmpty", &s_isEmpty },
  { "error:", &s_error_ },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Date {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__microseconds;
};
struct t_Time {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__nanoseconds;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargeInteger {
  struct _vtable *_vtable[0];
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t_Association {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t_Link {
  struct _vtable *_vtable[0];
  oop v_prevLink;
  oop v_nextLink;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_LinkedList {
  struct _vtable *_vtable[0];
  oop v_firstLink;
  oop v_lastLink;
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__oops;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_OrderedCollection {
  struct _vtable *_vtable[0];
  oop v_firstIndex;
  oop v_lastIndex;
  oop v_array;
};
struct t_IdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Set {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_IdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Dictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_FastIdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_SlotDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_MemoDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_ProfiledMethod {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_count;
  oop v_next;
};
struct t_SinkStream {
  struct _vtable *_vtable[0];
};
struct t_ReadStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_WriteStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_writeLimit;
};
struct t_FileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
};
struct t_ConsoleFileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
  oop v__prompt;
};
struct t_File {
  struct _vtable *_vtable[0];
  oop v__fd;
  oop v_name;
};
struct t_Function {
  struct _vtable *_vtable[0];
};
struct t_Random {
  struct _vtable *_vtable[0];
  oop v_seed;
  oop v_a;
  oop v_m;
  oop v_q;
  oop v_r;
};
struct t_OS {
  struct _vtable *_vtable[0];
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
static oop l_7= 0;
static oop l_9= 0;
static oop l_14= 0;
static oop l_15= 0;
static oop l_17= 0;
static oop l_18= 0;
static oop l_32= 0;
static oop l_33= 0;
static oop v__object= 0;
static oop v__vector= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_Magnitude= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_SmallInteger= 0;
static oop v_Link= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_LinkedList= 0;
static oop v_ArrayedCollection= 0;
static oop v_ByteArray= 0;
static oop v_String= 0;
static oop v_IdentitySet= 0;
static oop v_IdentityDictionary= 0;
static oop v_SlotDictionary= 0;
static oop v_StaticBlockClosure= 0;
static oop v_BlockClosure= 0;
static oop v_ReadStream= 0;
static oop v_FileStream= 0;
static oop v_nil= 0;
static oop v_true= 0;
static oop v_false= 0;
static struct __methodinfo __info1= { "first", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 25, 26, 0 };
static oop LinkedList__first(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info1);
  oop _1= 0;
  _line(25);
  _1= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info2= { "last", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 26, 28, &__info1 };
static oop LinkedList__last(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info2);
  oop _1= 0;
  _line(26);
  _1= ((struct t_LinkedList *)v_stateful_self)->v_lastLink;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info3= { "addFirst:", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 28, 38, &__info2 };
static oop LinkedList__addFirst_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aLink)
 {
  _enter(&__info3);
  oop _1= 0;
  oop _2= 0;
  _line(28);
  _1= v_aLink;
  _line(30);
  _1=_sendv(s_reset, 1, _1);
  /* ifTrue: */
  _1= 0;
  _2= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  _line(31);
  _2=_sendv(s_isNil, 1, _2);
  if (!_2) goto _l1;
 {
  _1= v_aLink;
  ((struct t_LinkedList *)v_stateful_self)->v_lastLink= _1;
  ((struct t_LinkedList *)v_stateful_self)->v_firstLink= _1;
  _leave();
  return _1;
 }
 _l1:;
  _1= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  _2= v_aLink;
  _line(32);
  _1=_sendv(s_prevLink_, 2, _1, _2);
  _1= v_aLink;
  _2= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  _line(33);
  _1=_sendv(s_nextLink_, 2, _1, _2);
  _1= v_aLink;
  ((struct t_LinkedList *)v_stateful_self)->v_firstLink= _1;
  _1= v_aLink;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info4= { "addLast:", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 38, 48, &__info3 };
static oop LinkedList__addLast_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aLink)
 {
  _enter(&__info4);
  oop _1= 0;
  oop _2= 0;
  _line(38);
  _1= v_aLink;
  _line(40);
  _1=_sendv(s_reset, 1, _1);
  /* ifTrue: */
  _1= 0;
  _2= ((struct t_LinkedList *)v_stateful_self)->v_lastLink;
  _line(41);
  _2=_sendv(s_isNil, 1, _2);
  if (!_2) goto _l2;
 {
  _1= v_aLink;
  ((struct t_LinkedList *)v_stateful_self)->v_lastLink= _1;
  ((struct t_LinkedList *)v_stateful_self)->v_firstLink= _1;
  _leave();
  return _1;
 }
 _l2:;
  _1= ((struct t_LinkedList *)v_stateful_self)->v_lastLink;
  _2= v_aLink;
  _line(42);
  _1=_sendv(s_nextLink_, 2, _1, _2);
  _1= v_aLink;
  _2= ((struct t_LinkedList *)v_stateful_self)->v_lastLink;
  _line(43);
  _1=_sendv(s_prevLink_, 2, _1, _2);
  _1= v_aLink;
  ((struct t_LinkedList *)v_stateful_self)->v_lastLink= _1;
  _1= v_aLink;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info5= { "add:", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 48, 53, &__info4 };
static oop LinkedList__add_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aLink)
 {
  _enter(&__info5);
  oop _1= 0;
  oop _2= 0;
  _line(48);
  _1= v_self;
  _2= v_aLink;
  _line(50);
  _1=_sendv(s_addLast_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info6= { "add:before:", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 53, 69, &__info5 };
static oop LinkedList__add_before_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aLink, oop v_anotherLink)
 {
  _enter(&__info6);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(53);
  _1= v_aLink;
  _line(55);
  _1=_sendv(s_reset, 1, _1);
  /* ifTrue: */
  _1= 0;
  _2= v_anotherLink;
  _3= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l3;
 {
  _1= v_aLink;
  _2= v_anotherLink;
  _line(58);
  _1=_sendv(s_nextLink_, 2, _1, _2);
  _1= v_anotherLink;
  _2= v_aLink;
  _line(59);
  _1=_sendv(s_prevLink_, 2, _1, _2);
  _1= v_aLink;
  ((struct t_LinkedList *)v_stateful_self)->v_firstLink= _1;
  _leave();
  return _1;
 }
 _l3:;
  /* ifFalse: */
  _1= 0;
  /* and: */
  _2= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  if (!_2) goto _l5;
 {
  _2= v_anotherLink;
  _line(61);
  _2=_sendv(s_prevLink, 1, _2);
 }
 _l5:;
  if (_2) goto _l4;
 {
  _1= v_self;
  _2= l_7;
  _line(61);
  _1=_sendv(s_error_, 2, _1, _2);
 }
 _l4:;
  _1= v_aLink;
  _2= v_anotherLink;
  _line(62);
  _2=_sendv(s_prevLink, 1, _2);
  _line(62);
  _1=_sendv(s_prevLink_, 2, _1, _2);
  _1= v_aLink;
  _2= v_anotherLink;
  _line(63);
  _1=_sendv(s_nextLink_, 2, _1, _2);
  _1= v_anotherLink;
  _line(64);
  _1=_sendv(s_prevLink, 1, _1);
  _2= v_aLink;
  _line(64);
  _1=_sendv(s_nextLink_, 2, _1, _2);
  _1= v_anotherLink;
  _2= v_aLink;
  _line(65);
  _1=_sendv(s_prevLink_, 2, _1, _2);
  _1= v_aLink;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info8= { "add:after:", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 69, 85, &__info6 };
static oop LinkedList__add_after_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aLink, oop v_anotherLink)
 {
  _enter(&__info8);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(69);
  _1= v_aLink;
  _line(71);
  _1=_sendv(s_reset, 1, _1);
  /* ifTrue: */
  _1= 0;
  _2= v_anotherLink;
  _3= ((struct t_LinkedList *)v_stateful_self)->v_lastLink;
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l6;
 {
  _1= v_aLink;
  _2= v_anotherLink;
  _line(74);
  _1=_sendv(s_prevLink_, 2, _1, _2);
  _1= v_anotherLink;
  _2= v_aLink;
  _line(75);
  _1=_sendv(s_nextLink_, 2, _1, _2);
  _1= v_aLink;
  ((struct t_LinkedList *)v_stateful_self)->v_lastLink= _1;
  _leave();
  return _1;
 }
 _l6:;
  /* ifFalse: */
  _1= 0;
  /* and: */
  _2= ((struct t_LinkedList *)v_stateful_self)->v_lastLink;
  if (!_2) goto _l8;
 {
  _2= v_anotherLink;
  _line(77);
  _2=_sendv(s_nextLink, 1, _2);
 }
 _l8:;
  if (_2) goto _l7;
 {
  _1= v_self;
  _2= l_9;
  _line(77);
  _1=_sendv(s_error_, 2, _1, _2);
 }
 _l7:;
  _1= v_aLink;
  _2= v_anotherLink;
  _line(78);
  _2=_sendv(s_nextLink, 1, _2);
  _line(78);
  _1=_sendv(s_nextLink_, 2, _1, _2);
  _1= v_aLink;
  _2= v_anotherLink;
  _line(79);
  _1=_sendv(s_prevLink_, 2, _1, _2);
  _1= v_anotherLink;
  _line(80);
  _1=_sendv(s_nextLink, 1, _1);
  _2= v_aLink;
  _line(80);
  _1=_sendv(s_prevLink_, 2, _1, _2);
  _1= v_anotherLink;
  _2= v_aLink;
  _line(81);
  _1=_sendv(s_nextLink_, 2, _1, _2);
  _1= v_aLink;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info10= { "remove:", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 85, 93, &__info8 };
static oop LinkedList__remove_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aLink)
 {
  _enter(&__info10);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(85);
  /* ifTrue: */
  _1= 0;
  _2= v_aLink;
  _3= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l9;
 {
  _1= v_self;
  _line(87);
  _1=_sendv(s_removeFirst, 1, _1);
  _leave();
  return _1;
 }
 _l9:;
  /* ifTrue: */
  _1= 0;
  _2= v_aLink;
  _3= ((struct t_LinkedList *)v_stateful_self)->v_lastLink;
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l10;
 {
  _1= v_self;
  _line(88);
  _1=_sendv(s_removeLast, 1, _1);
  _leave();
  return _1;
 }
 _l10:;
  _1= v_aLink;
  _line(89);
  _1=_sendv(s_unlink, 1, _1);
  _1= v_aLink;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info11= { "removeFirst", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 93, 103, &__info10 };
static oop LinkedList__removeFirst(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info11);
  oop v_aLink= 0;
  oop _1= 0;
  oop _2= 0;
  (void)v_aLink;
  _line(93);
  _1= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  v_aLink= _1;
  /* ifTrue:ifFalse: */
  _1= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  _line(97);
  _1=_sendv(s_nextLink, 1, _1);
  ((struct t_LinkedList *)v_stateful_self)->v_firstLink= _1;
  if (!_1) goto _l11;
 {
  _1= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  _2= v_nil;
  _line(98);
  _1=_sendv(s_prevLink_, 2, _1, _2);
 }
  goto _l12;
 _l11:;
 {
  _1= v_nil;
  ((struct t_LinkedList *)v_stateful_self)->v_lastLink= _1;
 }
 _l12:;
  _1= v_aLink;
  _line(100);
  _1=_sendv(s_unlinked, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info12= { "removeLast", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 103, 113, &__info11 };
static oop LinkedList__removeLast(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info12);
  oop v_aLink= 0;
  oop _1= 0;
  oop _2= 0;
  (void)v_aLink;
  _line(103);
  _1= ((struct t_LinkedList *)v_stateful_self)->v_lastLink;
  v_aLink= _1;
  /* ifTrue:ifFalse: */
  _1= ((struct t_LinkedList *)v_stateful_self)->v_lastLink;
  _line(107);
  _1=_sendv(s_prevLink, 1, _1);
  ((struct t_LinkedList *)v_stateful_self)->v_lastLink= _1;
  if (!_1) goto _l13;
 {
  _1= ((struct t_LinkedList *)v_stateful_self)->v_lastLink;
  _2= v_nil;
  _line(108);
  _1=_sendv(s_nextLink_, 2, _1, _2);
 }
  goto _l14;
 _l13:;
 {
  _1= v_nil;
  ((struct t_LinkedList *)v_stateful_self)->v_firstLink= _1;
 }
 _l14:;
  _1= v_aLink;
  _line(110);
  _1=_sendv(s_unlinked, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info13= { "size", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 113, 125, &__info12 };
static oop LinkedList__size(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info13);
  oop v_size= 0;
  oop v_link= 0;
  oop _1= 0;
  oop _2= 0;
  (void)v_size;
  (void)v_link;
  _line(113);
  _1= l_14;
  v_size= _1;
  _1= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  v_link= _1;
  /* whileTrue: */
  goto _l16;
 _l15:;
 {
  _1= v_link;
  _line(120);
  _1=_sendv(s_nextLink, 1, _1);
  v_link= _1;
  _1= v_size;
  _2= l_15;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  v_size= _1;
 }
 _l16:;
 {
  _1= v_link;
 }
  if (_1) goto _l15;
  _1= 0;
  _1= v_size;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info16= { "from:do:", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 125, 137, &__info13 };
static oop LinkedList__from_do_(oop v__closure, oop v_stateful_self, oop v_self, oop v_index, oop v_unaryBlock)
 {
  _enter(&__info16);
  oop v_link= 0;
  oop v_count= 0;
  oop _1= 0;
  oop _2= 0;
  (void)v_link;
  (void)v_count;
  _line(125);
  _1= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  v_link= _1;
  _1= v_index;
  v_count= _1;
  /* whileTrue: */
  goto _l18;
 _l17:;
 {
  _1= v_link;
  _line(130);
  _1=_sendv(s_nextLink, 1, _1);
  v_link= _1;
 }
 _l18:;
 {
  /* and: */
  _1= v_count;
  _2= l_17;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2d, 2, _1, _2);
  }
  v_count= _1;
  _2= l_18;
  if (1 & (long)_1) {
    _1= (((long)_1 >= (long)_2) ? v_true : v_false);
  } else _1= _sendv(s__3e_3d, 2, _1, _2);
  if (!_1) goto _l19;
 {
  _1= v_link;
 }
 _l19:;
 }
  if (_1) goto _l17;
  _1= 0;
  /* whileTrue: */
  goto _l21;
 _l20:;
 {
  _1= v_unaryBlock;
  _2= v_link;
  _line(133);
  _1=_sendv(s_value_, 2, _1, _2);
  _1= v_link;
  _line(134);
  _1=_sendv(s_nextLink, 1, _1);
  v_link= _1;
 }
 _l21:;
 {
  _1= v_link;
 }
  if (_1) goto _l20;
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info19= { "do:", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 137, 147, &__info16 };
static oop LinkedList__do_(oop v__closure, oop v_stateful_self, oop v_self, oop v_unaryBlock)
 {
  _enter(&__info19);
  oop v_link= 0;
  oop _1= 0;
  oop _2= 0;
  (void)v_link;
  _line(137);
  _1= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  v_link= _1;
  /* whileTrue: */
  goto _l23;
 _l22:;
 {
  _1= v_unaryBlock;
  _2= v_link;
  _line(143);
  _1=_sendv(s_value_, 2, _1, _2);
  _1= v_link;
  _line(144);
  _1=_sendv(s_nextLink, 1, _1);
  v_link= _1;
 }
 _l23:;
 {
  _1= v_link;
  _line(141);
  _1=_sendv(s_notNil, 1, _1);
 }
  if (_1) goto _l22;
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info20= { "reverseDo:", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 147, 157, &__info19 };
static oop LinkedList__reverseDo_(oop v__closure, oop v_stateful_self, oop v_self, oop v_unaryBlock)
 {
  _enter(&__info20);
  oop v_link= 0;
  oop _1= 0;
  oop _2= 0;
  (void)v_link;
  _line(147);
  _1= ((struct t_LinkedList *)v_stateful_self)->v_lastLink;
  v_link= _1;
  /* whileTrue: */
  goto _l25;
 _l24:;
 {
  _1= v_unaryBlock;
  _2= v_link;
  _line(153);
  _1=_sendv(s_value_, 2, _1, _2);
  _1= v_link;
  _line(154);
  _1=_sendv(s_prevLink, 1, _1);
  v_link= _1;
 }
 _l25:;
 {
  _1= v_link;
  _line(151);
  _1=_sendv(s_notNil, 1, _1);
 }
  if (_1) goto _l24;
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info22= { "[] collect:", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 157, 165, &__info20 };
static oop b_22(oop v__closure, oop v__self, oop v_elt)
 {
  _enter(&__info22);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(161);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* list */
  _2= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[2];  /* unaryBlock */
  _3= v_elt;
  _line(161);
  _2=_sendv(s_value_, 2, _2, _3);
  _line(161);
  _1=_sendv(s_add_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info21= { "collect:", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 157, 165, &__info22 };
static oop LinkedList__collect_(oop v__closure, oop v_stateful_self, oop v_self, oop v_unaryBlock)
 {
  _enter(&__info21);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 3);
  oop _1= 0;
  oop _2= 0;
  ((oop *)_state1)[2]= v_unaryBlock;
  _line(157);
  _1= v_self;
  _line(160);
  _1=_sendv(s_new, 1, _1);
  ((oop *)_state1)[1]= _1;  /* list */
  _1= v_self;
  /* Scope('elt'->ArgumentVariableNode) */
  /* Scope('firstLink'->SlotVariableNode 'lastLink'->SlotVariableNode 'self'->ArgumentVariableNode 'stateful_self'->ArgumentVariableNode 'list'->TemporaryVariableNode 'unaryBlock'->ArgumentVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _2= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_22, 1, 0, ((oop *)_state1), 0);
  _line(161);
  _1=_sendv(s_do_, 2, _1, _2);
  _1= ((oop *)_state1)[1];  /* list */
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info24= { "[] select:", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 165, 173, &__info21 };
static oop b_24(oop v__closure, oop v__self, oop v_elt)
 {
  _enter(&__info24);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(169);
  /* ifTrue: */
  _1= 0;
  _2= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* unaryBlock */
  _3= v_elt;
  _line(169);
  _2=_sendv(s_value_, 2, _2, _3);
  if (!_2) goto _l26;
 {
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[2];  /* list */
  _2= v_elt;
  _line(169);
  _1=_sendv(s_add_, 2, _1, _2);
 }
 _l26:;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info23= { "select:", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 165, 173, &__info24 };
static oop LinkedList__select_(oop v__closure, oop v_stateful_self, oop v_self, oop v_unaryBlock)
 {
  _enter(&__info23);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 3);
  oop _1= 0;
  oop _2= 0;
  ((oop *)_state1)[1]= v_unaryBlock;
  _line(165);
  _1= v_self;
  _line(168);
  _1=_sendv(s_new, 1, _1);
  ((oop *)_state1)[2]= _1;  /* list */
  _1= v_self;
  /* Scope('elt'->ArgumentVariableNode) */
  /* Scope('firstLink'->SlotVariableNode 'lastLink'->SlotVariableNode 'self'->ArgumentVariableNode 'stateful_self'->ArgumentVariableNode 'list'->TemporaryVariableNode 'unaryBlock'->ArgumentVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _2= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_24, 1, 0, ((oop *)_state1), 0);
  _line(169);
  _1=_sendv(s_do_, 2, _1, _2);
  _1= ((oop *)_state1)[2];  /* list */
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info25= { "detect:", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 173, 184, &__info23 };
static oop LinkedList__detect_(oop v__closure, oop v_stateful_self, oop v_self, oop v_unaryBlock)
 {
  _enter(&__info25);
  oop v_link= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  (void)v_link;
  _line(173);
  _1= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  v_link= _1;
  /* whileTrue: */
  goto _l28;
 _l27:;
 {
  /* ifTrue: */
  _1= 0;
  _2= v_unaryBlock;
  _3= v_link;
  _line(179);
  _2=_sendv(s_value_, 2, _2, _3);
  if (!_2) goto _l29;
 {
  _1= v_link;
  _leave();
  return _1;
 }
 _l29:;
  _1= v_link;
  _line(180);
  _1=_sendv(s_nextLink, 1, _1);
  v_link= _1;
 }
 _l28:;
 {
  _1= v_link;
  _line(177);
  _1=_sendv(s_notNil, 1, _1);
 }
  if (_1) goto _l27;
  _1= 0;
  _1= v_nil;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info26= { "inject:into:", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 184, 195, &__info25 };
static oop LinkedList__inject_into_(oop v__closure, oop v_stateful_self, oop v_self, oop v_answer, oop v_binaryBlock)
 {
  _enter(&__info26);
  oop v_link= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  (void)v_link;
  _line(184);
  _1= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  v_link= _1;
  /* whileTrue: */
  goto _l31;
 _l30:;
 {
  _1= v_binaryBlock;
  _2= v_answer;
  _3= v_link;
  _line(190);
  _1=_sendv(s_value_value_, 3, _1, _2, _3);
  v_answer= _1;
  _1= v_link;
  _line(191);
  _1=_sendv(s_nextLink, 1, _1);
  v_link= _1;
 }
 _l31:;
 {
  _1= v_link;
 }
  if (_1) goto _l30;
  _1= 0;
  _1= v_answer;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info27= { "to:inject:into:", "Link", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 195, 205, &__info26 };
static oop Link__to_inject_into_(oop v__closure, oop v_stateful_self, oop v_self, oop v_bLink, oop v_answer, oop v_binaryBlock)
 {
  _enter(&__info27);
  oop v_aLink= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  (void)v_aLink;
  _line(195);
  _1= v_self;
  v_aLink= _1;
  /* whileTrue: */
  goto _l33;
 _l32:;
 {
  _1= v_aLink;
  _line(201);
  _1=_sendv(s_nextLink, 1, _1);
  v_aLink= _1;
 }
 _l33:;
 {
  /* and: */
  _1= v_aLink;
  if (!_1) goto _l34;
 {
  _1= v_binaryBlock;
  _2= v_answer;
  _3= v_aLink;
  _line(199);
  _1=_sendv(s_value_value_, 3, _1, _2, _3);
  v_answer= _1;
  _1= v_aLink;
  _2= v_bLink;
  _1= (_1 != _2) ? v_true : v_false;
 }
 _l34:;
 }
  if (_1) goto _l32;
  _1= 0;
  _1= v_answer;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info28= { "upTo:inject:into:", "Link", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 205, 216, &__info27 };
static oop Link__upTo_inject_into_(oop v__closure, oop v_stateful_self, oop v_self, oop v_bLink, oop v_answer, oop v_binaryBlock)
 {
  _enter(&__info28);
  oop v_aLink= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  (void)v_aLink;
  _line(205);
  _1= v_self;
  v_aLink= _1;
  /* whileTrue: */
  goto _l36;
 _l35:;
 {
  _1= v_binaryBlock;
  _2= v_answer;
  _3= v_aLink;
  _line(211);
  _1=_sendv(s_value_value_, 3, _1, _2, _3);
  v_answer= _1;
  _1= v_aLink;
  _line(212);
  _1=_sendv(s_nextLink, 1, _1);
  v_aLink= _1;
 }
 _l36:;
 {
  /* and: */
  _1= v_aLink;
  if (!_1) goto _l37;
 {
  _1= v_aLink;
  _2= v_bLink;
  _1= (_1 != _2) ? v_true : v_false;
 }
 _l37:;
 }
  if (_1) goto _l35;
  _1= 0;
  _1= v_answer;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info29= { "isEmpty", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 216, 217, &__info28 };
static oop LinkedList__isEmpty(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info29);
  oop _1= 0;
  _line(216);
  _1= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  _line(216);
  _1=_sendv(s_isNil, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info30= { "notEmpty", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 217, 219, &__info29 };
static oop LinkedList__notEmpty(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info30);
  oop _1= 0;
  _line(217);
  _1= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info31= { "at:", "LinkedList", "/Users/chazu/dev/c/idst-with-history/function/objects/LinkedList.st", 0, 219, 229, &__info30 };
static oop LinkedList__at_(oop v__closure, oop v_stateful_self, oop v_self, oop v_index)
 {
  _enter(&__info31);
  oop v_link= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  (void)v_link;
  _line(219);
  /* ifTrue: */
  _1= 0;
  _2= v_index;
  _3= l_32;
  if (1 & (long)_2) {
    _2= (((long)_2 >= (long)_3) ? v_true : v_false);
  } else _2= _sendv(s__3e_3d, 2, _2, _3);
  if (!_2) goto _l38;
 {
  _1= ((struct t_LinkedList *)v_stateful_self)->v_firstLink;
  v_link= _1;
  /* whileTrue: */
  goto _l40;
 _l39:;
 {
  _1= v_link;
  _line(225);
  _1=_sendv(s_nextLink, 1, _1);
  v_link= _1;
 }
 _l40:;
 {
  /* and: */
  _1= v_link;
  if (!_1) goto _l41;
 {
  _1= v_index;
  _2= l_33;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2d, 2, _1, _2);
  }
  v_index= _1;
  _2= l_32;
  if (1 & (long)_1) {
    _1= (((long)_1 > (long)_2) ? v_true : v_false);
  } else _1= _sendv(s__3e, 2, _1, _2);
 }
 _l41:;
 }
  if (_1) goto _l39;
  _1= 0;
  _1= v_link;
  _leave();
  return _1;
 }
 _l38:;
  _1= v_self;
  _2= v_index;
  _line(227);
  _1=_superv(v_SequenceableCollection, s_at_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "LinkedList.st", 0, 0, 0, &__info31 };
void __id__init__LinkedList(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
# define GC_add_roots _libid->gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info1);

  _sendv(s__5fimport_, 3, _libid->_object, "Objects", "__id__init__Objects");
  v__object= _libid->import("_object");
  v__vector= _libid->import("_vector");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_Magnitude= _libid->import("Magnitude");
  v_Number= _libid->import("Number");
  v_Integer= _libid->import("Integer");
  v_SmallInteger= _libid->import("SmallInteger");
  v_Link= _libid->import("Link");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_LinkedList= _libid->import("LinkedList");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_ByteArray= _libid->import("ByteArray");
  v_String= _libid->import("String");
  v_IdentitySet= _libid->import("IdentitySet");
  v_IdentityDictionary= _libid->import("IdentityDictionary");
  v_SlotDictionary= _libid->import("SlotDictionary");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_BlockClosure= _libid->import("BlockClosure");
  v_ReadStream= _libid->import("ReadStream");
  v_FileStream= _libid->import("FileStream");
  v_nil= _libid->import("nil");
  v_true= _libid->import("true");
  v_false= _libid->import("false");
  _libid->method(v_LinkedList, s_first, (_imp_t)LinkedList__first);
  _libid->method(v_LinkedList, s_last, (_imp_t)LinkedList__last);
  _libid->method(v_LinkedList, s_addFirst_, (_imp_t)LinkedList__addFirst_);
  _libid->method(v_LinkedList, s_addLast_, (_imp_t)LinkedList__addLast_);
  _libid->method(v_LinkedList, s_add_, (_imp_t)LinkedList__add_);
  l_7= _sendv(s_size_5f_value_5f_, 3, v_String, 15, "cannot add link");
  _libid->method(v_LinkedList, s_add_before_, (_imp_t)LinkedList__add_before_);
  l_9= _sendv(s_size_5f_value_5f_, 3, v_String, 15, "cannot add link");
  _libid->method(v_LinkedList, s_add_after_, (_imp_t)LinkedList__add_after_);
  _libid->method(v_LinkedList, s_remove_, (_imp_t)LinkedList__remove_);
  _libid->method(v_LinkedList, s_removeFirst, (_imp_t)LinkedList__removeFirst);
  _libid->method(v_LinkedList, s_removeLast, (_imp_t)LinkedList__removeLast);
  l_14= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  l_15= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_LinkedList, s_size, (_imp_t)LinkedList__size);
  l_17= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  l_18= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  _libid->method(v_LinkedList, s_from_do_, (_imp_t)LinkedList__from_do_);
  _libid->method(v_LinkedList, s_do_, (_imp_t)LinkedList__do_);
  _libid->method(v_LinkedList, s_reverseDo_, (_imp_t)LinkedList__reverseDo_);
  _libid->method(v_LinkedList, s_collect_, (_imp_t)LinkedList__collect_);
  _libid->method(v_LinkedList, s_select_, (_imp_t)LinkedList__select_);
  _libid->method(v_LinkedList, s_detect_, (_imp_t)LinkedList__detect_);
  _libid->method(v_LinkedList, s_inject_into_, (_imp_t)LinkedList__inject_into_);
  _libid->method(v_Link, s_to_inject_into_, (_imp_t)Link__to_inject_into_);
  _libid->method(v_Link, s_upTo_inject_into_, (_imp_t)Link__upTo_inject_into_);
  _libid->method(v_LinkedList, s_isEmpty, (_imp_t)LinkedList__isEmpty);
  _libid->method(v_LinkedList, s_notEmpty, (_imp_t)LinkedList__notEmpty);
  l_32= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  l_33= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_LinkedList, s_at_, (_imp_t)LinkedList__at_);
  _leave();
}
