/* generated by Id 1.1 at è */
/* with the command: -I../../object/stage2/ -I. -g -g -c Magnitude.st -o Magnitude.o.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s__3d= 0;
static oop s__3c= 0;
static oop s_subtypeResponsibility_= 0;
static oop s_size_5f_value_5f_= 0;
static oop s__7e_3d= 0;
static oop s__5fimport_= 0;
static oop s_or_= 0;
static oop s_not= 0;
static oop s__3c_3d= 0;
static oop s__3e_3d= 0;
static oop s__3e= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "=", &s__3d },
  { "<", &s__3c },
  { "subtypeResponsibility:", &s_subtypeResponsibility_ },
  { "size_:value_:", &s_size_5f_value_5f_ },
  { "~=", &s__7e_3d },
  { "_import:", &s__5fimport_ },
  { "or:", &s_or_ },
  { "not", &s_not },
  { "<=", &s__3c_3d },
  { ">=", &s__3e_3d },
  { ">", &s__3e },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Date {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__microseconds;
};
struct t_Time {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__nanoseconds;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargeInteger {
  struct _vtable *_vtable[0];
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t_Association {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t_Link {
  struct _vtable *_vtable[0];
  oop v_prevLink;
  oop v_nextLink;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_LinkedList {
  struct _vtable *_vtable[0];
  oop v_firstLink;
  oop v_lastLink;
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__oops;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_OrderedCollection {
  struct _vtable *_vtable[0];
  oop v_firstIndex;
  oop v_lastIndex;
  oop v_array;
};
struct t_IdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Set {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_IdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Dictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_FastIdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_SlotDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_MemoDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_ProfiledMethod {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_count;
  oop v_next;
};
struct t_SinkStream {
  struct _vtable *_vtable[0];
};
struct t_ReadStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_WriteStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_writeLimit;
};
struct t_FileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
};
struct t_ConsoleFileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
  oop v__prompt;
};
struct t_File {
  struct _vtable *_vtable[0];
  oop v__fd;
  oop v_name;
};
struct t_Function {
  struct _vtable *_vtable[0];
};
struct t_Random {
  struct _vtable *_vtable[0];
  oop v_seed;
  oop v_a;
  oop v_m;
  oop v_q;
  oop v_r;
};
struct t_OS {
  struct _vtable *_vtable[0];
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
static oop l_2= 0;
static oop l_4= 0;
static oop v__object= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_Magnitude= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_Symbol= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_ByteArray= 0;
static oop v_IdentitySet= 0;
static oop v_IdentityDictionary= 0;
static oop v_SlotDictionary= 0;
static oop v_StaticBlockClosure= 0;
static oop v_ReadStream= 0;
static oop v_FileStream= 0;
static oop v_true= 0;
static oop v_false= 0;
static struct __methodinfo __info1= { "<", "Magnitude", "/Users/chazu/dev/c/idst-with-history/function/objects/Magnitude.st", 0, 3, 4, 0 };
static oop Magnitude___3c(oop v__closure, oop v_stateful_self, oop v_self, oop v_aMagnitude)
 {
  _enter(&__info1);
  oop _1= 0;
  oop _2= 0;
  _line(3);
  _1= v_self;
  _2= l_2;
  _line(3);
  _1=_sendv(s_subtypeResponsibility_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info3= { "=", "Magnitude", "/Users/chazu/dev/c/idst-with-history/function/objects/Magnitude.st", 0, 4, 6, &__info1 };
static oop Magnitude___3d(oop v__closure, oop v_stateful_self, oop v_self, oop v_aMagnitude)
 {
  _enter(&__info3);
  oop _1= 0;
  oop _2= 0;
  _line(4);
  _1= v_self;
  _2= l_4;
  _line(4);
  _1=_sendv(s_subtypeResponsibility_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info5= { "<=", "Magnitude", "/Users/chazu/dev/c/idst-with-history/function/objects/Magnitude.st", 0, 6, 7, &__info3 };
static oop Magnitude___3c_3d(oop v__closure, oop v_stateful_self, oop v_self, oop v_aMagnitude)
 {
  _enter(&__info5);
  oop _1= 0;
  oop _2= 0;
  _line(6);
  /* or: */
  _1= v_self;
  _2= v_aMagnitude;
  if (1 & (long)_1 & (long)_2) {
    _1= (((long)_1 < (long)_2) ? v_true : v_false);
  } else _1= _sendv(s__3c, 2, _1, _2);
  if (_1) goto _l1;
 {
  _1= v_self;
  _2= v_aMagnitude;
  if (1 & (long)_1 & (long)_2) {
    _1= (((long)_1 == (long)_2) ? v_true : v_false);
  } else _1= _sendv(s__3d, 2, _1, _2);
 }
 _l1:;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info6= { "~=", "Magnitude", "/Users/chazu/dev/c/idst-with-history/function/objects/Magnitude.st", 0, 7, 8, &__info5 };
static oop Magnitude___7e_3d(oop v__closure, oop v_stateful_self, oop v_self, oop v_aMagnitude)
 {
  _enter(&__info6);
  oop _1= 0;
  oop _2= 0;
  _line(7);
  _1= v_self;
  _2= v_aMagnitude;
  if (1 & (long)_1 & (long)_2) {
    _1= (((long)_1 == (long)_2) ? v_true : v_false);
  } else _1= _sendv(s__3d, 2, _1, _2);
  _line(7);
  _1=_sendv(s_not, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info7= { ">=", "Magnitude", "/Users/chazu/dev/c/idst-with-history/function/objects/Magnitude.st", 0, 8, 9, &__info6 };
static oop Magnitude___3e_3d(oop v__closure, oop v_stateful_self, oop v_self, oop v_aMagnitude)
 {
  _enter(&__info7);
  oop _1= 0;
  oop _2= 0;
  _line(8);
  _1= v_self;
  _2= v_aMagnitude;
  if (1 & (long)_1 & (long)_2) {
    _1= (((long)_1 < (long)_2) ? v_true : v_false);
  } else _1= _sendv(s__3c, 2, _1, _2);
  _line(8);
  _1=_sendv(s_not, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info8= { ">", "Magnitude", "/Users/chazu/dev/c/idst-with-history/function/objects/Magnitude.st", 0, 9, 10, &__info7 };
static oop Magnitude___3e(oop v__closure, oop v_stateful_self, oop v_self, oop v_aMagnitude)
 {
  _enter(&__info8);
  oop _1= 0;
  oop _2= 0;
  _line(9);
  _1= v_aMagnitude;
  _2= v_self;
  if (1 & (long)_1 & (long)_2) {
    _1= (((long)_1 < (long)_2) ? v_true : v_false);
  } else _1= _sendv(s__3c, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "Magnitude.st", 0, 0, 0, &__info8 };
void __id__init__Magnitude(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
# define GC_add_roots _libid->gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info1);

  _sendv(s__5fimport_, 3, _libid->_object, "Objects", "__id__init__Objects");
  v__object= _libid->import("_object");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_Magnitude= _libid->import("Magnitude");
  v_Number= _libid->import("Number");
  v_Integer= _libid->import("Integer");
  v_Symbol= _libid->import("Symbol");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_ByteArray= _libid->import("ByteArray");
  v_IdentitySet= _libid->import("IdentitySet");
  v_IdentityDictionary= _libid->import("IdentityDictionary");
  v_SlotDictionary= _libid->import("SlotDictionary");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_ReadStream= _libid->import("ReadStream");
  v_FileStream= _libid->import("FileStream");
  v_true= _libid->import("true");
  v_false= _libid->import("false");
  l_2= _sendv(s_size_5f_value_5f_, 3, v_Symbol, 1, "<");
  _libid->method(v_Magnitude, s__3c, (_imp_t)Magnitude___3c);
  l_4= _sendv(s_size_5f_value_5f_, 3, v_Symbol, 1, "=");
  _libid->method(v_Magnitude, s__3d, (_imp_t)Magnitude___3d);
  _libid->method(v_Magnitude, s__3c_3d, (_imp_t)Magnitude___3c_3d);
  _libid->method(v_Magnitude, s__7e_3d, (_imp_t)Magnitude___7e_3d);
  _libid->method(v_Magnitude, s__3e_3d, (_imp_t)Magnitude___3e_3d);
  _libid->method(v_Magnitude, s__3e, (_imp_t)Magnitude___3e);
  _leave();
}
