/* generated by Id 1.1 at шк */
/* with the command: -I../../object/stage2/ -I. -g -g -c Objects.st -o Objects.o.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s__5fimport_= 0;
static oop s__5fslots= 0;
static oop s__5fsizeof= 0;
static oop s__5fdebugName= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "_import:", &s__5fimport_ },
  { "_slots", &s__5fslots },
  { "_sizeof", &s__5fsizeof },
  { "_debugName", &s__5fdebugName },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Date {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__microseconds;
};
struct t_Time {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__nanoseconds;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargeInteger {
  struct _vtable *_vtable[0];
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t_Association {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t_Link {
  struct _vtable *_vtable[0];
  oop v_prevLink;
  oop v_nextLink;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_LinkedList {
  struct _vtable *_vtable[0];
  oop v_firstLink;
  oop v_lastLink;
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__oops;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_OrderedCollection {
  struct _vtable *_vtable[0];
  oop v_firstIndex;
  oop v_lastIndex;
  oop v_array;
};
struct t_IdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Set {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_IdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Dictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_FastIdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_SlotDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_MemoDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_ProfiledMethod {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_count;
  oop v_next;
};
struct t_SinkStream {
  struct _vtable *_vtable[0];
};
struct t_ReadStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_WriteStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_writeLimit;
};
struct t_FileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
};
struct t_ConsoleFileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
  oop v__prompt;
};
struct t_File {
  struct _vtable *_vtable[0];
  oop v__fd;
  oop v_name;
};
struct t_Function {
  struct _vtable *_vtable[0];
};
struct t_Random {
  struct _vtable *_vtable[0];
  oop v_seed;
  oop v_a;
  oop v_m;
  oop v_q;
  oop v_r;
};
struct t_OS {
  struct _vtable *_vtable[0];
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
static oop v__object= 0;
static oop v__selector= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_Magnitude= 0;
static oop v_Date= 0;
static oop v_Time= 0;
static oop v_Number= 0;
static oop v_Float= 0;
static oop v_Integer= 0;
static oop v_SmallInteger= 0;
static oop v_LargeInteger= 0;
static oop v_Symbol= 0;
static oop v_Association= 0;
static oop v_Link= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_LinkedList= 0;
static oop v_ArrayedCollection= 0;
static oop v_Array= 0;
static oop v_ByteArray= 0;
static oop v_String= 0;
static oop v_OrderedCollection= 0;
static oop v_IdentitySet= 0;
static oop v_Set= 0;
static oop v_IdentityDictionary= 0;
static oop v_Dictionary= 0;
static oop v_FastIdentityDictionary= 0;
static oop v_SlotDictionary= 0;
static oop v_MemoDictionary= 0;
static oop v_StaticBlockClosure= 0;
static oop v_BlockClosure= 0;
static oop v_ProfiledMethod= 0;
static oop v_SinkStream= 0;
static oop v_ReadStream= 0;
static oop v_WriteStream= 0;
static oop v_FileStream= 0;
static oop v_ConsoleFileStream= 0;
static oop v_File= 0;
static oop v_Function= 0;
static oop v_Random= 0;
static oop v_OS= 0;
static oop v_nil= 0;
static oop v_true= 0;
static oop v_false= 0;
static oop v_StdIn= 0;
static oop v_StdOut= 0;
static oop v_StdErr= 0;
static size_t Object___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_Object); }
static char *Object___5fdebugName(oop _closure, oop v_self) { return "Object"; }
static struct __slotinfo *Object___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { 0, 0, 0 } };  return &info[0]; }
static size_t UndefinedObject___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_UndefinedObject); }
static char *UndefinedObject___5fdebugName(oop _closure, oop v_self) { return "UndefinedObject"; }
static struct __slotinfo *UndefinedObject___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { 0, 0, 0 } };  return &info[0]; }
static size_t Magnitude___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_Magnitude); }
static char *Magnitude___5fdebugName(oop _closure, oop v_self) { return "Magnitude"; }
static struct __slotinfo *Magnitude___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { 0, 0, 0 } };  return &info[0]; }
static size_t Date___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_Date); }
static char *Date___5fdebugName(oop _closure, oop v_self) { return "Date"; }
static struct __slotinfo *Date___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "_seconds", 0, 4 }, { "_microseconds", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t Time___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_Time); }
static char *Time___5fdebugName(oop _closure, oop v_self) { return "Time"; }
static struct __slotinfo *Time___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "_seconds", 0, 4 }, { "_nanoseconds", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t Number___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_Number); }
static char *Number___5fdebugName(oop _closure, oop v_self) { return "Number"; }
static struct __slotinfo *Number___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { 0, 0, 0 } };  return &info[0]; }
static size_t Float___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_Float); }
static char *Float___5fdebugName(oop _closure, oop v_self) { return "Float"; }
static struct __slotinfo *Float___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { 0, 0, 0 } };  return &info[0]; }
static size_t Integer___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_Integer); }
static char *Integer___5fdebugName(oop _closure, oop v_self) { return "Integer"; }
static struct __slotinfo *Integer___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { 0, 0, 0 } };  return &info[0]; }
static size_t SmallInteger___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_SmallInteger); }
static char *SmallInteger___5fdebugName(oop _closure, oop v_self) { return "SmallInteger"; }
static struct __slotinfo *SmallInteger___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { 0, 0, 0 } };  return &info[0]; }
static size_t LargeInteger___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_LargeInteger); }
static char *LargeInteger___5fdebugName(oop _closure, oop v_self) { return "LargeInteger"; }
static struct __slotinfo *LargeInteger___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { 0, 0, 0 } };  return &info[0]; }
static size_t Symbol___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_Symbol); }
static char *Symbol___5fdebugName(oop _closure, oop v_self) { return "Symbol"; }
static struct __slotinfo *Symbol___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "_size", 0, 4 }, { "_elements", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t Association___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_Association); }
static char *Association___5fdebugName(oop _closure, oop v_self) { return "Association"; }
static struct __slotinfo *Association___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "key", 0, 4 }, { "value", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t Link___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_Link); }
static char *Link___5fdebugName(oop _closure, oop v_self) { return "Link"; }
static struct __slotinfo *Link___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "prevLink", 0, 4 }, { "nextLink", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t Collection___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_Collection); }
static char *Collection___5fdebugName(oop _closure, oop v_self) { return "Collection"; }
static struct __slotinfo *Collection___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { 0, 0, 0 } };  return &info[0]; }
static size_t SequenceableCollection___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_SequenceableCollection); }
static char *SequenceableCollection___5fdebugName(oop _closure, oop v_self) { return "SequenceableCollection"; }
static struct __slotinfo *SequenceableCollection___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { 0, 0, 0 } };  return &info[0]; }
static size_t LinkedList___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_LinkedList); }
static char *LinkedList___5fdebugName(oop _closure, oop v_self) { return "LinkedList"; }
static struct __slotinfo *LinkedList___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "firstLink", 0, 4 }, { "lastLink", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t ArrayedCollection___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_ArrayedCollection); }
static char *ArrayedCollection___5fdebugName(oop _closure, oop v_self) { return "ArrayedCollection"; }
static struct __slotinfo *ArrayedCollection___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "size", 0, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t Array___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_Array); }
static char *Array___5fdebugName(oop _closure, oop v_self) { return "Array"; }
static struct __slotinfo *Array___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "size", 0, 4 }, { "_oops", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t ByteArray___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_ByteArray); }
static char *ByteArray___5fdebugName(oop _closure, oop v_self) { return "ByteArray"; }
static struct __slotinfo *ByteArray___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "size", 0, 4 }, { "_bytes", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t String___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_String); }
static char *String___5fdebugName(oop _closure, oop v_self) { return "String"; }
static struct __slotinfo *String___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "size", 0, 4 }, { "_bytes", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t OrderedCollection___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_OrderedCollection); }
static char *OrderedCollection___5fdebugName(oop _closure, oop v_self) { return "OrderedCollection"; }
static struct __slotinfo *OrderedCollection___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "firstIndex", 0, 4 }, { "lastIndex", 4, 4 }, { "array", 8, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t IdentitySet___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_IdentitySet); }
static char *IdentitySet___5fdebugName(oop _closure, oop v_self) { return "IdentitySet"; }
static struct __slotinfo *IdentitySet___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "tally", 0, 4 }, { "lists", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t Set___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_Set); }
static char *Set___5fdebugName(oop _closure, oop v_self) { return "Set"; }
static struct __slotinfo *Set___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "tally", 0, 4 }, { "lists", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t IdentityDictionary___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_IdentityDictionary); }
static char *IdentityDictionary___5fdebugName(oop _closure, oop v_self) { return "IdentityDictionary"; }
static struct __slotinfo *IdentityDictionary___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "tally", 0, 4 }, { "lists", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t Dictionary___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_Dictionary); }
static char *Dictionary___5fdebugName(oop _closure, oop v_self) { return "Dictionary"; }
static struct __slotinfo *Dictionary___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "tally", 0, 4 }, { "lists", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t FastIdentityDictionary___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_FastIdentityDictionary); }
static char *FastIdentityDictionary___5fdebugName(oop _closure, oop v_self) { return "FastIdentityDictionary"; }
static struct __slotinfo *FastIdentityDictionary___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "tally", 0, 4 }, { "lists", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t SlotDictionary___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_SlotDictionary); }
static char *SlotDictionary___5fdebugName(oop _closure, oop v_self) { return "SlotDictionary"; }
static struct __slotinfo *SlotDictionary___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "_size", 0, 4 }, { "_tally", 4, 4 }, { "_keys", 8, 4 }, { "_values", 12, 4 }, { "default", 16, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t MemoDictionary___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_MemoDictionary); }
static char *MemoDictionary___5fdebugName(oop _closure, oop v_self) { return "MemoDictionary"; }
static struct __slotinfo *MemoDictionary___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "_size", 0, 4 }, { "_tally", 4, 4 }, { "_keys", 8, 4 }, { "_values", 12, 4 }, { "default", 16, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t StaticBlockClosure___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_StaticBlockClosure); }
static char *StaticBlockClosure___5fdebugName(oop _closure, oop v_self) { return "StaticBlockClosure"; }
static struct __slotinfo *StaticBlockClosure___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "_function", 0, 4 }, { "_arity", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t BlockClosure___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_BlockClosure); }
static char *BlockClosure___5fdebugName(oop _closure, oop v_self) { return "BlockClosure"; }
static struct __slotinfo *BlockClosure___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "_function", 0, 4 }, { "_arity", 4, 4 }, { "outer", 8, 4 }, { "state", 12, 4 }, { "_nlr", 16, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t ProfiledMethod___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_ProfiledMethod); }
static char *ProfiledMethod___5fdebugName(oop _closure, oop v_self) { return "ProfiledMethod"; }
static struct __slotinfo *ProfiledMethod___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "_method", 0, 4 }, { "count", 4, 4 }, { "next", 8, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t SinkStream___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_SinkStream); }
static char *SinkStream___5fdebugName(oop _closure, oop v_self) { return "SinkStream"; }
static struct __slotinfo *SinkStream___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { 0, 0, 0 } };  return &info[0]; }
static size_t ReadStream___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_ReadStream); }
static char *ReadStream___5fdebugName(oop _closure, oop v_self) { return "ReadStream"; }
static struct __slotinfo *ReadStream___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "collection", 0, 4 }, { "position", 4, 4 }, { "readLimit", 8, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t WriteStream___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_WriteStream); }
static char *WriteStream___5fdebugName(oop _closure, oop v_self) { return "WriteStream"; }
static struct __slotinfo *WriteStream___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "collection", 0, 4 }, { "position", 4, 4 }, { "readLimit", 8, 4 }, { "writeLimit", 12, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t FileStream___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_FileStream); }
static char *FileStream___5fdebugName(oop _closure, oop v_self) { return "FileStream"; }
static struct __slotinfo *FileStream___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "collection", 0, 4 }, { "position", 4, 4 }, { "readLimit", 8, 4 }, { "file", 12, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t ConsoleFileStream___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_ConsoleFileStream); }
static char *ConsoleFileStream___5fdebugName(oop _closure, oop v_self) { return "ConsoleFileStream"; }
static struct __slotinfo *ConsoleFileStream___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "collection", 0, 4 }, { "position", 4, 4 }, { "readLimit", 8, 4 }, { "file", 12, 4 }, { "_prompt", 16, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t File___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_File); }
static char *File___5fdebugName(oop _closure, oop v_self) { return "File"; }
static struct __slotinfo *File___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "_fd", 0, 4 }, { "name", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t Function___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_Function); }
static char *Function___5fdebugName(oop _closure, oop v_self) { return "Function"; }
static struct __slotinfo *Function___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { 0, 0, 0 } };  return &info[0]; }
static size_t Random___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_Random); }
static char *Random___5fdebugName(oop _closure, oop v_self) { return "Random"; }
static struct __slotinfo *Random___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "seed", 0, 4 }, { "a", 4, 4 }, { "m", 8, 4 }, { "q", 12, 4 }, { "r", 16, 4 }, { 0, 0, 0 } };  return &info[0]; }
static size_t OS___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_OS); }
static char *OS___5fdebugName(oop _closure, oop v_self) { return "OS"; }
static struct __slotinfo *OS___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { 0, 0, 0 } };  return &info[0]; }
static size_t nil___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_nil); }
static char *nil___5fdebugName(oop _closure, oop v_self) { return "nil"; }
static struct __slotinfo *nil___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { 0, 0, 0 } };  return &info[0]; }
static size_t true___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_true); }
static char *true___5fdebugName(oop _closure, oop v_self) { return "true"; }
static struct __slotinfo *true___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { 0, 0, 0 } };  return &info[0]; }
static size_t false___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_false); }
static char *false___5fdebugName(oop _closure, oop v_self) { return "false"; }
static struct __slotinfo *false___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { 0, 0, 0 } };  return &info[0]; }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "Objects.st", 0, 0, 0, 0 };
void __id__init__Objects(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
# define GC_add_roots _libid->gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info);

  _sendv(s__5fimport_, 3, _libid->_object, "_object", "__id__init___5fobject");
  v__object= _libid->import("_object");
  v__selector= _libid->import("_selector");
  v_Object= _libid->proto2(v__object, Object___5fsizeof(0, 0));
  _libid->method(v_Object, s__5fsizeof, (_imp_t)Object___5fsizeof);
  _libid->method(v_Object, s__5fdebugName, (_imp_t)Object___5fdebugName);
  _libid->method(v_Object, s__5fslots, (_imp_t)Object___5fslots);
  _libid->export("Object", v_Object);
 {
  oop _1= 0;
  _1= v__object;
  v_Object= _1;
  _libid->export("Object", v_Object);
 }
  v_UndefinedObject= _libid->proto2(v_Object, UndefinedObject___5fsizeof(0, 0));
  _libid->method(v_UndefinedObject, s__5fsizeof, (_imp_t)UndefinedObject___5fsizeof);
  _libid->method(v_UndefinedObject, s__5fdebugName, (_imp_t)UndefinedObject___5fdebugName);
  _libid->method(v_UndefinedObject, s__5fslots, (_imp_t)UndefinedObject___5fslots);
  _libid->export("UndefinedObject", v_UndefinedObject);
  v_Magnitude= _libid->proto2(v_Object, Magnitude___5fsizeof(0, 0));
  _libid->method(v_Magnitude, s__5fsizeof, (_imp_t)Magnitude___5fsizeof);
  _libid->method(v_Magnitude, s__5fdebugName, (_imp_t)Magnitude___5fdebugName);
  _libid->method(v_Magnitude, s__5fslots, (_imp_t)Magnitude___5fslots);
  _libid->export("Magnitude", v_Magnitude);
  v_Date= _libid->proto2(v_Magnitude, Date___5fsizeof(0, 0));
  _libid->method(v_Date, s__5fsizeof, (_imp_t)Date___5fsizeof);
  _libid->method(v_Date, s__5fdebugName, (_imp_t)Date___5fdebugName);
  _libid->method(v_Date, s__5fslots, (_imp_t)Date___5fslots);
  _libid->export("Date", v_Date);
  v_Time= _libid->proto2(v_Magnitude, Time___5fsizeof(0, 0));
  _libid->method(v_Time, s__5fsizeof, (_imp_t)Time___5fsizeof);
  _libid->method(v_Time, s__5fdebugName, (_imp_t)Time___5fdebugName);
  _libid->method(v_Time, s__5fslots, (_imp_t)Time___5fslots);
  _libid->export("Time", v_Time);
  v_Number= _libid->proto2(v_Magnitude, Number___5fsizeof(0, 0));
  _libid->method(v_Number, s__5fsizeof, (_imp_t)Number___5fsizeof);
  _libid->method(v_Number, s__5fdebugName, (_imp_t)Number___5fdebugName);
  _libid->method(v_Number, s__5fslots, (_imp_t)Number___5fslots);
  _libid->export("Number", v_Number);
  v_Float= _libid->proto2(v_Number, Float___5fsizeof(0, 0));
  _libid->method(v_Float, s__5fsizeof, (_imp_t)Float___5fsizeof);
  _libid->method(v_Float, s__5fdebugName, (_imp_t)Float___5fdebugName);
  _libid->method(v_Float, s__5fslots, (_imp_t)Float___5fslots);
  _libid->export("Float", v_Float);
  v_Integer= _libid->proto2(v_Number, Integer___5fsizeof(0, 0));
  _libid->method(v_Integer, s__5fsizeof, (_imp_t)Integer___5fsizeof);
  _libid->method(v_Integer, s__5fdebugName, (_imp_t)Integer___5fdebugName);
  _libid->method(v_Integer, s__5fslots, (_imp_t)Integer___5fslots);
  _libid->export("Integer", v_Integer);
  v_SmallInteger= _libid->proto2(v_Integer, SmallInteger___5fsizeof(0, 0));
  _libid->method(v_SmallInteger, s__5fsizeof, (_imp_t)SmallInteger___5fsizeof);
  _libid->method(v_SmallInteger, s__5fdebugName, (_imp_t)SmallInteger___5fdebugName);
  _libid->method(v_SmallInteger, s__5fslots, (_imp_t)SmallInteger___5fslots);
  _libid->export("SmallInteger", v_SmallInteger);
  v_LargeInteger= _libid->proto2(v_Integer, LargeInteger___5fsizeof(0, 0));
  _libid->method(v_LargeInteger, s__5fsizeof, (_imp_t)LargeInteger___5fsizeof);
  _libid->method(v_LargeInteger, s__5fdebugName, (_imp_t)LargeInteger___5fdebugName);
  _libid->method(v_LargeInteger, s__5fslots, (_imp_t)LargeInteger___5fslots);
  _libid->export("LargeInteger", v_LargeInteger);
  v_Symbol= _libid->proto2(v_Object, Symbol___5fsizeof(0, 0));
  _libid->method(v_Symbol, s__5fsizeof, (_imp_t)Symbol___5fsizeof);
  _libid->method(v_Symbol, s__5fdebugName, (_imp_t)Symbol___5fdebugName);
  _libid->method(v_Symbol, s__5fslots, (_imp_t)Symbol___5fslots);
  _libid->export("Symbol", v_Symbol);
 {
  oop _1= 0;
  _1= v__selector;
  v_Symbol= _1;
  _libid->export("Symbol", v_Symbol);
 }
  v_Association= _libid->proto2(v_Object, Association___5fsizeof(0, 0));
  _libid->method(v_Association, s__5fsizeof, (_imp_t)Association___5fsizeof);
  _libid->method(v_Association, s__5fdebugName, (_imp_t)Association___5fdebugName);
  _libid->method(v_Association, s__5fslots, (_imp_t)Association___5fslots);
  _libid->export("Association", v_Association);
  v_Link= _libid->proto2(v_Object, Link___5fsizeof(0, 0));
  _libid->method(v_Link, s__5fsizeof, (_imp_t)Link___5fsizeof);
  _libid->method(v_Link, s__5fdebugName, (_imp_t)Link___5fdebugName);
  _libid->method(v_Link, s__5fslots, (_imp_t)Link___5fslots);
  _libid->export("Link", v_Link);
  v_Collection= _libid->proto2(v_Object, Collection___5fsizeof(0, 0));
  _libid->method(v_Collection, s__5fsizeof, (_imp_t)Collection___5fsizeof);
  _libid->method(v_Collection, s__5fdebugName, (_imp_t)Collection___5fdebugName);
  _libid->method(v_Collection, s__5fslots, (_imp_t)Collection___5fslots);
  _libid->export("Collection", v_Collection);
  v_SequenceableCollection= _libid->proto2(v_Collection, SequenceableCollection___5fsizeof(0, 0));
  _libid->method(v_SequenceableCollection, s__5fsizeof, (_imp_t)SequenceableCollection___5fsizeof);
  _libid->method(v_SequenceableCollection, s__5fdebugName, (_imp_t)SequenceableCollection___5fdebugName);
  _libid->method(v_SequenceableCollection, s__5fslots, (_imp_t)SequenceableCollection___5fslots);
  _libid->export("SequenceableCollection", v_SequenceableCollection);
  v_LinkedList= _libid->proto2(v_SequenceableCollection, LinkedList___5fsizeof(0, 0));
  _libid->method(v_LinkedList, s__5fsizeof, (_imp_t)LinkedList___5fsizeof);
  _libid->method(v_LinkedList, s__5fdebugName, (_imp_t)LinkedList___5fdebugName);
  _libid->method(v_LinkedList, s__5fslots, (_imp_t)LinkedList___5fslots);
  _libid->export("LinkedList", v_LinkedList);
  v_ArrayedCollection= _libid->proto2(v_SequenceableCollection, ArrayedCollection___5fsizeof(0, 0));
  _libid->method(v_ArrayedCollection, s__5fsizeof, (_imp_t)ArrayedCollection___5fsizeof);
  _libid->method(v_ArrayedCollection, s__5fdebugName, (_imp_t)ArrayedCollection___5fdebugName);
  _libid->method(v_ArrayedCollection, s__5fslots, (_imp_t)ArrayedCollection___5fslots);
  _libid->export("ArrayedCollection", v_ArrayedCollection);
  v_Array= _libid->proto2(v_ArrayedCollection, Array___5fsizeof(0, 0));
  _libid->method(v_Array, s__5fsizeof, (_imp_t)Array___5fsizeof);
  _libid->method(v_Array, s__5fdebugName, (_imp_t)Array___5fdebugName);
  _libid->method(v_Array, s__5fslots, (_imp_t)Array___5fslots);
  _libid->export("Array", v_Array);
  v_ByteArray= _libid->proto2(v_ArrayedCollection, ByteArray___5fsizeof(0, 0));
  _libid->method(v_ByteArray, s__5fsizeof, (_imp_t)ByteArray___5fsizeof);
  _libid->method(v_ByteArray, s__5fdebugName, (_imp_t)ByteArray___5fdebugName);
  _libid->method(v_ByteArray, s__5fslots, (_imp_t)ByteArray___5fslots);
  _libid->export("ByteArray", v_ByteArray);
  v_String= _libid->proto2(v_ByteArray, String___5fsizeof(0, 0));
  _libid->method(v_String, s__5fsizeof, (_imp_t)String___5fsizeof);
  _libid->method(v_String, s__5fdebugName, (_imp_t)String___5fdebugName);
  _libid->method(v_String, s__5fslots, (_imp_t)String___5fslots);
  _libid->export("String", v_String);
  v_OrderedCollection= _libid->proto2(v_SequenceableCollection, OrderedCollection___5fsizeof(0, 0));
  _libid->method(v_OrderedCollection, s__5fsizeof, (_imp_t)OrderedCollection___5fsizeof);
  _libid->method(v_OrderedCollection, s__5fdebugName, (_imp_t)OrderedCollection___5fdebugName);
  _libid->method(v_OrderedCollection, s__5fslots, (_imp_t)OrderedCollection___5fslots);
  _libid->export("OrderedCollection", v_OrderedCollection);
  v_IdentitySet= _libid->proto2(v_Collection, IdentitySet___5fsizeof(0, 0));
  _libid->method(v_IdentitySet, s__5fsizeof, (_imp_t)IdentitySet___5fsizeof);
  _libid->method(v_IdentitySet, s__5fdebugName, (_imp_t)IdentitySet___5fdebugName);
  _libid->method(v_IdentitySet, s__5fslots, (_imp_t)IdentitySet___5fslots);
  _libid->export("IdentitySet", v_IdentitySet);
  v_Set= _libid->proto2(v_IdentitySet, Set___5fsizeof(0, 0));
  _libid->method(v_Set, s__5fsizeof, (_imp_t)Set___5fsizeof);
  _libid->method(v_Set, s__5fdebugName, (_imp_t)Set___5fdebugName);
  _libid->method(v_Set, s__5fslots, (_imp_t)Set___5fslots);
  _libid->export("Set", v_Set);
  v_IdentityDictionary= _libid->proto2(v_IdentitySet, IdentityDictionary___5fsizeof(0, 0));
  _libid->method(v_IdentityDictionary, s__5fsizeof, (_imp_t)IdentityDictionary___5fsizeof);
  _libid->method(v_IdentityDictionary, s__5fdebugName, (_imp_t)IdentityDictionary___5fdebugName);
  _libid->method(v_IdentityDictionary, s__5fslots, (_imp_t)IdentityDictionary___5fslots);
  _libid->export("IdentityDictionary", v_IdentityDictionary);
  v_Dictionary= _libid->proto2(v_IdentityDictionary, Dictionary___5fsizeof(0, 0));
  _libid->method(v_Dictionary, s__5fsizeof, (_imp_t)Dictionary___5fsizeof);
  _libid->method(v_Dictionary, s__5fdebugName, (_imp_t)Dictionary___5fdebugName);
  _libid->method(v_Dictionary, s__5fslots, (_imp_t)Dictionary___5fslots);
  _libid->export("Dictionary", v_Dictionary);
  v_FastIdentityDictionary= _libid->proto2(v_IdentityDictionary, FastIdentityDictionary___5fsizeof(0, 0));
  _libid->method(v_FastIdentityDictionary, s__5fsizeof, (_imp_t)FastIdentityDictionary___5fsizeof);
  _libid->method(v_FastIdentityDictionary, s__5fdebugName, (_imp_t)FastIdentityDictionary___5fdebugName);
  _libid->method(v_FastIdentityDictionary, s__5fslots, (_imp_t)FastIdentityDictionary___5fslots);
  _libid->export("FastIdentityDictionary", v_FastIdentityDictionary);
  v_SlotDictionary= _libid->proto2(v_Object, SlotDictionary___5fsizeof(0, 0));
  _libid->method(v_SlotDictionary, s__5fsizeof, (_imp_t)SlotDictionary___5fsizeof);
  _libid->method(v_SlotDictionary, s__5fdebugName, (_imp_t)SlotDictionary___5fdebugName);
  _libid->method(v_SlotDictionary, s__5fslots, (_imp_t)SlotDictionary___5fslots);
  _libid->export("SlotDictionary", v_SlotDictionary);
  v_MemoDictionary= _libid->proto2(v_SlotDictionary, MemoDictionary___5fsizeof(0, 0));
  _libid->method(v_MemoDictionary, s__5fsizeof, (_imp_t)MemoDictionary___5fsizeof);
  _libid->method(v_MemoDictionary, s__5fdebugName, (_imp_t)MemoDictionary___5fdebugName);
  _libid->method(v_MemoDictionary, s__5fslots, (_imp_t)MemoDictionary___5fslots);
  _libid->export("MemoDictionary", v_MemoDictionary);
  v_StaticBlockClosure= _libid->proto2(v_Object, StaticBlockClosure___5fsizeof(0, 0));
  _libid->method(v_StaticBlockClosure, s__5fsizeof, (_imp_t)StaticBlockClosure___5fsizeof);
  _libid->method(v_StaticBlockClosure, s__5fdebugName, (_imp_t)StaticBlockClosure___5fdebugName);
  _libid->method(v_StaticBlockClosure, s__5fslots, (_imp_t)StaticBlockClosure___5fslots);
  _libid->export("StaticBlockClosure", v_StaticBlockClosure);
  v_BlockClosure= _libid->proto2(v_StaticBlockClosure, BlockClosure___5fsizeof(0, 0));
  _libid->method(v_BlockClosure, s__5fsizeof, (_imp_t)BlockClosure___5fsizeof);
  _libid->method(v_BlockClosure, s__5fdebugName, (_imp_t)BlockClosure___5fdebugName);
  _libid->method(v_BlockClosure, s__5fslots, (_imp_t)BlockClosure___5fslots);
  _libid->export("BlockClosure", v_BlockClosure);
  v_ProfiledMethod= _libid->proto2(v_Object, ProfiledMethod___5fsizeof(0, 0));
  _libid->method(v_ProfiledMethod, s__5fsizeof, (_imp_t)ProfiledMethod___5fsizeof);
  _libid->method(v_ProfiledMethod, s__5fdebugName, (_imp_t)ProfiledMethod___5fdebugName);
  _libid->method(v_ProfiledMethod, s__5fslots, (_imp_t)ProfiledMethod___5fslots);
  _libid->export("ProfiledMethod", v_ProfiledMethod);
  v_SinkStream= _libid->proto2(v_Object, SinkStream___5fsizeof(0, 0));
  _libid->method(v_SinkStream, s__5fsizeof, (_imp_t)SinkStream___5fsizeof);
  _libid->method(v_SinkStream, s__5fdebugName, (_imp_t)SinkStream___5fdebugName);
  _libid->method(v_SinkStream, s__5fslots, (_imp_t)SinkStream___5fslots);
  _libid->export("SinkStream", v_SinkStream);
  v_ReadStream= _libid->proto2(v_Object, ReadStream___5fsizeof(0, 0));
  _libid->method(v_ReadStream, s__5fsizeof, (_imp_t)ReadStream___5fsizeof);
  _libid->method(v_ReadStream, s__5fdebugName, (_imp_t)ReadStream___5fdebugName);
  _libid->method(v_ReadStream, s__5fslots, (_imp_t)ReadStream___5fslots);
  _libid->export("ReadStream", v_ReadStream);
  v_WriteStream= _libid->proto2(v_ReadStream, WriteStream___5fsizeof(0, 0));
  _libid->method(v_WriteStream, s__5fsizeof, (_imp_t)WriteStream___5fsizeof);
  _libid->method(v_WriteStream, s__5fdebugName, (_imp_t)WriteStream___5fdebugName);
  _libid->method(v_WriteStream, s__5fslots, (_imp_t)WriteStream___5fslots);
  _libid->export("WriteStream", v_WriteStream);
  v_FileStream= _libid->proto2(v_ReadStream, FileStream___5fsizeof(0, 0));
  _libid->method(v_FileStream, s__5fsizeof, (_imp_t)FileStream___5fsizeof);
  _libid->method(v_FileStream, s__5fdebugName, (_imp_t)FileStream___5fdebugName);
  _libid->method(v_FileStream, s__5fslots, (_imp_t)FileStream___5fslots);
  _libid->export("FileStream", v_FileStream);
  v_ConsoleFileStream= _libid->proto2(v_FileStream, ConsoleFileStream___5fsizeof(0, 0));
  _libid->method(v_ConsoleFileStream, s__5fsizeof, (_imp_t)ConsoleFileStream___5fsizeof);
  _libid->method(v_ConsoleFileStream, s__5fdebugName, (_imp_t)ConsoleFileStream___5fdebugName);
  _libid->method(v_ConsoleFileStream, s__5fslots, (_imp_t)ConsoleFileStream___5fslots);
  _libid->export("ConsoleFileStream", v_ConsoleFileStream);
  v_File= _libid->proto2(v_Object, File___5fsizeof(0, 0));
  _libid->method(v_File, s__5fsizeof, (_imp_t)File___5fsizeof);
  _libid->method(v_File, s__5fdebugName, (_imp_t)File___5fdebugName);
  _libid->method(v_File, s__5fslots, (_imp_t)File___5fslots);
  _libid->export("File", v_File);
  v_Function= _libid->proto2(v_Object, Function___5fsizeof(0, 0));
  _libid->method(v_Function, s__5fsizeof, (_imp_t)Function___5fsizeof);
  _libid->method(v_Function, s__5fdebugName, (_imp_t)Function___5fdebugName);
  _libid->method(v_Function, s__5fslots, (_imp_t)Function___5fslots);
  _libid->export("Function", v_Function);
  v_Random= _libid->proto2(v_Object, Random___5fsizeof(0, 0));
  _libid->method(v_Random, s__5fsizeof, (_imp_t)Random___5fsizeof);
  _libid->method(v_Random, s__5fdebugName, (_imp_t)Random___5fdebugName);
  _libid->method(v_Random, s__5fslots, (_imp_t)Random___5fslots);
  _libid->export("Random", v_Random);
  v_OS= _libid->proto2(v_Object, OS___5fsizeof(0, 0));
  _libid->method(v_OS, s__5fsizeof, (_imp_t)OS___5fsizeof);
  _libid->method(v_OS, s__5fdebugName, (_imp_t)OS___5fdebugName);
  _libid->method(v_OS, s__5fslots, (_imp_t)OS___5fslots);
  _libid->export("OS", v_OS);
  v_nil= _libid->proto2(v_UndefinedObject, nil___5fsizeof(0, 0));
  _libid->method(v_nil, s__5fsizeof, (_imp_t)nil___5fsizeof);
  _libid->method(v_nil, s__5fdebugName, (_imp_t)nil___5fdebugName);
  _libid->method(v_nil, s__5fslots, (_imp_t)nil___5fslots);
  _libid->export("nil", v_nil);
  v_true= _libid->proto2(v_Object, true___5fsizeof(0, 0));
  _libid->method(v_true, s__5fsizeof, (_imp_t)true___5fsizeof);
  _libid->method(v_true, s__5fdebugName, (_imp_t)true___5fdebugName);
  _libid->method(v_true, s__5fslots, (_imp_t)true___5fslots);
  _libid->export("true", v_true);
  v_false= _libid->proto2(v_Object, false___5fsizeof(0, 0));
  _libid->method(v_false, s__5fsizeof, (_imp_t)false___5fsizeof);
  _libid->method(v_false, s__5fdebugName, (_imp_t)false___5fdebugName);
  _libid->method(v_false, s__5fslots, (_imp_t)false___5fslots);
  _libid->export("false", v_false);
 {
  v_StdIn= 0;
  _libid->export("StdIn", v_StdIn);
 }
 {
  v_StdOut= 0;
  _libid->export("StdOut", v_StdOut);
 }
 {
  v_StdErr= 0;
  _libid->export("StdErr", v_StdErr);
 }
  _leave();
}
