/* generated by Id 1.1 at ËZf */
/* with the command: -I../../object/stage2/ -I. -g -g -c OrderedCollection.st -o OrderedCollection.o.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s_shiftToEnd= 0;
static oop s_do_= 0;
static oop s_with_= 0;
static oop s_yourself= 0;
static oop s_max_= 0;
static oop s__3c= 0;
static oop s_to_do_= 0;
static oop s_value= 0;
static oop s__3e= 0;
static oop s_new_5f_= 0;
static oop s__2d= 0;
static oop s__2c= 0;
static oop s__3d_3d= 0;
static oop s__2b= 0;
static oop s_whileTrue_= 0;
static oop s_value_= 0;
static oop s_at_= 0;
static oop s_resetToEnd= 0;
static oop s_addFirst_= 0;
static oop s_value_5f_= 0;
static oop s__5fimport_= 0;
static oop s_with_with_= 0;
static oop s_ifFalse_= 0;
static oop s_new_= 0;
static oop s_add_= 0;
static oop s_ifTrue_= 0;
static oop s_downTo_do_= 0;
static oop s_emptyCheck= 0;
static oop s_and_= 0;
static oop s__2a= 0;
static oop s_removeLast= 0;
static oop s_new= 0;
static oop s_with_with_with_= 0;
static oop s_makeRoomAtFirst= 0;
static oop s_makeRoomAtLast= 0;
static oop s_replaceFrom_to_with_startingAt_= 0;
static oop s_size= 0;
static oop s_resetToBeginning= 0;
static oop s_shiftToBeginning= 0;
static oop s_function_5f_arity_5f_outer_state_nlr_5f_= 0;
static oop s_removeFirst= 0;
static oop s_addLast_= 0;
static oop s_indexOf_ifAbsent_= 0;
static oop s_doWithIndex_= 0;
static oop s_removeAll_ifAbsent_= 0;
static oop s_remove_ifAbsent_= 0;
static oop s_removeAtIndex_= 0;
static oop s__3e_3d= 0;
static oop s_errorOutOfBounds_= 0;
static oop s_insert_atIndex_= 0;
static oop s_ifTrue_ifFalse_= 0;
static oop s_removeAll= 0;
static oop s_asOrderedCollection= 0;
static oop s_at_put_= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "shiftToEnd", &s_shiftToEnd },
  { "do:", &s_do_ },
  { "with:", &s_with_ },
  { "yourself", &s_yourself },
  { "max:", &s_max_ },
  { "<", &s__3c },
  { "to:do:", &s_to_do_ },
  { "value", &s_value },
  { ">", &s__3e },
  { "new_:", &s_new_5f_ },
  { "-", &s__2d },
  { ",", &s__2c },
  { "==", &s__3d_3d },
  { "+", &s__2b },
  { "whileTrue:", &s_whileTrue_ },
  { "value:", &s_value_ },
  { "at:", &s_at_ },
  { "resetToEnd", &s_resetToEnd },
  { "addFirst:", &s_addFirst_ },
  { "value_:", &s_value_5f_ },
  { "_import:", &s__5fimport_ },
  { "with:with:", &s_with_with_ },
  { "ifFalse:", &s_ifFalse_ },
  { "new:", &s_new_ },
  { "add:", &s_add_ },
  { "ifTrue:", &s_ifTrue_ },
  { "downTo:do:", &s_downTo_do_ },
  { "emptyCheck", &s_emptyCheck },
  { "and:", &s_and_ },
  { "*", &s__2a },
  { "removeLast", &s_removeLast },
  { "new", &s_new },
  { "with:with:with:", &s_with_with_with_ },
  { "makeRoomAtFirst", &s_makeRoomAtFirst },
  { "makeRoomAtLast", &s_makeRoomAtLast },
  { "replaceFrom:to:with:startingAt:", &s_replaceFrom_to_with_startingAt_ },
  { "size", &s_size },
  { "resetToBeginning", &s_resetToBeginning },
  { "shiftToBeginning", &s_shiftToBeginning },
  { "function_:arity_:outer:state:nlr_:", &s_function_5f_arity_5f_outer_state_nlr_5f_ },
  { "removeFirst", &s_removeFirst },
  { "addLast:", &s_addLast_ },
  { "indexOf:ifAbsent:", &s_indexOf_ifAbsent_ },
  { "doWithIndex:", &s_doWithIndex_ },
  { "removeAll:ifAbsent:", &s_removeAll_ifAbsent_ },
  { "remove:ifAbsent:", &s_remove_ifAbsent_ },
  { "removeAtIndex:", &s_removeAtIndex_ },
  { ">=", &s__3e_3d },
  { "errorOutOfBounds:", &s_errorOutOfBounds_ },
  { "insert:atIndex:", &s_insert_atIndex_ },
  { "ifTrue:ifFalse:", &s_ifTrue_ifFalse_ },
  { "removeAll", &s_removeAll },
  { "asOrderedCollection", &s_asOrderedCollection },
  { "at:put:", &s_at_put_ },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Date {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__microseconds;
};
struct t_Time {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__nanoseconds;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargeInteger {
  struct _vtable *_vtable[0];
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t_Association {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t_Link {
  struct _vtable *_vtable[0];
  oop v_prevLink;
  oop v_nextLink;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_LinkedList {
  struct _vtable *_vtable[0];
  oop v_firstLink;
  oop v_lastLink;
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__oops;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_OrderedCollection {
  struct _vtable *_vtable[0];
  oop v_firstIndex;
  oop v_lastIndex;
  oop v_array;
};
struct t_IdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Set {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_IdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Dictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_FastIdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_SlotDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_MemoDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_ProfiledMethod {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_count;
  oop v_next;
};
struct t_SinkStream {
  struct _vtable *_vtable[0];
};
struct t_ReadStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_WriteStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_writeLimit;
};
struct t_FileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
};
struct t_ConsoleFileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
  oop v__prompt;
};
struct t_File {
  struct _vtable *_vtable[0];
  oop v__fd;
  oop v_name;
};
struct t_Function {
  struct _vtable *_vtable[0];
};
struct t_Random {
  struct _vtable *_vtable[0];
  oop v_seed;
  oop v_a;
  oop v_m;
  oop v_q;
  oop v_r;
};
struct t_OS {
  struct _vtable *_vtable[0];
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
static oop l_2= 0;
static oop l_4= 0;
static oop l_12= 0;
static oop l_13= 0;
static oop l_15= 0;
static oop l_17= 0;
static oop l_18= 0;
static oop l_19= 0;
static oop l_21= 0;
static oop l_22= 0;
static oop l_23= 0;
static oop l_25= 0;
static oop l_26= 0;
static oop l_29= 0;
static oop l_30= 0;
static oop l_33= 0;
static oop l_36= 0;
static oop l_38= 0;
static oop l_40= 0;
static oop l_49= 0;
static oop l_50= 0;
static oop l_52= 0;
static oop l_54= 0;
static oop l_55= 0;
static oop l_58= 0;
static oop l_60= 0;
static oop l_62= 0;
static oop v__object= 0;
static oop v__vector= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_Magnitude= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_SmallInteger= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_Array= 0;
static oop v_ByteArray= 0;
static oop v_OrderedCollection= 0;
static oop v_IdentitySet= 0;
static oop v_IdentityDictionary= 0;
static oop v_SlotDictionary= 0;
static oop v_StaticBlockClosure= 0;
static oop v_BlockClosure= 0;
static oop v_ReadStream= 0;
static oop v_FileStream= 0;
static oop v_nil= 0;
static oop v_true= 0;
static oop v_false= 0;
static struct __methodinfo __info1= { "new", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 25, 27, 0 };
static oop OrderedCollection__new(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info1);
  oop _1= 0;
  oop _2= 0;
  _line(25);
  _1= v_self;
  _2= l_2;
  _line(25);
  _1=_sendv(s_new_, 2, _1, _2);
  _line(25);
  _1=_sendv(s_removeAll, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info3= { "new:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 27, 35, &__info1 };
static oop OrderedCollection__new_(oop v__closure, oop v_stateful_self, oop v_self, oop v_size)
 {
  _enter(&__info3);
  oop _1= 0;
  oop _2= 0;
  _line(27);
  _1= v_self;
  _line(29);
  _1=_superv(v_SequenceableCollection, s_new, 1, _1);
  v_self= _1;
  v_stateful_self= _1;
  _1= v_Array;
  _2= v_size;
  _line(30);
  _1=_sendv(s_new_, 2, _1, _2);
  ((struct t_OrderedCollection *)v_stateful_self)->v_array= _1;
  _1= l_4;
  ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex= _1;
  _1= v_size;
  ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info5= { "with:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 35, 36, &__info3 };
static oop OrderedCollection__with_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anObject)
 {
  _enter(&__info5);
  oop _1= 0;
  oop _2= 0;
  _line(35);
  _1= v_self;
  _line(35);
  _1=_sendv(s_new, 1, _1);
  _2= v_anObject;
  _line(35);
  _sendv(s_add_, 2, _1, _2);
  _1=_sendv(s_yourself, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info6= { "with:with:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 36, 37, &__info5 };
static oop OrderedCollection__with_with_(oop v__closure, oop v_stateful_self, oop v_self, oop v_a, oop v_b)
 {
  _enter(&__info6);
  oop _1= 0;
  oop _2= 0;
  _line(36);
  _1= v_self;
  _line(36);
  _1=_sendv(s_new, 1, _1);
  _2= v_a;
  _line(36);
  _sendv(s_add_, 2, _1, _2);
  _2= v_b;
  _sendv(s_add_, 2, _1, _2);
  _1=_sendv(s_yourself, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info7= { "with:with:with:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 37, 39, &__info6 };
static oop OrderedCollection__with_with_with_(oop v__closure, oop v_stateful_self, oop v_self, oop v_a, oop v_b, oop v_c)
 {
  _enter(&__info7);
  oop _1= 0;
  oop _2= 0;
  _line(37);
  _1= v_self;
  _line(37);
  _1=_sendv(s_new, 1, _1);
  _2= v_a;
  _line(37);
  _sendv(s_add_, 2, _1, _2);
  _2= v_b;
  _sendv(s_add_, 2, _1, _2);
  _2= v_c;
  _sendv(s_add_, 2, _1, _2);
  _1=_sendv(s_yourself, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info8= { "size", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 39, 41, &__info7 };
static oop OrderedCollection__size(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info8);
  oop _1= 0;
  oop _2= 0;
  _line(39);
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex;
  _2= ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2d, 2, _1, _2);
  }
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info9= { ",", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 41, 43, &__info8 };
static oop OrderedCollection___2c(oop v__closure, oop v_stateful_self, oop v_self, oop v_anObject)
 {
  _enter(&__info9);
  oop _1= 0;
  oop _2= 0;
  _line(41);
  _1= v_self;
  _2= v_anObject;
  _line(41);
  _1=_sendv(s_addLast_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info10= { "add:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 43, 45, &__info9 };
static oop OrderedCollection__add_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anObject)
 {
  _enter(&__info10);
  oop _1= 0;
  oop _2= 0;
  _line(43);
  _1= v_self;
  _2= v_anObject;
  _line(43);
  _1=_sendv(s_addLast_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info11= { "addFirst:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 45, 53, &__info10 };
static oop OrderedCollection__addFirst_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anObject)
 {
  _enter(&__info11);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(45);
  /* ifTrue: */
  _1= 0;
  _2= ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex;
  _3= l_12;
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l1;
 {
  _1= v_self;
  _line(47);
  _1=_sendv(s_makeRoomAtFirst, 1, _1);
 }
 _l1:;
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex;
  _2= l_13;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2d, 2, _1, _2);
  }
  ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex= _1;
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _2= ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex;
  _3= v_anObject;
  _line(49);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _1= v_anObject;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info14= { "addLast:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 53, 61, &__info11 };
static oop OrderedCollection__addLast_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anObject)
 {
  _enter(&__info14);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(53);
  /* ifTrue: */
  _1= 0;
  _2= ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex;
  _3= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _line(55);
  _3=_sendv(s_size, 1, _3);
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l2;
 {
  _1= v_self;
  _line(55);
  _1=_sendv(s_makeRoomAtLast, 1, _1);
 }
 _l2:;
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _2= ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex;
  _3= v_anObject;
  _line(56);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex;
  _2= l_15;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex= _1;
  _1= v_anObject;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info16= { "makeRoomAtFirst", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 61, 74, &__info14 };
static oop OrderedCollection__makeRoomAtFirst(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info16);
  oop v_delta= 0;
  oop v_newArray= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  oop _5= 0;
  (void)v_delta;
  (void)v_newArray;
  _line(61);
  /* ifTrue: */
  _1= 0;
  _2= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _line(64);
  _2=_sendv(s_size, 1, _2);
  v_delta= _2;
  _3= l_17;
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l3;
 {
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _2= l_18;
  v_delta= _2;
  _line(64);
  _1=_sendv(s_new_, 2, _1, _2);
  ((struct t_OrderedCollection *)v_stateful_self)->v_array= _1;
 }
 _l3:;
  /* ifTrue: */
  _1= 0;
  /* and: */
  _2= v_self;
  _line(65);
  _2=_sendv(s_size, 1, _2);
  _3= l_17;
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l5;
 {
  _2= v_delta;
  _3= l_17;
  if (1 & (long)_2) {
    _2= (((long)_2 > (long)_3) ? v_true : v_false);
  } else _2= _sendv(s__3e, 2, _2, _3);
 }
 _l5:;
  if (!_2) goto _l4;
 {
  _1= v_self;
  _line(65);
  _1=_sendv(s_resetToEnd, 1, _1);
  _leave();
  return _1;
 }
 _l4:;
  /* ifTrue: */
  _1= 0;
  _2= v_self;
  _line(66);
  _2=_sendv(s_size, 1, _2);
  _3= l_18;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= (_l * _r);
    if ((1 & (long)_2) && ((_r == 0) || (_s / _r == _l)) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2a, 2, _2, _3);
  }
  _3= v_delta;
  if (1 & (long)_2 & (long)_3) {
    _2= (((long)_2 < (long)_3) ? v_true : v_false);
  } else _2= _sendv(s__3c, 2, _2, _3);
  if (!_2) goto _l6;
 {
  _1= v_self;
  _line(66);
  _1=_sendv(s_shiftToEnd, 1, _1);
  _leave();
  return _1;
 }
 _l6:;
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _2= v_self;
  _line(67);
  _2=_sendv(s_size, 1, _2);
  _3= v_delta;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_2 & (long)_3) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2b, 2, _2, _3);
  }
  _3= l_18;
  _line(67);
  _2=_sendv(s_max_, 2, _2, _3);
  _line(67);
  _1=_sendv(s_new_, 2, _1, _2);
  _2= ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex;
  _3= v_delta;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_2 & (long)_3) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2b, 2, _2, _3);
  }
  _3= ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex;
  _4= v_delta;
  {
    int _l= (long)_3 >> 1;
    int _r= (long)_4 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_3 & (long)_4) && ((_s ^ (_s << 1)) >= 0))  _3= (oop)(long)(_s << 1 | 1);  else _3= _sendv(s__2b, 2, _3, _4);
  }
  _4= l_19;
  {
    int _l= (long)_3 >> 1;
    int _r= (long)_4 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_3) && ((_s ^ (_s << 1)) >= 0))  _3= (oop)(long)(_s << 1 | 1);  else _3= _sendv(s__2d, 2, _3, _4);
  }
  _4= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _5= ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex;
  _line(68);
  _1=_sendv(s_replaceFrom_to_with_startingAt_, 5, _1, _2, _3, _4, _5);
  v_newArray= _1;
  _1= v_newArray;
  ((struct t_OrderedCollection *)v_stateful_self)->v_array= _1;
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex;
  _2= v_delta;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex= _1;
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex;
  _2= v_delta;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info20= { "makeRoomAtLast", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 74, 83, &__info16 };
static oop OrderedCollection__makeRoomAtLast(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info20);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  oop _5= 0;
  _line(74);
  /* ifTrue: */
  _1= 0;
  /* and: */
  _2= v_self;
  _line(76);
  _2=_sendv(s_size, 1, _2);
  _3= l_21;
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l8;
 {
  _2= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _line(76);
  _2=_sendv(s_size, 1, _2);
  _3= l_21;
  if (1 & (long)_2) {
    _2= (((long)_2 > (long)_3) ? v_true : v_false);
  } else _2= _sendv(s__3e, 2, _2, _3);
 }
 _l8:;
  if (!_2) goto _l7;
 {
  _1= v_self;
  _line(76);
  _1=_sendv(s_resetToBeginning, 1, _1);
  _leave();
  return _1;
 }
 _l7:;
  /* ifTrue: */
  _1= 0;
  _2= v_self;
  _line(77);
  _2=_sendv(s_size, 1, _2);
  _3= l_22;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= (_l * _r);
    if ((1 & (long)_2) && ((_r == 0) || (_s / _r == _l)) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2a, 2, _2, _3);
  }
  _3= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _line(77);
  _3=_sendv(s_size, 1, _3);
  if (1 & (long)_2 & (long)_3) {
    _2= (((long)_2 < (long)_3) ? v_true : v_false);
  } else _2= _sendv(s__3c, 2, _2, _3);
  if (!_2) goto _l9;
 {
  _1= v_self;
  _line(77);
  _1=_sendv(s_shiftToBeginning, 1, _1);
  _leave();
  return _1;
 }
 _l9:;
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _2= v_self;
  _line(78);
  _2=_sendv(s_size, 1, _2);
  _3= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _line(78);
  _3=_sendv(s_size, 1, _3);
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_2 & (long)_3) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2b, 2, _2, _3);
  }
  _3= l_22;
  _line(78);
  _2=_sendv(s_max_, 2, _2, _3);
  _line(78);
  _1=_sendv(s_new_, 2, _1, _2);
  _2= ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex;
  _3= ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex;
  _4= l_23;
  {
    int _l= (long)_3 >> 1;
    int _r= (long)_4 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_3) && ((_s ^ (_s << 1)) >= 0))  _3= (oop)(long)(_s << 1 | 1);  else _3= _sendv(s__2d, 2, _3, _4);
  }
  _4= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _5= ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex;
  _line(79);
  _sendv(s_replaceFrom_to_with_startingAt_, 5, _1, _2, _3, _4, _5);
  _1=_sendv(s_yourself, 1, _1);
  ((struct t_OrderedCollection *)v_stateful_self)->v_array= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info27= { "[] shiftToBeginning", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 83, 92, &__info20 };
static oop b_27(oop v__closure, oop v__self, oop v_index)
 {
  _enter(&__info27);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  oop _5= 0;
  _line(87);
  _1= ((struct t_OrderedCollection *)((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[2])->v_array;  /* array */
  _2= v_index;
  _3= ((struct t_OrderedCollection *)((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[2])->v_array;  /* array */
  _4= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[3];  /* delta */
  _5= v_index;
  {
    int _l= (long)_4 >> 1;
    int _r= (long)_5 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_4 & (long)_5) && ((_s ^ (_s << 1)) >= 0))  _4= (oop)(long)(_s << 1 | 1);  else _4= _sendv(s__2b, 2, _4, _5);
  }
  _line(87);
  _3=_sendv(s_at_, 2, _3, _4);
  _line(87);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info24= { "shiftToBeginning", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 83, 92, &__info27 };
static oop OrderedCollection__shiftToBeginning(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info24);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 7);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  ((oop *)_state1)[2]= v_stateful_self;
  ((oop *)_state1)[1]= v_self;
  _line(83);
  /* ifTrue: */
  _1= 0;
  _2= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_firstIndex;  /* firstIndex */
  ((oop *)_state1)[3]= _2;  /* delta */
  _3= l_25;
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l10;
 {
  _1= ((oop *)_state1)[1];  /* self */
  _leave();
  return _1;
 }
 _l10:;
  _1= l_25;
  _2= ((oop *)_state1)[1];  /* self */
  _line(87);
  _2=_sendv(s_size, 1, _2);
  _3= l_26;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2d, 2, _2, _3);
  }
  /* Scope('index'->ArgumentVariableNode) */
  /* Scope('firstIndex'->SlotVariableNode 'self'->ArgumentVariableNode 'lastIndex'->SlotVariableNode 'stateful_self'->ArgumentVariableNode 'delta'->TemporaryVariableNode 'array'->SlotVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_27, 1, 0, ((oop *)_state1), 0);
  _line(87);
  _1=_sendv(s_to_do_, 3, _1, _2, _3);
  _1= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_firstIndex;  /* firstIndex */
  _2= ((oop *)_state1)[3];  /* delta */
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2d, 2, _1, _2);
  }
  ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_firstIndex= _1;  /* firstIndex */
  _1= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_lastIndex;  /* lastIndex */
  _2= ((oop *)_state1)[3];  /* delta */
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2d, 2, _1, _2);
  }
  ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_lastIndex= _1;  /* lastIndex */
  _1= ((oop *)_state1)[1];  /* self */
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info31= { "[] shiftToEnd", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 92, 101, &__info24 };
static oop b_31(oop v__closure, oop v__self, oop v_index)
 {
  _enter(&__info31);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  _line(96);
  _1= ((struct t_OrderedCollection *)((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[2])->v_array;  /* array */
  _2= v_index;
  _3= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[3];  /* delta */
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_2 & (long)_3) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2b, 2, _2, _3);
  }
  _3= ((struct t_OrderedCollection *)((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[2])->v_array;  /* array */
  _4= v_index;
  _line(96);
  _3=_sendv(s_at_, 2, _3, _4);
  _line(96);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info28= { "shiftToEnd", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 92, 101, &__info31 };
static oop OrderedCollection__shiftToEnd(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info28);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 7);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  ((oop *)_state1)[2]= v_stateful_self;
  ((oop *)_state1)[1]= v_self;
  _line(92);
  /* ifTrue: */
  _1= 0;
  _2= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_array;  /* array */
  _line(95);
  _2=_sendv(s_size, 1, _2);
  _3= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_lastIndex;  /* lastIndex */
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_2 & (long)_3) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2d, 2, _2, _3);
  }
  ((oop *)_state1)[3]= _2;  /* delta */
  _3= l_29;
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l11;
 {
  _1= ((oop *)_state1)[1];  /* self */
  _leave();
  return _1;
 }
 _l11:;
  _1= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_lastIndex;  /* lastIndex */
  _2= l_30;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2d, 2, _1, _2);
  }
  _2= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_firstIndex;  /* firstIndex */
  /* Scope('index'->ArgumentVariableNode) */
  /* Scope('firstIndex'->SlotVariableNode 'self'->ArgumentVariableNode 'lastIndex'->SlotVariableNode 'stateful_self'->ArgumentVariableNode 'delta'->TemporaryVariableNode 'array'->SlotVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_31, 1, 0, ((oop *)_state1), 0);
  _line(96);
  _1=_sendv(s_downTo_do_, 3, _1, _2, _3);
  _1= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_firstIndex;  /* firstIndex */
  _2= ((oop *)_state1)[3];  /* delta */
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_firstIndex= _1;  /* firstIndex */
  _1= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_lastIndex;  /* lastIndex */
  _2= ((oop *)_state1)[3];  /* delta */
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_lastIndex= _1;  /* lastIndex */
  _1= ((oop *)_state1)[1];  /* self */
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info32= { "resetToBeginning", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 101, 102, &__info28 };
static oop OrderedCollection__resetToBeginning(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info32);
  oop _1= 0;
  _line(101);
  _1= l_33;
  ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex= _1;
  ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info34= { "resetToEnd", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 102, 104, &__info32 };
static oop OrderedCollection__resetToEnd(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info34);
  oop _1= 0;
  _line(102);
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _line(102);
  _1=_sendv(s_size, 1, _1);
  ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex= _1;
  ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info35= { "removeFirst", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 104, 114, &__info34 };
static oop OrderedCollection__removeFirst(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info35);
  oop v_first= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  (void)v_first;
  _line(104);
  _1= v_self;
  _line(107);
  _1=_sendv(s_emptyCheck, 1, _1);
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _2= ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex;
  _line(108);
  _1=_sendv(s_at_, 2, _1, _2);
  v_first= _1;
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _2= ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex;
  _3= v_nil;
  _line(109);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex;
  _2= l_36;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex= _1;
  _1= v_first;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info37= { "removeLast", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 114, 124, &__info35 };
static oop OrderedCollection__removeLast(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info37);
  oop v_last= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  (void)v_last;
  _line(114);
  _1= v_self;
  _line(117);
  _1=_sendv(s_emptyCheck, 1, _1);
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex;
  _2= l_38;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2d, 2, _1, _2);
  }
  ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex= _1;
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _2= ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex;
  _line(119);
  _1=_sendv(s_at_, 2, _1, _2);
  v_last= _1;
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _2= ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex;
  _3= v_nil;
  _line(120);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _1= v_last;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info39= { "removeAll", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 124, 129, &__info37 };
static oop OrderedCollection__removeAll(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info39);
  oop _1= 0;
  _line(124);
  _1= l_40;
  ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex= _1;
  ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info42= { "[] indexOf:ifAbsent:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 129, 135, &__info39 };
static oop b_42(oop v__closure, oop v__self, oop v_element, oop v_index)
 {
  _enter(&__info42);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(131);
  /* ifTrue: */
  _1= 0;
  _2= v_element;
  _3= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* anObject */
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l12;
 {
  _1= v_index;
  _leave();
  return _libid->nlreturn(((struct t_BlockClosure *)v__self)->v__nlr, _1);
 }
 _l12:;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info41= { "indexOf:ifAbsent:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 129, 135, &__info42 };
static oop OrderedCollection__indexOf_ifAbsent_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anObject, oop v_errorBlock)
 {
  _enter(&__info41);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 2);
  oop _1= 0;
  oop _2= 0;
  jmp_buf __nlr;
  oop _nlr;
  ((oop *)_state1)[1]= v_anObject;
  _nlr= (oop)&__nlr;
  if (setjmp(__nlr)) { return _libid->nlresult(); }
  _line(129);
  _1= v_self;
  /* Scope('element'->ArgumentVariableNode 'index'->ArgumentVariableNode) */
  /* Scope('stateful_self'->ArgumentVariableNode 'array'->SlotVariableNode 'self'->ArgumentVariableNode 'firstIndex'->SlotVariableNode 'lastIndex'->SlotVariableNode 'errorBlock'->ArgumentVariableNode 'anObject'->ArgumentVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _2= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_42, 2, 0, ((oop *)_state1), _nlr);
  _line(131);
  _1=_sendv(s_doWithIndex_, 2, _1, _2);
  _1= v_errorBlock;
  _line(132);
  _1=_sendv(s_value, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info45= { "[] removeAll:ifAbsent:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 135, 140, &__info41 };
static oop b_45(oop v__closure, oop v__self)
 {
  _enter(&__info45);
  oop _1= 0;
  _line(137);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_outer)->v_state))[3];  /* errorBlock */
  _line(137);
  _1=_sendv(s_value, 1, _1);
  _leave();
  return _libid->nlreturn(((struct t_BlockClosure *)v__self)->v__nlr, _1);
  _leave();
 }
static struct __methodinfo __info44= { "[] removeAll:ifAbsent:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 135, 140, &__info45 };
static oop b_44(oop v__closure, oop v__self, oop v_element)
 {
  _enter(&__info44);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(137);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* self */
  _2= v_element;
  /* Scope() */
  /* Scope('element'->ArgumentVariableNode) */
  /* Object */
  /* 3 */
  /* 2 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_45, 0, v__self, 0, ((struct t_BlockClosure *)v__self)->v__nlr);
  _line(137);
  _1=_sendv(s_remove_ifAbsent_, 3, _1, _2, _3);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info43= { "removeAll:ifAbsent:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 135, 140, &__info44 };
static oop OrderedCollection__removeAll_ifAbsent_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aCollection, oop v_errorBlock)
 {
  _enter(&__info43);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 7);
  oop _1= 0;
  oop _2= 0;
  jmp_buf __nlr;
  oop _nlr;
  ((oop *)_state1)[2]= v_stateful_self;
  ((oop *)_state1)[1]= v_self;
  ((oop *)_state1)[3]= v_errorBlock;
  _nlr= (oop)&__nlr;
  if (setjmp(__nlr)) { return _libid->nlresult(); }
  _line(135);
  _1= v_aCollection;
  /* Scope('element'->ArgumentVariableNode) */
  /* Scope('stateful_self'->ArgumentVariableNode 'aCollection'->ArgumentVariableNode 'array'->SlotVariableNode 'self'->ArgumentVariableNode 'firstIndex'->SlotVariableNode 'lastIndex'->SlotVariableNode 'errorBlock'->ArgumentVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _2= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_44, 1, 0, ((oop *)_state1), _nlr);
  _line(137);
  _1=_sendv(s_do_, 2, _1, _2);
  _1= ((oop *)_state1)[1];  /* self */
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info47= { "[] remove:ifAbsent:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 140, 145, &__info43 };
static oop b_47(oop v__closure, oop v__self)
 {
  _enter(&__info47);
  oop _1= 0;
  _line(142);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* errorBlock */
  _line(142);
  _1=_sendv(s_value, 1, _1);
  _leave();
  return _libid->nlreturn(((struct t_BlockClosure *)v__self)->v__nlr, _1);
  _leave();
 }
static struct __methodinfo __info46= { "remove:ifAbsent:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 140, 145, &__info47 };
static oop OrderedCollection__remove_ifAbsent_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anObject, oop v_errorBlock)
 {
  _enter(&__info46);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 2);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  jmp_buf __nlr;
  oop _nlr;
  ((oop *)_state1)[1]= v_errorBlock;
  _nlr= (oop)&__nlr;
  if (setjmp(__nlr)) { return _libid->nlresult(); }
  _line(140);
  _1= v_self;
  _2= v_self;
  _3= v_anObject;
  /* Scope() */
  /* Scope('stateful_self'->ArgumentVariableNode 'array'->SlotVariableNode 'self'->ArgumentVariableNode 'firstIndex'->SlotVariableNode 'lastIndex'->SlotVariableNode 'errorBlock'->ArgumentVariableNode 'anObject'->ArgumentVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _4= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_47, 0, 0, ((oop *)_state1), _nlr);
  _line(142);
  _2=_sendv(s_indexOf_ifAbsent_, 3, _2, _3, _4);
  _line(142);
  _1=_sendv(s_removeAtIndex_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info51= { "[] removeAtIndex:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 145, 154, &__info46 };
static oop b_51(oop v__closure, oop v__self, oop v_i)
 {
  _enter(&__info51);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  oop _5= 0;
  _line(150);
  _1= ((struct t_OrderedCollection *)((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[2])->v_array;  /* array */
  _2= v_i;
  _3= ((struct t_OrderedCollection *)((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[2])->v_array;  /* array */
  _4= l_52;
  _5= v_i;
  {
    int _l= (long)_4 >> 1;
    int _r= (long)_5 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_5) && ((_s ^ (_s << 1)) >= 0))  _4= (oop)(long)(_s << 1 | 1);  else _4= _sendv(s__2b, 2, _4, _5);
  }
  _line(150);
  _3=_sendv(s_at_, 2, _3, _4);
  _line(150);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info48= { "removeAtIndex:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 145, 154, &__info51 };
static oop OrderedCollection__removeAtIndex_(oop v__closure, oop v_stateful_self, oop v_self, oop v_offset)
 {
  _enter(&__info48);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 6);
  oop v_arrayOffset= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  (void)v_arrayOffset;
  ((oop *)_state1)[2]= v_stateful_self;
  ((oop *)_state1)[1]= v_self;
  _line(145);
  _1= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_firstIndex;  /* firstIndex */
  _2= v_offset;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  v_arrayOffset= _1;
  /* ifFalse: */
  _1= 0;
  /* and: */
  _2= v_offset;
  _3= l_49;
  if (1 & (long)_2) {
    _2= (((long)_2 >= (long)_3) ? v_true : v_false);
  } else _2= _sendv(s__3e_3d, 2, _2, _3);
  if (!_2) goto _l14;
 {
  _2= v_arrayOffset;
  _3= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_lastIndex;  /* lastIndex */
  if (1 & (long)_2 & (long)_3) {
    _2= (((long)_2 < (long)_3) ? v_true : v_false);
  } else _2= _sendv(s__3c, 2, _2, _3);
 }
 _l14:;
  if (_2) goto _l13;
 {
  _1= ((oop *)_state1)[1];  /* self */
  _2= v_offset;
  _line(149);
  _1=_sendv(s_errorOutOfBounds_, 2, _1, _2);
  _leave();
  return _1;
 }
 _l13:;
  _1= v_arrayOffset;
  _2= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_lastIndex;  /* lastIndex */
  _3= l_50;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2d, 2, _2, _3);
  }
  /* Scope('i'->ArgumentVariableNode) */
  /* Scope('arrayOffset'->TemporaryVariableNode 'stateful_self'->ArgumentVariableNode 'array'->SlotVariableNode 'self'->ArgumentVariableNode 'offset'->ArgumentVariableNode 'firstIndex'->SlotVariableNode 'lastIndex'->SlotVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_51, 1, 0, ((oop *)_state1), 0);
  _line(150);
  _1=_sendv(s_to_do_, 3, _1, _2, _3);
  _1= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_lastIndex;  /* lastIndex */
  _2= l_52;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2d, 2, _1, _2);
  }
  ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_lastIndex= _1;  /* lastIndex */
  _1= ((oop *)_state1)[1];  /* self */
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info56= { "[] insert:atIndex:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 154, 168, &__info48 };
static oop b_56(oop v__closure, oop v__self, oop v_i)
 {
  _enter(&__info56);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  _line(163);
  _1= ((struct t_OrderedCollection *)((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[2])->v_array;  /* array */
  _2= v_i;
  _3= l_55;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2b, 2, _2, _3);
  }
  _3= ((struct t_OrderedCollection *)((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[2])->v_array;  /* array */
  _4= v_i;
  _line(163);
  _3=_sendv(s_at_, 2, _3, _4);
  _line(163);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info53= { "insert:atIndex:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 154, 168, &__info56 };
static oop OrderedCollection__insert_atIndex_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anObject, oop v_offset)
 {
  _enter(&__info53);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 6);
  oop v_arrayOffset= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  (void)v_arrayOffset;
  ((oop *)_state1)[2]= v_stateful_self;
  ((oop *)_state1)[1]= v_self;
  _line(154);
  _1= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_firstIndex;  /* firstIndex */
  _2= v_offset;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  v_arrayOffset= _1;
  /* ifTrue: */
  _1= 0;
  _2= v_offset;
  _3= l_54;
  if (1 & (long)_2) {
    _2= (((long)_2 < (long)_3) ? v_true : v_false);
  } else _2= _sendv(s__3c, 2, _2, _3);
  if (!_2) goto _l15;
 {
  _1= ((oop *)_state1)[1];  /* self */
  _2= v_offset;
  _line(158);
  _1=_sendv(s_errorOutOfBounds_, 2, _1, _2);
  _leave();
  return _1;
 }
 _l15:;
  /* ifTrue: */
  _1= 0;
  _2= v_offset;
  _3= l_54;
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l16;
 {
  _1= ((oop *)_state1)[1];  /* self */
  _2= v_anObject;
  _line(159);
  _1=_sendv(s_addFirst_, 2, _1, _2);
  _leave();
  return _1;
 }
 _l16:;
  /* ifTrue: */
  _1= 0;
  _2= v_arrayOffset;
  _3= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_lastIndex;  /* lastIndex */
  if (1 & (long)_2 & (long)_3) {
    _2= (((long)_2 > (long)_3) ? v_true : v_false);
  } else _2= _sendv(s__3e, 2, _2, _3);
  if (!_2) goto _l17;
 {
  _1= ((oop *)_state1)[1];  /* self */
  _2= v_offset;
  _line(160);
  _1=_sendv(s_errorOutOfBounds_, 2, _1, _2);
  _leave();
  return _1;
 }
 _l17:;
  /* ifTrue: */
  _1= 0;
  _2= v_arrayOffset;
  _3= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_lastIndex;  /* lastIndex */
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l18;
 {
  _1= ((oop *)_state1)[1];  /* self */
  _2= v_anObject;
  _line(161);
  _1=_sendv(s_addLast_, 2, _1, _2);
  _leave();
  return _1;
 }
 _l18:;
  /* ifTrue: */
  _1= 0;
  _2= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_lastIndex;  /* lastIndex */
  _3= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_array;  /* array */
  _line(162);
  _3=_sendv(s_size, 1, _3);
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l19;
 {
  _1= ((oop *)_state1)[1];  /* self */
  _line(162);
  _1=_sendv(s_makeRoomAtLast, 1, _1);
  _1= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_firstIndex;  /* firstIndex */
  _2= v_offset;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  v_arrayOffset= _1;
 }
 _l19:;
  _1= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_lastIndex;  /* lastIndex */
  _2= l_55;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2d, 2, _1, _2);
  }
  _2= v_arrayOffset;
  /* Scope('i'->ArgumentVariableNode) */
  /* Scope('stateful_self'->ArgumentVariableNode 'arrayOffset'->TemporaryVariableNode 'array'->SlotVariableNode 'lastIndex'->SlotVariableNode 'offset'->ArgumentVariableNode 'self'->ArgumentVariableNode 'firstIndex'->SlotVariableNode 'anObject'->ArgumentVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_56, 1, 0, ((oop *)_state1), 0);
  _line(163);
  _1=_sendv(s_downTo_do_, 3, _1, _2, _3);
  _1= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_lastIndex;  /* lastIndex */
  _2= l_55;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_lastIndex= _1;  /* lastIndex */
  _1= ((struct t_OrderedCollection *)((oop *)_state1)[2])->v_array;  /* array */
  _2= v_arrayOffset;
  _3= v_anObject;
  _line(165);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info57= { "at:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 168, 177, &__info53 };
static oop OrderedCollection__at_(oop v__closure, oop v_stateful_self, oop v_self, oop v_offset)
 {
  _enter(&__info57);
  oop v_arrayOffset= 0;
  oop _1= 0;
  oop _2= 0;
  (void)v_arrayOffset;
  _line(168);
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex;
  _2= v_offset;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  v_arrayOffset= _1;
  /* ifTrue:ifFalse: */
  /* and: */
  _1= v_offset;
  _2= l_58;
  if (1 & (long)_1) {
    _1= (((long)_1 >= (long)_2) ? v_true : v_false);
  } else _1= _sendv(s__3e_3d, 2, _1, _2);
  if (!_1) goto _l22;
 {
  _1= v_arrayOffset;
  _2= ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex;
  if (1 & (long)_1 & (long)_2) {
    _1= (((long)_1 < (long)_2) ? v_true : v_false);
  } else _1= _sendv(s__3c, 2, _1, _2);
 }
 _l22:;
  if (!_1) goto _l20;
 {
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _2= v_arrayOffset;
  _line(173);
  _1=_sendv(s_at_, 2, _1, _2);
 }
  goto _l21;
 _l20:;
 {
  _1= v_self;
  _2= v_offset;
  _line(174);
  _1=_sendv(s_errorOutOfBounds_, 2, _1, _2);
 }
 _l21:;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info59= { "at:put:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 177, 186, &__info57 };
static oop OrderedCollection__at_put_(oop v__closure, oop v_stateful_self, oop v_self, oop v_offset, oop v_anObject)
 {
  _enter(&__info59);
  oop v_arrayOffset= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  (void)v_arrayOffset;
  _line(177);
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex;
  _2= v_offset;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  v_arrayOffset= _1;
  /* ifTrue:ifFalse: */
  /* and: */
  _1= v_offset;
  _2= l_60;
  if (1 & (long)_1) {
    _1= (((long)_1 >= (long)_2) ? v_true : v_false);
  } else _1= _sendv(s__3e_3d, 2, _1, _2);
  if (!_1) goto _l25;
 {
  _1= v_arrayOffset;
  _2= ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex;
  if (1 & (long)_1 & (long)_2) {
    _1= (((long)_1 < (long)_2) ? v_true : v_false);
  } else _1= _sendv(s__3c, 2, _1, _2);
 }
 _l25:;
  if (!_1) goto _l23;
 {
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _2= v_arrayOffset;
  _3= v_anObject;
  _line(182);
  _1=_sendv(s_at_put_, 3, _1, _2, _3);
 }
  goto _l24;
 _l23:;
 {
  _1= v_self;
  _2= v_offset;
  _line(183);
  _1=_sendv(s_errorOutOfBounds_, 2, _1, _2);
 }
 _l24:;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info61= { "do:", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 186, 196, &__info59 };
static oop OrderedCollection__do_(oop v__closure, oop v_stateful_self, oop v_self, oop v_unaryBlock)
 {
  _enter(&__info61);
  oop v_index= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  (void)v_index;
  _line(186);
  _1= ((struct t_OrderedCollection *)v_stateful_self)->v_firstIndex;
  v_index= _1;
  /* whileTrue: */
  goto _l27;
 _l26:;
 {
  _1= v_unaryBlock;
  _2= ((struct t_OrderedCollection *)v_stateful_self)->v_array;
  _3= v_index;
  _line(192);
  _2=_sendv(s_at_, 2, _2, _3);
  _line(192);
  _1=_sendv(s_value_, 2, _1, _2);
  _1= v_index;
  _2= l_62;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  v_index= _1;
 }
 _l27:;
 {
  _1= v_index;
  _2= ((struct t_OrderedCollection *)v_stateful_self)->v_lastIndex;
  if (1 & (long)_1 & (long)_2) {
    _1= (((long)_1 < (long)_2) ? v_true : v_false);
  } else _1= _sendv(s__3c, 2, _1, _2);
 }
  if (_1) goto _l26;
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info63= { "asOrderedCollection", "OrderedCollection", "/Users/chazu/dev/c/idst-with-history/function/objects/OrderedCollection.st", 0, 196, 200, &__info61 };
static oop OrderedCollection__asOrderedCollection(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info63);
  oop _1= 0;
  _line(196);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "OrderedCollection.st", 0, 0, 0, &__info63 };
void __id__init__OrderedCollection(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
# define GC_add_roots _libid->gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info1);

  _sendv(s__5fimport_, 3, _libid->_object, "Objects", "__id__init__Objects");
  v__object= _libid->import("_object");
  v__vector= _libid->import("_vector");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_Magnitude= _libid->import("Magnitude");
  v_Number= _libid->import("Number");
  v_Integer= _libid->import("Integer");
  v_SmallInteger= _libid->import("SmallInteger");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_Array= _libid->import("Array");
  v_ByteArray= _libid->import("ByteArray");
  v_OrderedCollection= _libid->import("OrderedCollection");
  v_IdentitySet= _libid->import("IdentitySet");
  v_IdentityDictionary= _libid->import("IdentityDictionary");
  v_SlotDictionary= _libid->import("SlotDictionary");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_BlockClosure= _libid->import("BlockClosure");
  v_ReadStream= _libid->import("ReadStream");
  v_FileStream= _libid->import("FileStream");
  v_nil= _libid->import("nil");
  v_true= _libid->import("true");
  v_false= _libid->import("false");
  l_2= _sendv(s_value_5f_, 2, v_SmallInteger, 4);
  _libid->method(v_OrderedCollection, s_new, (_imp_t)OrderedCollection__new);
  l_4= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  _libid->method(v_OrderedCollection, s_new_, (_imp_t)OrderedCollection__new_);
  _libid->method(v_OrderedCollection, s_with_, (_imp_t)OrderedCollection__with_);
  _libid->method(v_OrderedCollection, s_with_with_, (_imp_t)OrderedCollection__with_with_);
  _libid->method(v_OrderedCollection, s_with_with_with_, (_imp_t)OrderedCollection__with_with_with_);
  _libid->method(v_OrderedCollection, s_size, (_imp_t)OrderedCollection__size);
  _libid->method(v_OrderedCollection, s__2c, (_imp_t)OrderedCollection___2c);
  _libid->method(v_OrderedCollection, s_add_, (_imp_t)OrderedCollection__add_);
  l_12= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  l_13= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_OrderedCollection, s_addFirst_, (_imp_t)OrderedCollection__addFirst_);
  l_15= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_OrderedCollection, s_addLast_, (_imp_t)OrderedCollection__addLast_);
  l_17= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  l_18= _sendv(s_value_5f_, 2, v_SmallInteger, 2);
  l_19= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_OrderedCollection, s_makeRoomAtFirst, (_imp_t)OrderedCollection__makeRoomAtFirst);
  l_21= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  l_22= _sendv(s_value_5f_, 2, v_SmallInteger, 2);
  l_23= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_OrderedCollection, s_makeRoomAtLast, (_imp_t)OrderedCollection__makeRoomAtLast);
  l_25= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  l_26= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_OrderedCollection, s_shiftToBeginning, (_imp_t)OrderedCollection__shiftToBeginning);
  l_29= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  l_30= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_OrderedCollection, s_shiftToEnd, (_imp_t)OrderedCollection__shiftToEnd);
  l_33= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  _libid->method(v_OrderedCollection, s_resetToBeginning, (_imp_t)OrderedCollection__resetToBeginning);
  _libid->method(v_OrderedCollection, s_resetToEnd, (_imp_t)OrderedCollection__resetToEnd);
  l_36= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_OrderedCollection, s_removeFirst, (_imp_t)OrderedCollection__removeFirst);
  l_38= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_OrderedCollection, s_removeLast, (_imp_t)OrderedCollection__removeLast);
  l_40= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  _libid->method(v_OrderedCollection, s_removeAll, (_imp_t)OrderedCollection__removeAll);
  _libid->method(v_OrderedCollection, s_indexOf_ifAbsent_, (_imp_t)OrderedCollection__indexOf_ifAbsent_);
  _libid->method(v_OrderedCollection, s_removeAll_ifAbsent_, (_imp_t)OrderedCollection__removeAll_ifAbsent_);
  _libid->method(v_OrderedCollection, s_remove_ifAbsent_, (_imp_t)OrderedCollection__remove_ifAbsent_);
  l_49= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  l_50= _sendv(s_value_5f_, 2, v_SmallInteger, 2);
  l_52= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_OrderedCollection, s_removeAtIndex_, (_imp_t)OrderedCollection__removeAtIndex_);
  l_54= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  l_55= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_OrderedCollection, s_insert_atIndex_, (_imp_t)OrderedCollection__insert_atIndex_);
  l_58= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  _libid->method(v_OrderedCollection, s_at_, (_imp_t)OrderedCollection__at_);
  l_60= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  _libid->method(v_OrderedCollection, s_at_put_, (_imp_t)OrderedCollection__at_put_);
  l_62= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_OrderedCollection, s_do_, (_imp_t)OrderedCollection__do_);
  _libid->method(v_OrderedCollection, s_asOrderedCollection, (_imp_t)OrderedCollection__asOrderedCollection);
  _leave();
}
