/* generated by Id 1.1 at 蚮 */
/* with the command: -I../../object/stage2/ -I. -g -g -c ProfiledMethod.st -o ProfiledMethod.o.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s_on_= 0;
static oop s_count= 0;
static oop s_do_= 0;
static oop s__5fname= 0;
static oop s_value_5f_= 0;
static oop s__5fimport_= 0;
static oop s_space= 0;
static oop s_report= 0;
static oop s_new_= 0;
static oop s__5fmethod= 0;
static oop s_release= 0;
static oop s_ifTrue_= 0;
static oop s_type= 0;
static oop s__2a= 0;
static oop s_and_= 0;
static oop s_value= 0;
static oop s_nextPut_= 0;
static oop s__3e= 0;
static oop s_new_5f_= 0;
static oop s_new= 0;
static oop s_withMethod_5f_= 0;
static oop s_reportOn_tally_= 0;
static oop s__2b= 0;
static oop s_function_5f_arity_5f_outer_state_nlr_5f_= 0;
static oop s_printOn_base_width_padded_= 0;
static oop s__2f_2f= 0;
static oop s_nextPutAll_= 0;
static oop s_name= 0;
static oop s_delete= 0;
static oop s_exchange_= 0;
static oop s_ifTrue_ifFalse_= 0;
static oop s_next= 0;
static oop s_setMethod_5f_count_= 0;
static oop s_statisticalProfile= 0;
static oop s_perform_every_= 0;
static oop s_increment= 0;
static oop s_value_= 0;
static oop s_sort= 0;
static oop s_tally= 0;
static oop s_cr= 0;
static oop s__5ftype= 0;
static oop s_size_5f_value_5f_= 0;
static oop s_whileTrue= 0;
static oop s_profilerTick= 0;
static oop s_asInteger= 0;
static oop s__5c_5c= 0;
static oop s_contents= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "on:", &s_on_ },
  { "count", &s_count },
  { "do:", &s_do_ },
  { "_name", &s__5fname },
  { "value_:", &s_value_5f_ },
  { "_import:", &s__5fimport_ },
  { "space", &s_space },
  { "report", &s_report },
  { "new:", &s_new_ },
  { "_method", &s__5fmethod },
  { "release", &s_release },
  { "ifTrue:", &s_ifTrue_ },
  { "type", &s_type },
  { "*", &s__2a },
  { "and:", &s_and_ },
  { "value", &s_value },
  { "nextPut:", &s_nextPut_ },
  { ">", &s__3e },
  { "new_:", &s_new_5f_ },
  { "new", &s_new },
  { "withMethod_:", &s_withMethod_5f_ },
  { "reportOn:tally:", &s_reportOn_tally_ },
  { "+", &s__2b },
  { "function_:arity_:outer:state:nlr_:", &s_function_5f_arity_5f_outer_state_nlr_5f_ },
  { "printOn:base:width:padded:", &s_printOn_base_width_padded_ },
  { "//", &s__2f_2f },
  { "nextPutAll:", &s_nextPutAll_ },
  { "name", &s_name },
  { "delete", &s_delete },
  { "exchange:", &s_exchange_ },
  { "ifTrue:ifFalse:", &s_ifTrue_ifFalse_ },
  { "next", &s_next },
  { "setMethod_:count:", &s_setMethod_5f_count_ },
  { "statisticalProfile", &s_statisticalProfile },
  { "perform:every:", &s_perform_every_ },
  { "increment", &s_increment },
  { "value:", &s_value_ },
  { "sort", &s_sort },
  { "tally", &s_tally },
  { "cr", &s_cr },
  { "_type", &s__5ftype },
  { "size_:value_:", &s_size_5f_value_5f_ },
  { "whileTrue", &s_whileTrue },
  { "profilerTick", &s_profilerTick },
  { "asInteger", &s_asInteger },
  { "\\\\", &s__5c_5c },
  { "contents", &s_contents },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Date {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__microseconds;
};
struct t_Time {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__nanoseconds;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargeInteger {
  struct _vtable *_vtable[0];
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t_Association {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t_Link {
  struct _vtable *_vtable[0];
  oop v_prevLink;
  oop v_nextLink;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_LinkedList {
  struct _vtable *_vtable[0];
  oop v_firstLink;
  oop v_lastLink;
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__oops;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_OrderedCollection {
  struct _vtable *_vtable[0];
  oop v_firstIndex;
  oop v_lastIndex;
  oop v_array;
};
struct t_IdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Set {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_IdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Dictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_FastIdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_SlotDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_MemoDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_ProfiledMethod {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_count;
  oop v_next;
};
struct t_SinkStream {
  struct _vtable *_vtable[0];
};
struct t_ReadStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_WriteStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_writeLimit;
};
struct t_FileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
};
struct t_ConsoleFileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
  oop v__prompt;
};
struct t_File {
  struct _vtable *_vtable[0];
  oop v__fd;
  oop v_name;
};
struct t_Function {
  struct _vtable *_vtable[0];
};
struct t_Random {
  struct _vtable *_vtable[0];
  oop v_seed;
  oop v_a;
  oop v_m;
  oop v_q;
  oop v_r;
};
struct t_OS {
  struct _vtable *_vtable[0];
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
struct t_CharacterClass {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_FastIdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_SharedFile {
  struct _vtable *_vtable[0];
  oop v__fd;
  oop v_name;
  oop v_readStream;
};
static oop l_5= 0;
static oop l_10= 0;
static oop l_13= 0;
static oop l_16= 0;
static oop l_17= 0;
static oop l_18= 0;
static oop l_19= 0;
static oop l_20= 0;
static oop l_21= 0;
static oop l_24= 0;
static oop l_32= 0;
static oop l_33= 0;
static oop l_34= 0;
static oop l_37= 0;
static oop v__object= 0;
static oop v__vector= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_Magnitude= 0;
static oop v_Number= 0;
static oop v_Float= 0;
static oop v_Integer= 0;
static oop v_SmallInteger= 0;
static oop v_Symbol= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_ByteArray= 0;
static oop v_String= 0;
static oop v_IdentitySet= 0;
static oop v_IdentityDictionary= 0;
static oop v_SlotDictionary= 0;
static oop v_StaticBlockClosure= 0;
static oop v_BlockClosure= 0;
static oop v_ProfiledMethod= 0;
static oop v_ReadStream= 0;
static oop v_WriteStream= 0;
static oop v_FileStream= 0;
static oop v_File= 0;
static oop v_nil= 0;
static oop v_true= 0;
static oop v_false= 0;
static oop v_ProfiledMethods= 0;
static double d_33= 0.001;
#include "sigalrm.h"
static struct __methodinfo __info1= { "new", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 7, 14, 0 };
static oop ProfiledMethod__new(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info1);
  oop _1= 0;
  _line(7);
 {
# define self ((struct t_ProfiledMethod *)v_self)

    oop clone= (oop)malloc(sizeof(oop) + sizeof(*self)) + 1;
    clone->_vtable[-1]= self->_vtable[-1];
    _return(clone);

# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info2= { "delete", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 14, 19, &__info1 };
static oop ProfiledMethod__delete(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info2);
  oop _1= 0;
  _line(14);
 {
# define self ((struct t_ProfiledMethod *)v_self)

    free(v_self - 1);

# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info3= { "release", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 19, 25, &__info2 };
static oop ProfiledMethod__release(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info3);
  oop _1= 0;
  oop _2= 0;
  _line(19);
  /* ifTrue: */
  _1= 0;
  _2= ((struct t_ProfiledMethod *)v_stateful_self)->v_next;
  if (!_2) goto _l1;
 {
  _1= ((struct t_ProfiledMethod *)v_stateful_self)->v_next;
  _line(21);
  _1=_sendv(s_release, 1, _1);
 }
 _l1:;
  _1= v_self;
  _line(22);
  _1=_sendv(s_delete, 1, _1);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info4= { "withMethod_:", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 27, 44, &__info3 };
static oop ProfiledMethod__withMethod_5f_(oop v__closure, oop v_stateful_self, oop v_self, oop v__mi)
 {
  _enter(&__info4);
  oop _1= 0;
  _line(27);
 {
# define self ((struct t_ProfiledMethod *)v_self)

	struct __methodinfo *mi= (struct __methodinfo *)v__mi;
	if (mi->meta) return (oop)mi->meta;
    
# undef self
 }
  _1= 0;
  _1= v_self;
  _line(33);
  _1=_sendv(s_new, 1, _1);
  v_self= _1;
  v_stateful_self= _1;
  _1= v__mi;
  ((struct t_ProfiledMethod *)v_stateful_self)->v__method= _1;
  _1= l_5;
  ((struct t_ProfiledMethod *)v_stateful_self)->v_count= _1;
  _1= v_ProfiledMethods;
  ((struct t_ProfiledMethod *)v_stateful_self)->v_next= _1;
  _1= v_self;
  v_ProfiledMethods= _1;
  _libid->export("ProfiledMethods", v_ProfiledMethods);
 {
# define self ((struct t_ProfiledMethod *)v_self)

	struct __methodinfo *mi= (struct __methodinfo *)v__mi;
	mi->meta= (void *)self;
    
# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info6= { "_method", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 44, 45, &__info4 };
static oop ProfiledMethod___5fmethod(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info6);
  oop _1= 0;
  _line(44);
  _1= ((struct t_ProfiledMethod *)v_stateful_self)->v__method;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info7= { "count", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 45, 46, &__info6 };
static oop ProfiledMethod__count(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info7);
  oop _1= 0;
  _line(45);
  _1= ((struct t_ProfiledMethod *)v_stateful_self)->v_count;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info8= { "next", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 46, 48, &__info7 };
static oop ProfiledMethod__next(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info8);
  oop _1= 0;
  _line(46);
  _1= ((struct t_ProfiledMethod *)v_stateful_self)->v_next;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info9= { "increment", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 48, 50, &__info8 };
static oop ProfiledMethod__increment(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info9);
  oop _1= 0;
  oop _2= 0;
  _line(48);
  _1= ((struct t_ProfiledMethod *)v_stateful_self)->v_count;
  _2= l_10;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  ((struct t_ProfiledMethod *)v_stateful_self)->v_count= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info11= { "do:", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 50, 58, &__info9 };
static oop ProfiledMethod__do_(oop v__closure, oop v_stateful_self, oop v_self, oop v_unaryBlock)
 {
  _enter(&__info11);
  oop v_me= 0;
  oop _1= 0;
  oop _2= 0;
  (void)v_me;
  _line(50);
  _1= v_self;
  v_me= _1;
  /* whileTrue */
 _l2:;
 {
  _1= v_unaryBlock;
  _2= v_me;
  _line(54);
  _1=_sendv(s_value_, 2, _1, _2);
  _1= v_me;
  _line(55);
  _1=_sendv(s_next, 1, _1);
  v_me= _1;
 }
  if (_1) goto _l2;
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info14= { "[] report", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 58, 69, &__info11 };
static oop b_14(oop v__closure, oop v__self, oop v_method)
 {
  _enter(&__info14);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(64);
  _1= v_method;
  _2= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* stream */
  _3= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[2];  /* total */
  _line(64);
  _1=_sendv(s_reportOn_tally_, 3, _1, _2, _3);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info12= { "report", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 58, 69, &__info14 };
static oop ProfiledMethod__report(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info12);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 3);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(58);
  _1= v_self;
  _line(61);
  _1=_sendv(s_sort, 1, _1);
  _1= v_self;
  _line(62);
  _1=_sendv(s_tally, 1, _1);
  ((oop *)_state1)[2]= _1;  /* total */
  _1= v_WriteStream;
  _2= v_String;
  _3= l_13;
  _line(63);
  _2=_sendv(s_new_, 2, _2, _3);
  _line(63);
  _1=_sendv(s_on_, 2, _1, _2);
  ((oop *)_state1)[1]= _1;  /* stream */
  _1= v_self;
  /* Scope('method'->ArgumentVariableNode) */
  /* Scope('next'->SlotVariableNode '_method'->SlotVariableNode 'count'->SlotVariableNode 'stateful_self'->ArgumentVariableNode 'stream'->TemporaryVariableNode 'self'->ArgumentVariableNode 'total'->TemporaryVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _2= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_14, 1, 0, ((oop *)_state1), 0);
  _line(64);
  _1=_sendv(s_do_, 2, _1, _2);
  _1= v_self;
  _line(65);
  _1=_sendv(s_release, 1, _1);
  _1= ((oop *)_state1)[1];  /* stream */
  _line(66);
  _1=_sendv(s_contents, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info15= { "reportOn:tally:", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 69, 81, &__info12 };
static oop ProfiledMethod__reportOn_tally_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream, oop v_tally)
 {
  _enter(&__info15);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  oop _5= 0;
  _line(69);
  _1= ((struct t_ProfiledMethod *)v_stateful_self)->v_count;
  _2= v_aStream;
  _3= l_16;
  _4= l_17;
  _5= l_18;
  _line(71);
  _1=_sendv(s_printOn_base_width_padded_, 5, _1, _2, _3, _4, _5);
  _1= ((struct t_ProfiledMethod *)v_stateful_self)->v_count;
  _2= l_19;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= (_l * _r);
    if ((1 & (long)_1) && ((_r == 0) || (_s / _r == _l)) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2a, 2, _1, _2);
  }
  _2= v_tally;
  _1= _sendv(s__2f_2f, 2, _1, _2);
  _2= v_aStream;
  _3= l_16;
  _4= l_20;
  _5= l_18;
  _line(72);
  _1=_sendv(s_printOn_base_width_padded_, 5, _1, _2, _3, _4, _5);
  _1= v_aStream;
  _2= l_21;
  _line(74);
  _sendv(s_nextPut_, 2, _1, _2);
  _sendv(s_space, 1, _1);
  _2= v_self;
  _line(75);
  _2=_sendv(s_type, 1, _2);
  _sendv(s_nextPutAll_, 2, _1, _2);
  _sendv(s_space, 1, _1);
  _2= v_self;
  _line(76);
  _2=_sendv(s_name, 1, _2);
  _sendv(s_nextPutAll_, 2, _1, _2);
  _1=_sendv(s_cr, 1, _1);
  _1= ((struct t_ProfiledMethod *)v_stateful_self)->v_count;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info22= { "sort", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 81, 90, &__info15 };
static oop ProfiledMethod__sort(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info22);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(81);
  /* ifTrue: */
  _1= 0;
  /* and: */
  _2= ((struct t_ProfiledMethod *)v_stateful_self)->v_next;
  if (!_2) goto _l4;
 {
  _2= ((struct t_ProfiledMethod *)v_stateful_self)->v_next;
  _line(83);
  _2=_sendv(s_sort, 1, _2);
  _3= ((struct t_ProfiledMethod *)v_stateful_self)->v_count;
  if (1 & (long)_2 & (long)_3) {
    _2= (((long)_2 > (long)_3) ? v_true : v_false);
  } else _2= _sendv(s__3e, 2, _2, _3);
 }
 _l4:;
  if (!_2) goto _l3;
 {
  _1= v_self;
  _2= ((struct t_ProfiledMethod *)v_stateful_self)->v_next;
  _line(85);
  _1=_sendv(s_exchange_, 2, _1, _2);
  _1= ((struct t_ProfiledMethod *)v_stateful_self)->v_next;
  _line(86);
  _1=_sendv(s_sort, 1, _1);
 }
 _l3:;
  _1= ((struct t_ProfiledMethod *)v_stateful_self)->v_count;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info23= { "tally", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 90, 95, &__info22 };
static oop ProfiledMethod__tally(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info23);
  oop _1= 0;
  oop _2= 0;
  _line(90);
  _1= ((struct t_ProfiledMethod *)v_stateful_self)->v_count;
  /* ifTrue:ifFalse: */
  _2= ((struct t_ProfiledMethod *)v_stateful_self)->v_next;
  if (!_2) goto _l5;
 {
  _2= ((struct t_ProfiledMethod *)v_stateful_self)->v_next;
  _line(92);
  _2=_sendv(s_count, 1, _2);
 }
  goto _l6;
 _l5:;
 {
  _2= l_24;
 }
 _l6:;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info25= { "exchange:", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 95, 105, &__info23 };
static oop ProfiledMethod__exchange_(oop v__closure, oop v_stateful_self, oop v_self, oop v_other)
 {
  _enter(&__info25);
  oop v__m= 0;
  oop v_c= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  (void)v__m;
  (void)v_c;
  _line(95);
  _1= v_other;
  _line(98);
  _1=_sendv(s__5fmethod, 1, _1);
  v__m= _1;
  _1= v_other;
  _line(99);
  _1=_sendv(s_count, 1, _1);
  v_c= _1;
  _1= v_other;
  _2= ((struct t_ProfiledMethod *)v_stateful_self)->v__method;
  _3= ((struct t_ProfiledMethod *)v_stateful_self)->v_count;
  _line(100);
  _1=_sendv(s_setMethod_5f_count_, 3, _1, _2, _3);
  _1= v__m;
  ((struct t_ProfiledMethod *)v_stateful_self)->v__method= _1;
  _1= v_c;
  ((struct t_ProfiledMethod *)v_stateful_self)->v_count= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info26= { "setMethod_:count:", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 105, 111, &__info25 };
static oop ProfiledMethod__setMethod_5f_count_(oop v__closure, oop v_stateful_self, oop v_self, oop v__m, oop v_c)
 {
  _enter(&__info26);
  oop _1= 0;
  _line(105);
  _1= v__m;
  ((struct t_ProfiledMethod *)v_stateful_self)->v__method= _1;
  _1= v_c;
  ((struct t_ProfiledMethod *)v_stateful_self)->v_count= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info27= { "type", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 111, 112, &__info26 };
static oop ProfiledMethod__type(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info27);
  oop _1= 0;
  oop _2= 0;
  _line(111);
  _1= v_String;
  _2= v_self;
  _line(111);
  _2=_sendv(s__5ftype, 1, _2);
  _line(111);
  _1=_sendv(s_value_5f_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info28= { "name", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 112, 114, &__info27 };
static oop ProfiledMethod__name(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info28);
  oop _1= 0;
  oop _2= 0;
  _line(112);
  _1= v_String;
  _2= v_self;
  _line(112);
  _2=_sendv(s__5fname, 1, _2);
  _line(112);
  _1=_sendv(s_value_5f_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info29= { "_type", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 114, 115, &__info28 };
static oop ProfiledMethod___5ftype(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info29);
  oop _1= 0;
  _line(114);
 {
# define self ((struct t_ProfiledMethod *)v_self)
 _return((oop)((struct __methodinfo *)self->v__method)->type); 
# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info30= { "_name", "ProfiledMethod", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 115, 117, &__info29 };
static oop ProfiledMethod___5fname(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info30);
  oop _1= 0;
  _line(115);
 {
# define self ((struct t_ProfiledMethod *)v_self)
 _return((oop)((struct __methodinfo *)self->v__method)->name); 
# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info31= { "statisticalProfile", "StaticBlockClosure", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 117, 128, &__info30 };
static oop StaticBlockClosure__statisticalProfile(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info31);
  oop v_methods= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  (void)v_methods;
  _line(117);
  _1= v_self;
  _2= l_32;
  _3= l_33;
  _line(120);
  _1=_sendv(s_perform_every_, 3, _1, _2, _3);
  _1= v_self;
  _line(121);
  _1=_sendv(s_value, 1, _1);
  _1= v_self;
  _2= v_nil;
  _3= l_34;
  _line(122);
  _1=_sendv(s_perform_every_, 3, _1, _2, _3);
  _1= v_ProfiledMethods;
  v_methods= _1;
  _1= v_nil;
  v_ProfiledMethods= _1;
  _libid->export("ProfiledMethods", v_ProfiledMethods);
  _1= v_methods;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info35= { "profilerTick", "Object", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 128, 136, &__info31 };
static oop Object__profilerTick(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info35);
  oop v__mi= 0;
  oop v_mi= 0;
  oop _1= 0;
  oop _2= 0;
  (void)v__mi;
  (void)v_mi;
  _line(128);
 {
# define self ((struct t_Object *)v_self)
 if (!(v__mi= _libid->methodAt(1))) { _return(0); } 
# undef self
 }
  _1= 0;
  _1= v_ProfiledMethod;
  _2= v__mi;
  _line(132);
  _1=_sendv(s_withMethod_5f_, 2, _1, _2);
  v_mi= _1;
  _1= v_mi;
  _line(133);
  _1=_sendv(s_increment, 1, _1);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info36= { "perform:every:", "Object", "/Users/chazu/dev/c/idst-with-history/function/objects/ProfiledMethod.st", 0, 136, 166, &__info35 };
static oop Object__perform_every_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aSymbol, oop v_nSeconds)
 {
  _enter(&__info36);
  oop v_s= 0;
  oop v_us= 0;
  oop _1= 0;
  oop _2= 0;
  (void)v_s;
  (void)v_us;
  _line(136);
  _1= v_nSeconds;
  _line(139);
  _1=_sendv(s_asInteger, 1, _1);
  v_s= _1;
  _1= v_nSeconds;
  _2= l_37;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= (_l * _r);
    if ((1 & (long)_1) && ((_r == 0) || (_s / _r == _l)) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2a, 2, _1, _2);
  }
  _line(140);
  _1=_sendv(s_asInteger, 1, _1);
  _2= l_37;
  _1= _sendv(s__5c_5c, 2, _1, _2);
  v_us= _1;
 {
# define self ((struct t_Object *)v_self)

#     if defined(WIN32)
	(void)sigalrm;
#     else
	long s=  (long)v_s  >> 1;
	long us= (long)v_us >> 1;
	struct itimerval interval= { { s, us }, { s, us } };
	sigalrmReceiver= v_self;
	sigalrmSelector= v_aSymbol;
	if (v_aSymbol)
	  {
	    enableStatisticalProfile();
	    signal(SIGALRM, sigalrm);
	    setitimer(ITIMER_REAL, &interval, 0);
	  }
	else
	  {
	    signal(SIGALRM, SIG_IGN);
	    setitimer(ITIMER_REAL, 0, 0);
	    disableStatisticalProfile();
	  }
#     endif
    
# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "ProfiledMethod.st", 0, 0, 0, &__info36 };
void __id__init__ProfiledMethod(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
# define GC_add_roots _libid->gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info1);

  _sendv(s__5fimport_, 3, _libid->_object, "Object", "__id__init__Object");
  v__object= _libid->import("_object");
  v__vector= _libid->import("_vector");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_Magnitude= _libid->import("Magnitude");
  v_Number= _libid->import("Number");
  v_Float= _libid->import("Float");
  v_Integer= _libid->import("Integer");
  v_SmallInteger= _libid->import("SmallInteger");
  v_Symbol= _libid->import("Symbol");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_ByteArray= _libid->import("ByteArray");
  v_String= _libid->import("String");
  v_IdentitySet= _libid->import("IdentitySet");
  v_IdentityDictionary= _libid->import("IdentityDictionary");
  v_SlotDictionary= _libid->import("SlotDictionary");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_BlockClosure= _libid->import("BlockClosure");
  v_ProfiledMethod= _libid->import("ProfiledMethod");
  v_ReadStream= _libid->import("ReadStream");
  v_WriteStream= _libid->import("WriteStream");
  v_FileStream= _libid->import("FileStream");
  v_File= _libid->import("File");
  v_nil= _libid->import("nil");
  v_true= _libid->import("true");
  v_false= _libid->import("false");
  _libid->method(v_ProfiledMethod, s_new, (_imp_t)ProfiledMethod__new);
  _libid->method(v_ProfiledMethod, s_delete, (_imp_t)ProfiledMethod__delete);
  _libid->method(v_ProfiledMethod, s_release, (_imp_t)ProfiledMethod__release);
 {
  oop _1= 0;
  _1= v_nil;
  v_ProfiledMethods= _1;
  _libid->export("ProfiledMethods", v_ProfiledMethods);
 }
  l_5= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  _libid->method(v_ProfiledMethod, s_withMethod_5f_, (_imp_t)ProfiledMethod__withMethod_5f_);
  _libid->method(v_ProfiledMethod, s__5fmethod, (_imp_t)ProfiledMethod___5fmethod);
  _libid->method(v_ProfiledMethod, s_count, (_imp_t)ProfiledMethod__count);
  _libid->method(v_ProfiledMethod, s_next, (_imp_t)ProfiledMethod__next);
  l_10= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_ProfiledMethod, s_increment, (_imp_t)ProfiledMethod__increment);
  _libid->method(v_ProfiledMethod, s_do_, (_imp_t)ProfiledMethod__do_);
  l_13= _sendv(s_value_5f_, 2, v_SmallInteger, 1024);
  _libid->method(v_ProfiledMethod, s_report, (_imp_t)ProfiledMethod__report);
  l_16= _sendv(s_value_5f_, 2, v_SmallInteger, 10);
  l_17= _sendv(s_value_5f_, 2, v_SmallInteger, 5);
  l_18= _sendv(s_value_5f_, 2, v_SmallInteger, 32);
  l_19= _sendv(s_value_5f_, 2, v_SmallInteger, 100);
  l_20= _sendv(s_value_5f_, 2, v_SmallInteger, 4);
  l_21= _sendv(s_value_5f_, 2, v_SmallInteger, 37);
  _libid->method(v_ProfiledMethod, s_reportOn_tally_, (_imp_t)ProfiledMethod__reportOn_tally_);
  _libid->method(v_ProfiledMethod, s_sort, (_imp_t)ProfiledMethod__sort);
  l_24= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  _libid->method(v_ProfiledMethod, s_tally, (_imp_t)ProfiledMethod__tally);
  _libid->method(v_ProfiledMethod, s_exchange_, (_imp_t)ProfiledMethod__exchange_);
  _libid->method(v_ProfiledMethod, s_setMethod_5f_count_, (_imp_t)ProfiledMethod__setMethod_5f_count_);
  _libid->method(v_ProfiledMethod, s_type, (_imp_t)ProfiledMethod__type);
  _libid->method(v_ProfiledMethod, s_name, (_imp_t)ProfiledMethod__name);
  _libid->method(v_ProfiledMethod, s__5ftype, (_imp_t)ProfiledMethod___5ftype);
  _libid->method(v_ProfiledMethod, s__5fname, (_imp_t)ProfiledMethod___5fname);
  l_32= _sendv(s_size_5f_value_5f_, 3, v_Symbol, 12, "profilerTick");
  l_33= _sendv(s_value_5f_, 2, v_Float, &d_33);
  l_34= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  _libid->method(v_StaticBlockClosure, s_statisticalProfile, (_imp_t)StaticBlockClosure__statisticalProfile);
  _libid->method(v_Object, s_profilerTick, (_imp_t)Object__profilerTick);
  l_37= _sendv(s_value_5f_, 2, v_SmallInteger, 1000000);
  _libid->method(v_Object, s_perform_every_, (_imp_t)Object__perform_every_);
  _leave();
}
