/* generated by Id 1.1 at èšÕ */
/* with the command: -I../../object/stage2/ -I. -g -g -c Symbol.st -o Symbol.o.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s_isKeyword= 0;
static oop s_do_= 0;
static oop s_value_5f_= 0;
static oop s__5fimport_= 0;
static oop s__5fbytes= 0;
static oop s__3d= 0;
static oop s_hash= 0;
static oop s_ifTrue_= 0;
static oop s_to_do_= 0;
static oop s_isSymbol= 0;
static oop s_asSymbol= 0;
static oop s_intern_5f_= 0;
static oop s_nextPut_= 0;
static oop s_new_5f_= 0;
static oop s__2d= 0;
static oop s_asString= 0;
static oop s__2c= 0;
static oop s_beginsWith_= 0;
static oop s__5fintegerValue= 0;
static oop s_intern_5f_size_5f_= 0;
static oop s__5fstringValue= 0;
static oop s_size= 0;
static oop s_endsWith_= 0;
static oop s_append_= 0;
static oop s_between_and_= 0;
static oop s__5fat_5f_= 0;
static oop s_identityHash= 0;
static oop s__3d_3d= 0;
static oop s_nextPutAll_= 0;
static oop s_function_5f_arity_5f_outer_state_nlr_5f_= 0;
static oop s_printOn_= 0;
static oop s_bePrototype_= 0;
static oop s_value_= 0;
static oop s_intern_= 0;
static oop s_at_= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "isKeyword", &s_isKeyword },
  { "do:", &s_do_ },
  { "value_:", &s_value_5f_ },
  { "_import:", &s__5fimport_ },
  { "_bytes", &s__5fbytes },
  { "=", &s__3d },
  { "hash", &s_hash },
  { "ifTrue:", &s_ifTrue_ },
  { "to:do:", &s_to_do_ },
  { "isSymbol", &s_isSymbol },
  { "asSymbol", &s_asSymbol },
  { "intern_:", &s_intern_5f_ },
  { "nextPut:", &s_nextPut_ },
  { "new_:", &s_new_5f_ },
  { "-", &s__2d },
  { "asString", &s_asString },
  { ",", &s__2c },
  { "beginsWith:", &s_beginsWith_ },
  { "_integerValue", &s__5fintegerValue },
  { "intern_:size_:", &s_intern_5f_size_5f_ },
  { "_stringValue", &s__5fstringValue },
  { "size", &s_size },
  { "endsWith:", &s_endsWith_ },
  { "append:", &s_append_ },
  { "between:and:", &s_between_and_ },
  { "_at_:", &s__5fat_5f_ },
  { "identityHash", &s_identityHash },
  { "==", &s__3d_3d },
  { "nextPutAll:", &s_nextPutAll_ },
  { "function_:arity_:outer:state:nlr_:", &s_function_5f_arity_5f_outer_state_nlr_5f_ },
  { "printOn:", &s_printOn_ },
  { "bePrototype:", &s_bePrototype_ },
  { "value:", &s_value_ },
  { "intern:", &s_intern_ },
  { "at:", &s_at_ },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Date {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__microseconds;
};
struct t_Time {
  struct _vtable *_vtable[0];
  oop v__seconds;
  oop v__nanoseconds;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargeInteger {
  struct _vtable *_vtable[0];
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t_Association {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t_Link {
  struct _vtable *_vtable[0];
  oop v_prevLink;
  oop v_nextLink;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_LinkedList {
  struct _vtable *_vtable[0];
  oop v_firstLink;
  oop v_lastLink;
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__oops;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_OrderedCollection {
  struct _vtable *_vtable[0];
  oop v_firstIndex;
  oop v_lastIndex;
  oop v_array;
};
struct t_IdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Set {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_IdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_Dictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_FastIdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_lists;
};
struct t_SlotDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_MemoDictionary {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__tally;
  oop v__keys;
  oop v__values;
  oop v_default;
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_ProfiledMethod {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_count;
  oop v_next;
};
struct t_SinkStream {
  struct _vtable *_vtable[0];
};
struct t_ReadStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
};
struct t_WriteStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_writeLimit;
};
struct t_FileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
};
struct t_ConsoleFileStream {
  struct _vtable *_vtable[0];
  oop v_collection;
  oop v_position;
  oop v_readLimit;
  oop v_file;
  oop v__prompt;
};
struct t_File {
  struct _vtable *_vtable[0];
  oop v__fd;
  oop v_name;
};
struct t_Function {
  struct _vtable *_vtable[0];
};
struct t_Random {
  struct _vtable *_vtable[0];
  oop v_seed;
  oop v_a;
  oop v_m;
  oop v_q;
  oop v_r;
};
struct t_OS {
  struct _vtable *_vtable[0];
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
static oop l_16= 0;
static oop l_17= 0;
static oop l_23= 0;
static oop l_24= 0;
static oop l_26= 0;
static oop l_28= 0;
static oop l_29= 0;
static oop v__object= 0;
static oop v__vector= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_Magnitude= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_SmallInteger= 0;
static oop v_Symbol= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_ByteArray= 0;
static oop v_String= 0;
static oop v_IdentitySet= 0;
static oop v_IdentityDictionary= 0;
static oop v_SlotDictionary= 0;
static oop v_StaticBlockClosure= 0;
static oop v_BlockClosure= 0;
static oop v_ReadStream= 0;
static oop v_FileStream= 0;
static oop v_nil= 0;
static oop v_true= 0;
static oop v_false= 0;
static struct __methodinfo __info1= { "isSymbol", "Object", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 23, 24, 0 };
static oop Object__isSymbol(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info1);
  oop _1= 0;
  _line(23);
  _1= v_false;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info2= { "isSymbol", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 24, 26, &__info1 };
static oop Symbol__isSymbol(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info2);
  oop _1= 0;
  _line(24);
  _1= v_true;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info3= { "intern_:size_:", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 26, 34, &__info2 };
static oop Symbol__intern_5f_size_5f_(oop v__closure, oop v_stateful_self, oop v_self, oop v__string, oop v__stringSize)
 {
  _enter(&__info3);
  oop _1= 0;
  _line(26);
 {
# define self ((struct t_Symbol *)v_self)

    char *buf= (char *)alloca((long)v__stringSize + 1);
    memcpy((void *)buf, (void *)v__string, (long)v__stringSize);
    buf[(long)v__stringSize]= '\0';
    _return _libid->intern(buf);

# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info4= { "intern_:", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 34, 41, &__info3 };
static oop Symbol__intern_5f_(oop v__closure, oop v_stateful_self, oop v_self, oop v__string)
 {
  _enter(&__info4);
  oop v__stringSize= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  (void)v__stringSize;
  _line(34);
 {
# define self ((struct t_Symbol *)v_self)
 v__stringSize= (oop)(long)strlen((char *)v__string); 
# undef self
 }
  _1= 0;
  _1= v_self;
  _2= v__string;
  _3= v__stringSize;
  _line(38);
  _1=_sendv(s_intern_5f_size_5f_, 3, _1, _2, _3);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info5= { "intern:", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 41, 46, &__info4 };
static oop Symbol__intern_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aString)
 {
  _enter(&__info5);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(41);
  _1= v_self;
  _2= v_aString;
  _line(43);
  _2=_sendv(s__5fstringValue, 1, _2);
  _3= v_aString;
  _line(43);
  _3=_sendv(s_size, 1, _3);
  _line(43);
  _3=_sendv(s__5fintegerValue, 1, _3);
  _line(43);
  _1=_sendv(s_intern_5f_size_5f_, 3, _1, _2, _3);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info6= { "_bytes", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 46, 47, &__info5 };
static oop Symbol___5fbytes(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info6);
  oop _1= 0;
  _line(46);
  _1= ((struct t_Symbol *)v_stateful_self)->v__elements;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info7= { "size", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 47, 49, &__info6 };
static oop Symbol__size(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info7);
  oop _1= 0;
  oop _2= 0;
  _line(47);
  _1= v_SmallInteger;
  _2= ((struct t_Symbol *)v_stateful_self)->v__size;
  _line(47);
  _1=_sendv(s_value_5f_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info8= { "_stringValue", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 49, 51, &__info7 };
static oop Symbol___5fstringValue(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info8);
  oop _1= 0;
  _line(49);
  _1= ((struct t_Symbol *)v_stateful_self)->v__elements;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info9= { "asSymbol", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 51, 52, &__info8 };
static oop Symbol__asSymbol(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info9);
  oop _1= 0;
  _line(51);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info10= { "asString", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 52, 54, &__info9 };
static oop Symbol__asString(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info10);
  oop _1= 0;
  oop _2= 0;
  _line(52);
  _1= v_String;
  _2= ((struct t_Symbol *)v_stateful_self)->v__elements;
  _line(52);
  _1=_sendv(s_value_5f_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info11= { "beginsWith:", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 54, 55, &__info10 };
static oop Symbol__beginsWith_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aString)
 {
  _enter(&__info11);
  oop _1= 0;
  oop _2= 0;
  _line(54);
  _1= v_self;
  _line(54);
  _1=_sendv(s_asString, 1, _1);
  _2= v_aString;
  _line(54);
  _1=_sendv(s_beginsWith_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info12= { "endsWith:", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 55, 57, &__info11 };
static oop Symbol__endsWith_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aString)
 {
  _enter(&__info12);
  oop _1= 0;
  oop _2= 0;
  _line(55);
  _1= v_self;
  _line(55);
  _1=_sendv(s_asString, 1, _1);
  _2= v_aString;
  _line(55);
  _1=_sendv(s_endsWith_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info13= { ",", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 57, 58, &__info12 };
static oop Symbol___2c(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStringOrSymbol)
 {
  _enter(&__info13);
  oop _1= 0;
  oop _2= 0;
  _line(57);
  _1= v_self;
  _line(57);
  _1=_sendv(s_asString, 1, _1);
  _2= v_aStringOrSymbol;
  _line(57);
  _2=_sendv(s_asString, 1, _2);
  _line(57);
  _1=_sendv(s__2c, 2, _1, _2);
  _line(57);
  _1=_sendv(s_asSymbol, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info14= { "append:", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 58, 60, &__info13 };
static oop Symbol__append_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStringOrSymbol)
 {
  _enter(&__info14);
  oop _1= 0;
  oop _2= 0;
  _line(58);
  _1= v_self;
  _line(58);
  _1=_sendv(s_asString, 1, _1);
  _2= v_aStringOrSymbol;
  _line(58);
  _2=_sendv(s_asString, 1, _2);
  _line(58);
  _1=_sendv(s__2c, 2, _1, _2);
  _line(58);
  _1=_sendv(s_asSymbol, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info15= { "at:", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 60, 62, &__info14 };
static oop Symbol__at_(oop v__closure, oop v_stateful_self, oop v_self, oop v_offset)
 {
  _enter(&__info15);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  oop _5= 0;
  _line(60);
  /* ifTrue: */
  _1= 0;
  _2= v_offset;
  _3= l_16;
  _4= v_self;
  _line(60);
  _4=_sendv(s_size, 1, _4);
  _5= l_17;
  {
    int _l= (long)_4 >> 1;
    int _r= (long)_5 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_4) && ((_s ^ (_s << 1)) >= 0))  _4= (oop)(long)(_s << 1 | 1);  else _4= _sendv(s__2d, 2, _4, _5);
  }
  _line(60);
  _2=_sendv(s_between_and_, 3, _2, _3, _4);
  if (!_2) goto _l1;
 {
  _1= v_SmallInteger;
  _2= v_self;
  _3= v_offset;
  _line(60);
  _3=_sendv(s__5fintegerValue, 1, _3);
  _line(60);
  _2=_sendv(s__5fat_5f_, 2, _2, _3);
  _line(60);
  _1=_sendv(s_value_5f_, 2, _1, _2);
  _leave();
  return _1;
 }
 _l1:;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info18= { "_at_:", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 62, 64, &__info15 };
static oop Symbol___5fat_5f_(oop v__closure, oop v_stateful_self, oop v_self, oop v__offset)
 {
  _enter(&__info18);
  oop _1= 0;
  _line(62);
 {
# define self ((struct t_Symbol *)v_self)
 _return (oop)(long)(((char *)self->v__elements)[(long)v__offset]); 
# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info19= { "hash", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 64, 65, &__info18 };
static oop Symbol__hash(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info19);
  oop _1= 0;
  _line(64);
  _1= v_self;
  _line(64);
  _1=_sendv(s_identityHash, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info20= { "=", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 65, 67, &__info19 };
static oop Symbol___3d(oop v__closure, oop v_stateful_self, oop v_self, oop v_other)
 {
  _enter(&__info20);
  oop _1= 0;
  oop _2= 0;
  _line(65);
  _1= v_self;
  _2= v_other;
  _1= (_1 == _2) ? v_true : v_false;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info21= { "isKeyword", "Object", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 67, 68, &__info20 };
static oop Object__isKeyword(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info21);
  oop _1= 0;
  _line(67);
  _1= v_nil;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info22= { "isKeyword", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 68, 70, &__info21 };
static oop Symbol__isKeyword(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info22);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(68);
  _1= v_self;
  _2= v_self;
  _line(68);
  _2=_sendv(s_size, 1, _2);
  _3= l_23;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2d, 2, _2, _3);
  }
  _line(68);
  _1=_sendv(s_at_, 2, _1, _2);
  _2= l_24;
  _1= (_1 == _2) ? v_true : v_false;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info25= { "printOn:", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 70, 72, &__info22 };
static oop Symbol__printOn_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aStream)
 {
  _enter(&__info25);
  oop _1= 0;
  oop _2= 0;
  _line(70);
  _1= v_aStream;
  _2= l_26;
  _line(70);
  _sendv(s_nextPut_, 2, _1, _2);
  _2= v_self;
  _line(70);
  _2=_sendv(s_asString, 1, _2);
  _1=_sendv(s_nextPutAll_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info30= { "[] do:", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 72, 74, &__info25 };
static oop b_30(oop v__closure, oop v__self, oop v_i)
 {
  _enter(&__info30);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(72);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* unaryBlock */
  _2= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[2];  /* self */
  _3= v_i;
  _line(72);
  _2=_sendv(s_at_, 2, _2, _3);
  _line(72);
  _1=_sendv(s_value_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info27= { "do:", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 72, 74, &__info30 };
static oop Symbol__do_(oop v__closure, oop v_stateful_self, oop v_self, oop v_unaryBlock)
 {
  _enter(&__info27);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 6);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  ((oop *)_state1)[3]= v_stateful_self;
  ((oop *)_state1)[2]= v_self;
  ((oop *)_state1)[1]= v_unaryBlock;
  _line(72);
  _1= l_28;
  _2= ((oop *)_state1)[2];  /* self */
  _line(72);
  _2=_sendv(s_size, 1, _2);
  _3= l_29;
  {
    int _l= (long)_2 >> 1;
    int _r= (long)_3 >> 1;
    int _s= (_l - _r);
    if ((1 & (long)_2) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(long)(_s << 1 | 1);  else _2= _sendv(s__2d, 2, _2, _3);
  }
  /* Scope('i'->ArgumentVariableNode) */
  /* Scope('_size'->SlotVariableNode 'self'->ArgumentVariableNode 'stateful_self'->ArgumentVariableNode 'unaryBlock'->ArgumentVariableNode '_elements'->SlotVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_30, 1, 0, ((oop *)_state1), 0);
  _line(72);
  _1=_sendv(s_to_do_, 3, _1, _2, _3);
  _1= ((oop *)_state1)[2];  /* self */
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info31= { "bePrototype:", "Symbol", "/Users/chazu/dev/c/idst-with-history/function/objects/Symbol.st", 0, 74, 75, &__info27 };
static oop Symbol__bePrototype_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anObject)
 {
  _enter(&__info31);
  oop _1= 0;
  oop _2= 0;
  _line(74);
  _1= v_self;
  _line(74);
  _1=_sendv(s_asString, 1, _1);
  _2= v_anObject;
  _line(74);
  _1=_sendv(s_bePrototype_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "Symbol.st", 0, 0, 0, &__info31 };
void __id__init__Symbol(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
# define GC_add_roots _libid->gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info1);

  _sendv(s__5fimport_, 3, _libid->_object, "Objects", "__id__init__Objects");
  v__object= _libid->import("_object");
  v__vector= _libid->import("_vector");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_Magnitude= _libid->import("Magnitude");
  v_Number= _libid->import("Number");
  v_Integer= _libid->import("Integer");
  v_SmallInteger= _libid->import("SmallInteger");
  v_Symbol= _libid->import("Symbol");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_ByteArray= _libid->import("ByteArray");
  v_String= _libid->import("String");
  v_IdentitySet= _libid->import("IdentitySet");
  v_IdentityDictionary= _libid->import("IdentityDictionary");
  v_SlotDictionary= _libid->import("SlotDictionary");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_BlockClosure= _libid->import("BlockClosure");
  v_ReadStream= _libid->import("ReadStream");
  v_FileStream= _libid->import("FileStream");
  v_nil= _libid->import("nil");
  v_true= _libid->import("true");
  v_false= _libid->import("false");
  _libid->method(v_Object, s_isSymbol, (_imp_t)Object__isSymbol);
  _libid->method(v_Symbol, s_isSymbol, (_imp_t)Symbol__isSymbol);
  _libid->method(v_Symbol, s_intern_5f_size_5f_, (_imp_t)Symbol__intern_5f_size_5f_);
  _libid->method(v_Symbol, s_intern_5f_, (_imp_t)Symbol__intern_5f_);
  _libid->method(v_Symbol, s_intern_, (_imp_t)Symbol__intern_);
  _libid->method(v_Symbol, s__5fbytes, (_imp_t)Symbol___5fbytes);
  _libid->method(v_Symbol, s_size, (_imp_t)Symbol__size);
  _libid->method(v_Symbol, s__5fstringValue, (_imp_t)Symbol___5fstringValue);
  _libid->method(v_Symbol, s_asSymbol, (_imp_t)Symbol__asSymbol);
  _libid->method(v_Symbol, s_asString, (_imp_t)Symbol__asString);
  _libid->method(v_Symbol, s_beginsWith_, (_imp_t)Symbol__beginsWith_);
  _libid->method(v_Symbol, s_endsWith_, (_imp_t)Symbol__endsWith_);
  _libid->method(v_Symbol, s__2c, (_imp_t)Symbol___2c);
  _libid->method(v_Symbol, s_append_, (_imp_t)Symbol__append_);
  l_16= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  l_17= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_Symbol, s_at_, (_imp_t)Symbol__at_);
  _libid->method(v_Symbol, s__5fat_5f_, (_imp_t)Symbol___5fat_5f_);
  _libid->method(v_Symbol, s_hash, (_imp_t)Symbol__hash);
  _libid->method(v_Symbol, s__3d, (_imp_t)Symbol___3d);
  _libid->method(v_Object, s_isKeyword, (_imp_t)Object__isKeyword);
  l_23= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  l_24= _sendv(s_value_5f_, 2, v_SmallInteger, 58);
  _libid->method(v_Symbol, s_isKeyword, (_imp_t)Symbol__isKeyword);
  l_26= _sendv(s_value_5f_, 2, v_SmallInteger, 35);
  _libid->method(v_Symbol, s_printOn_, (_imp_t)Symbol__printOn_);
  l_28= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  l_29= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_Symbol, s_do_, (_imp_t)Symbol__do_);
  _libid->method(v_Symbol, s_bePrototype_, (_imp_t)Symbol__bePrototype_);
  _leave();
}
